services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pblog-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:z
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini:z
    networks:
      - pblog-network
      - mysql_default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: pblog-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:z
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:z
    networks:
      - pblog-network
    depends_on:
      - app

networks:
  pblog-network:
    driver: bridge
  mysql_default:
    external: true
