<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HSSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $hs = [
            ['kodeHS' => '1012100', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1012900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1013010', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1013090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1019000', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '1022100', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1022911', 'uraianBarang' => '---- Oxen'],
            ['kodeHS' => '1022919', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '1022990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '1023100', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1023900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1029010', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1029090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1031000', 'uraianBarang' => '- Bibit'],
            ['kodeHS' => '1039100', 'uraianBarang' => '-- Berat kurang dari 50 Kg'],
            ['kodeHS' => '1039200', 'uraianBarang' => '-- Berat 50 Kg atau lebih'],
            ['kodeHS' => '1041010', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1041090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1042010', 'uraianBarang' => '-- Bibit'],
            ['kodeHS' => '1042090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1051110', 'uraianBarang' => '--- Ayam bibit'],
            ['kodeHS' => '1051190', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '1051210', 'uraianBarang' => '--- Kalkun bibit'],
            ['kodeHS' => '1051290', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '1051310', 'uraianBarang' => '--- Bebek bibit'],
            ['kodeHS' => '1051390', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '1051410', 'uraianBarang' => '--- Angsa bibit'],
            ['kodeHS' => '1051490', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '1051510', 'uraianBarang' => '--- Ayam guinea bibit'],
            ['kodeHS' => '1051590', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '1059410', 'uraianBarang' => '--- Ayam bibit,selain ayam sabung'],
            ['kodeHS' => '1059441', 'uraianBarang' => '---- Berat tidak lebih dari 2 kg'],
            ['kodeHS' => '1059449', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '1059491', 'uraianBarang' => '---- Berat tidak lebih dari 2 kg'],
            ['kodeHS' => '1059499', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '1059910', 'uraianBarang' => '--- Bebek bibit'],
            ['kodeHS' => '1059920', 'uraianBarang' => '--- Bebek lainnya'],
            ['kodeHS' => '1059930', 'uraianBarang' => '--- Angsa, kalkun dan ayam guinea, bibit'],
            ['kodeHS' => '1059940', 'uraianBarang' => '--- Angsa, kalkun dan ayam guinea lainnya'],
            ['kodeHS' => '1061100', 'uraianBarang' => '-- Primata'],
            ['kodeHS' => '1061210', 'uraianBarang' => '--- Paus,lumba-lumba dan porpoise (binatang menyusui dari ordo cetacea);manate dan dugong (binatang menyusui dari ordo sirenia)'],
            ['kodeHS' => '1061220', 'uraianBarang' => '--- Anjing laut, singa laut dan beruang laut (mamalia dari sub ordo pinnipedia)'],
            ['kodeHS' => '1061300', 'uraianBarang' => '-- Unta dan camelid lainnya (camelidae)'],
            ['kodeHS' => '1061400', 'uraianBarang' => '-- Kelinci dan hare'],
            ['kodeHS' => '1061900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1062000', 'uraianBarang' => '- Binatang melata (termasuk ular dan penyu)'],
            ['kodeHS' => '1063100', 'uraianBarang' => '-- Burung pemangsa'],
            ['kodeHS' => '1063200', 'uraianBarang' => '-- Psittaciformes (termasuk burung beo, parkit, macaw dan kakatua)'],
            ['kodeHS' => '1063300', 'uraianBarang' => '-- Burung unta; emu (dromatus novaehollandiae)'],
            ['kodeHS' => '1063900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1064100', 'uraianBarang' => '-- Lebah'],
            ['kodeHS' => '1064900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '1069000', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '02011000', 'uraianBarang' => '- Karkas dan setengah karkas'],
            ['kodeHS' => '02012000', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '02013000', 'uraianBarang' => '- Daging tanpa tulang'],
            ['kodeHS' => '02021000', 'uraianBarang' => '- Karkas dan setengah karkas'],
            ['kodeHS' => '02022000', 'uraianBarang' => '- Potongan daging lainnya, bertulang'],
            ['kodeHS' => '02023000', 'uraianBarang' => '- Daging tanpa tulang'],
            ['kodeHS' => '02031100', 'uraianBarang' => '-- Karkas dan setengah karkas'],
            ['kodeHS' => '02031200', 'uraianBarang' => '-- Paha, bahu dan potongannya, bertulang'],
            ['kodeHS' => '02031900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '02032100', 'uraianBarang' => '-- Karkas dan setengah karkas'],
            ['kodeHS' => '02032200', 'uraianBarang' => '-- Paha, bahu dan potongannya, bertulang'],
            ['kodeHS' => '02032900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '02041000', 'uraianBarang' => '- Karkas dan setengah karkas dari biri biri muda, segar atau dingin'],
            ['kodeHS' => '02042100', 'uraianBarang' => '-- Karkas dan setengah karkas'],
            ['kodeHS' => '02042200', 'uraianBarang' => '-- Potongan daging lainnya, bertulang'],
            ['kodeHS' => '02042300', 'uraianBarang' => '-- Daging tanpa tulang'],
            ['kodeHS' => '02043000', 'uraianBarang' => '- Karkas dan setengah karkas dari biri biri muda, beku'],
            ['kodeHS' => '02044100', 'uraianBarang' => '-- Karkas dan setengah karkas'],
            ['kodeHS' => '02044200', 'uraianBarang' => '-- Potongan daging lainnya, bertulang'],
            ['kodeHS' => '02044300', 'uraianBarang' => '-- Daging tanpa tulang'],
            ['kodeHS' => '02045000', 'uraianBarang' => '- Daging kambing'],
            ['kodeHS' => '02061000', 'uraianBarang' => '- Dari binatang jenis lembu, segar atau dingin'],
            ['kodeHS' => '02062100', 'uraianBarang' => '-- Lidah'],
            ['kodeHS' => '02062200', 'uraianBarang' => '-- Hati'],
            ['kodeHS' => '02062900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '02063000', 'uraianBarang' => '- Dari babi, segar atau dingin'],
            ['kodeHS' => '02064100', 'uraianBarang' => '-- Hati'],
            ['kodeHS' => '02064900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '02068000', 'uraianBarang' => '- Lain-lain, segar atau dingin'],
            ['kodeHS' => '02069000', 'uraianBarang' => '- Lain-lain, beku'],
            ['kodeHS' => '02071100', 'uraianBarang' => '-- Tidak di potong menjadi bagian-bagian, segar atau dingin'],
            ['kodeHS' => '02071200', 'uraianBarang' => '-- Tidak di potong menjadi bagian-bagian, beku'],
            ['kodeHS' => '02071300', 'uraianBarang' => '-- Potongan dan sisanya, segar atau dingin'],
            ['kodeHS' => '02071410', 'uraianBarang' => '--- Sayap'],
            ['kodeHS' => '02071420', 'uraianBarang' => '--- Paha'],
            ['kodeHS' => '02071430', 'uraianBarang' => '--- Hati'],
            ['kodeHS' => '02071491', 'uraianBarang' => '---- Daging yang dihilangkan tulangnya atau dipisahkan dengan mesin'],
            ['kodeHS' => '02071499', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '02072400', 'uraianBarang' => '-- Tidak di potong menjadi bagian bagian, segar atau dingin'],
            ['kodeHS' => '02072500', 'uraianBarang' => '-- Tidak di potong menjadi bagian bagian, beku'],
            ['kodeHS' => '02072600', 'uraianBarang' => '-- Potongan dan sisanya, segar atau dingin'],
            ['kodeHS' => '02072710', 'uraianBarang' => '--- Hati'],
            ['kodeHS' => '02074100', 'uraianBarang' => '-- Tidak di potong menjadi bagian bagian, segar atau dingin'],
            ['kodeHS' => '02074200', 'uraianBarang' => '-- Tidak di potong menjadi bagian bagian, beku'],
            ['kodeHS' => '02074300', 'uraianBarang' => '-- Hati berlemak, segar atau dingin'],
            ['kodeHS' => '02074400', 'uraianBarang' => '-- Lain-lain, segar atau dingin'],
            ['kodeHS' => '02074510', 'uraianBarang' => '--- Hati berlemak'],
            ['kodeHS' => '02074590', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '02075100', 'uraianBarang' => '-- Tidak di potong menjadi bagian bagian, segar atau dingin'],
            ['kodeHS' => '02075200', 'uraianBarang' => '-- Tidak di potong menjadi bagian bagian, beku'],
            ['kodeHS' => '02075300', 'uraianBarang' => '-- Hati berlemak, segar atau dingin'],
            ['kodeHS' => '02075400', 'uraianBarang' => '-- Lain-lain, segar atau dingin'],
            ['kodeHS' => '02075519', 'uraianBarang' => '-- Lain-lain, beku'],
            ['kodeHS' => '02075590', 'uraianBarang' => '-- Lain-lain, beku'],
            ['kodeHS' => '02076010', 'uraianBarang' => '-- Lain-lain, beku'],
            ['kodeHS' => '02076020', 'uraianBarang' => '-- Lain-lain, beku'],
            ['kodeHS' => '02076030', 'uraianBarang' => '-- Lain-lain, beku'],
            ['kodeHS' => '02076040', 'uraianBarang' => '-- Potongan dan sisanya, beku'],
            ['kodeHS' => '02081000', 'uraianBarang' => '- Dari kelinci atau hare'],
            ['kodeHS' => '02083000', 'uraianBarang' => '- Dari primata'],
            ['kodeHS' => '02084010', 'uraianBarang' => '-- Dari paus, lumba lumba dan porpoise(binatang menyusui dari ordo Cetacea); dari manate dan dugong (binatang menyusui dari ordo Sirenia)'],
            ['kodeHS' => '02084090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '02085000', 'uraianBarang' => '- Dari binatang melata (termasuk ular dan penyu)'],
            ['kodeHS' => '02086000', 'uraianBarang' => '- Dari unta dan Camelid lainnya (Camelidae)'],
            ['kodeHS' => '02089010', 'uraianBarang' => '-- Kaki kodok'],
            ['kodeHS' => '02089090', 'uraianBarang' => '--Lain-lain'],
            ['kodeHS' => '02091000', 'uraianBarang' => '- Dari babi'],
            ['kodeHS' => '02099000', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '02101100', 'uraianBarang' => '-- Paha, bahu, dan potongannya bertulang'],
            ['kodeHS' => '02101200', 'uraianBarang' => '-- Perut (streaky) dan potongannya'],
            ['kodeHS' => '02101930', 'uraianBarang' => '--- Bacon; paha tanpa tulang'],
            ['kodeHS' => '02101990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '02102000', 'uraianBarang' => '- Daging binatang jenis lembu'],
            ['kodeHS' => '02109100', 'uraianBarang' => '-- Dari primata'],
            ['kodeHS' => '02109210', 'uraianBarang' => '--- Dari paus, lumba lumba dan porpoise(binatang menyusui dari ordo Cetacea); dari manate dan dugong (binatang menyusui dari ordo Sirenia)'],
            ['kodeHS' => '02109290', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '02109300', 'uraianBarang' => '-- Dari binatang melata (termasuk ular dan penyu)'],
            ['kodeHS' => '02109910', 'uraianBarang' => '--- Daging ayam dipotong berbentuk kubus, dikeringbekukan'],
            ['kodeHS' => '02109920', 'uraianBarang' => '--- Kulit babi dikeringkan'],
            ['kodeHS' => '02109990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03011110', 'uraianBarang' => '--- Benih ikan'],
            ['kodeHS' => '03011191', 'uraianBarang' => '---- Koi (Cyprinus carpio)'],
            ['kodeHS' => '03011192', 'uraianBarang' => '---- Ikan mas koki (carassius auratus)'],
            ['kodeHS' => '03011193', 'uraianBarang' => '---- Ikan cupang aduan (beta splendes)'],
            ['kodeHS' => '03011199', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03011990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03019321', 'uraianBarang' => '---- Bibit, selain benih ikan'],
            ['kodeHS' => '03019329', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03019332', 'uraianBarang' => '---- Benih ikan'],
            ['kodeHS' => '03019339', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03019400', 'uraianBarang' => '-- Tuna sirip biru Atlantik dan Pasifik (Thunnus thynnus, Thunnus orientalis)'],
            ['kodeHS' => '03019500', 'uraianBarang' => '-- Tuna sirip biru selatan (Thunnus maccoyii)'],
            ['kodeHS' => '03019911', 'uraianBarang' => '---- Bibit'],
            ['kodeHS' => '03019923', 'uraianBarang' => '---- Ikan mas lainnya'],
            ['kodeHS' => '03019924', 'uraianBarang' => '---- Lain-lain, bibit'],
            ['kodeHS' => '03019929', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03019933', 'uraianBarang' => '---- Kerapu sunu (Plectropomus leopardus)'],
            ['kodeHS' => '03019934', 'uraianBarang' => '---- Kerapu macan (Epinephelus fuscoguttatus)'],
            ['kodeHS' => '03019935', 'uraianBarang' => '---- Kerapu bebek (Cromileptes altivelis)'],
            ['kodeHS' => '03019941', 'uraianBarang' => '---- Tilapia (Oreochromis spp.)'],
            ['kodeHS' => '03019949', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03019950', 'uraianBarang' => '--- Lain-lain, ikan air laut'],
            ['kodeHS' => '03019990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03021400', 'uraianBarang' => '-- Salmon Atlantik (Salmo salar) dan salmon danube (hucho hocho)'],
            ['kodeHS' => '03022200', 'uraianBarang' => '-- Plaice (Pleuronectes platessa)'],
            ['kodeHS' => '03022300', 'uraianBarang' => '-- Sole (Solea spp.)'],
            ['kodeHS' => '03022400', 'uraianBarang' => '-- Turbots (Psetta maxima)'],
            ['kodeHS' => '03023100', 'uraianBarang' => '-- Albacore atau tuna sirip panjang (Thunnus alalunga)'],
            ['kodeHS' => '03023500', 'uraianBarang' => '-- Tuna sirip biru Atlantik dan Pasifik (Thunnus thynnus, Thunnus orientalis)'],
            ['kodeHS' => '03023600', 'uraianBarang' => '-- Tuna sirip biru selatan (Thunnus maccoyii)'],
            ['kodeHS' => '03024100', 'uraianBarang' => '-- Herring (Clupen harengus, clupea pallasii)'],
            ['kodeHS' => '03024200', 'uraianBarang' => '-- Teri (engraulis spp.)'],
            ['kodeHS' => '03024300', 'uraianBarang' => '-- Sarden (sardina pilchardus, sardinops spp.), sardinella (sardinella spp.), brisling atau sparts (sprattus sprattus)'],
            ['kodeHS' => '03024500', 'uraianBarang' => '-- Makarel jack dan makarel kuda (trachurus spp.)'],
            ['kodeHS' => '03024600', 'uraianBarang' => '-- Cobia (rachycentron canadum)'],
            ['kodeHS' => '03024900', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '03025100', 'uraianBarang' => '-- Cod (gadus morhua, gadus ogac, gadus macrocephalus)'],
            ['kodeHS' => '03025300', 'uraianBarang' => '-- Coalfish (Pollachius virens)'],
            ['kodeHS' => '03025400', 'uraianBarang' => '-- Hake (merluccius spp., urophycis spp.)'],
            ['kodeHS' => '03025500', 'uraianBarang' => '-- Alaska pollock (Theragra chalcogramma)'],
            ['kodeHS' => '03027100', 'uraianBarang' => '-- Tilapia (Oreochromis spp.)'],
            ['kodeHS' => '03027290', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03028100', 'uraianBarang' => '-- Dogfish dan hiu lainnya'],
            ['kodeHS' => '03028911', 'uraianBarang' => '---- Kerapu'],
            ['kodeHS' => '03028913', 'uraianBarang' => '---- Bluntnose lizardfish (trachinocephalus myops)'],
            ['kodeHS' => '03028915', 'uraianBarang' => '---- Indian threadfins (polynemus indicus)'],
            ['kodeHS' => '03028918', 'uraianBarang' => '---- Kakap merah (lutjanus argentimaculatus)'],
            ['kodeHS' => '03028919', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03028923', 'uraianBarang' => '---- Silver grunts (pomadasys argenteus)'],
            ['kodeHS' => '03029100', 'uraianBarang' => '-- Hati, telur dan sperma'],
            ['kodeHS' => '03029900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03031300', 'uraianBarang' => '-- Salmon antlantik (salmo salar) dan salmon danube (hucho hucho)'],
            ['kodeHS' => '03031400', 'uraianBarang' => '-- Trout ((salmo trutta, oncorhynchus mykiss, oncorhynchus clarki, oncorhynchus aguabonita, oncorhynchus gilae, oncorhynchus apache dan oncorhynchus chrysogaster)'],
            ['kodeHS' => '03032300', 'uraianBarang' => '-- Tilapia (Oreochromis spp.)'],
            ['kodeHS' => '03032600', 'uraianBarang' => '-- Sidat (anguilla spp.)'],
            ['kodeHS' => '03033100', 'uraianBarang' => '-- Halibatu (Reinhardtius, hippoglossoides, hippoglossus hippoglosus, hippoglossus stenolepis)'],
            ['kodeHS' => '03033400', 'uraianBarang' => '-- Turbots (Psetta maxima)'],
            ['kodeHS' => '03034100', 'uraianBarang' => '-- Albacore atau tuna sirip panjang (Thunnus Alalunga)'],
            ['kodeHS' => '03034200', 'uraianBarang' => '-- Tuna sirip kuning (Thunnus Albacares)'],
            ['kodeHS' => '03034510', 'uraianBarang' => '--- Tuna sirip biru Atlantik (Thunnus thynnus)'],
            ['kodeHS' => '03034600', 'uraianBarang' => '-- Tuna sirip biru selatan (Thunnus maccoyii)'],
            ['kodeHS' => '03011195', 'uraianBarang' => '---- Arwana (scleropages formosus)'],
            ['kodeHS' => '03011910', 'uraianBarang' => '--- Benih ikan'],
            ['kodeHS' => '03019100', 'uraianBarang' => '-- Trout (salmo trutta, oncorhynchus mykiss, oncorhynchus clarki, oncorhynchus aguabonita, oncorhynchus gilae, oncorhynchus apache dan oncorhynchus chrysogaster)'],
            ['kodeHS' => '03019200', 'uraianBarang' => '- Sidat (anguilla spp.)'],
            ['kodeHS' => '03019322', 'uraianBarang' => '---- Benih ikan'],
            ['kodeHS' => '03019331', 'uraianBarang' => '---- Bibit, selain benih ikan'],
            ['kodeHS' => '03019919', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03019922', 'uraianBarang' => '---- Ikan mas lainnya, bibit'],
            ['kodeHS' => '03019931', 'uraianBarang' => '---- Bandeng, bibit'],
            ['kodeHS' => '03019932', 'uraianBarang' => '---- Bandeng, lain-lain'],
            ['kodeHS' => '03019936', 'uraianBarang' => '---- Kerapu lainnya'],
            ['kodeHS' => '03019942', 'uraianBarang' => '---- Ikan mas lainnya, untuk bibit'],
            ['kodeHS' => '03021100', 'uraianBarang' => '-- Trout (salmo trutta, oncorhynchus mykiss, oncorhynchus clarki, oncorhynchus aguabonita, oncorhynchus gilae, oncorhynchus apache dan oncorhynchus chrysogaster)'],
            ['kodeHS' => '03021300', 'uraianBarang' => '-- Salmon pasifik (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou dan Oncorhynchus rhodurus)'],
            ['kodeHS' => '03021900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03022100', 'uraianBarang' => '-- Halibut (Reinhardtius hippoglossidaes, Hippoglossus hippoglosus, hippoglossus stenolepis)'],
            ['kodeHS' => '03022900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03023200', 'uraianBarang' => '-- Tuna sirip kuning (Thunnus albacares)'],
            ['kodeHS' => '03023300', 'uraianBarang' => '-- Cakalang (stripe-bellied bonito) (katsuwonus pelamis)'],
            ['kodeHS' => '03023400', 'uraianBarang' => '-- Tuna mata besar (Thunnus obesus)'],
            ['kodeHS' => '03023900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03024400', 'uraianBarang' => '-- Makarel (scomber scombrus, scomber australasicus, scomber japanicus)'],
            ['kodeHS' => '03024700', 'uraianBarang' => '-- todak (xiphias gladius)'],
            ['kodeHS' => '03025200', 'uraianBarang' => '-- Haddock (Melanogrammus aeglefinus)'],
            ['kodeHS' => '03025600', 'uraianBarang' => '-- Blue whitings (Micromesistius poutassou, Micromesistius australis)'],
            ['kodeHS' => '03025900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03027210', 'uraianBarang' => '--- Patin (pangasius pangasius)'],
            ['kodeHS' => '03027300', 'uraianBarang' => '-- Ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.)'],
            ['kodeHS' => '03027400', 'uraianBarang' => '-- Sidat (Anguilla spp.)'],
            ['kodeHS' => '03027900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03028200', 'uraianBarang' => '-- Pari dan skates (rajidae)'],
            ['kodeHS' => '03028300', 'uraianBarang' => '-- Toothfish (Dissostichus spp.)'],
            ['kodeHS' => '03028400', 'uraianBarang' => '-- Seabass (dicentrarchus spp.)'],
            ['kodeHS' => '03028500', 'uraianBarang' => '-- Seabream (sparidae)'],
            ['kodeHS' => '03028912', 'uraianBarang' => '---- Longfin majorra'],
            ['kodeHS' => '03028914', 'uraianBarang' => '---- Layur (lepturacanthus savala), belanger\'s croakers (johnius belangerii), reeve\'s croakers (chrysochir aureus) dan bigeye croakers (pennahia anea)'],
            ['kodeHS' => '03028916', 'uraianBarang' => '---- Scad torpedo (megalaspis cordyla), spotted sicklefish (drepane punctata) dan barracuda besar (sphyraena barracuda)'],
            ['kodeHS' => '03028917', 'uraianBarang' => '---- Bawal hitam (parastromatus niger)'],
            ['kodeHS' => '03028922', 'uraianBarang' => '---- Swamp barb (puntius chola)'],
            ['kodeHS' => '03028927', 'uraianBarang' => '---- Hilsa shad (telualosa ilisha)'],
            ['kodeHS' => '03028928', 'uraianBarang' => '---- Wallago (Wallago attu) dan giant river-catfish (sperata seenghala)'],
            ['kodeHS' => '03028929', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03029200', 'uraianBarang' => '-- Sirip hiu'],
            ['kodeHS' => '03031100', 'uraianBarang' => '-- Salmon sockeye (salmon merah) (oncorhynchus nerka)'],
            ['kodeHS' => '03031200', 'uraianBarang' => '-- Salmon pasifik lainnya (oncorhynchus gorbuscha, oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou dan Oncorhynchus rhodurus)'],
            ['kodeHS' => '03031900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03032400', 'uraianBarang' => '-- Catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.)'],
            ['kodeHS' => '03032500', 'uraianBarang' => '-- Ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.)'],
            ['kodeHS' => '03032900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03033200', 'uraianBarang' => '-- Plaice (Pleuronectes platessa)'],
            ['kodeHS' => '03033300', 'uraianBarang' => '-- Sole (Solea spp.)'],
            ['kodeHS' => '03033900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03034300', 'uraianBarang' => '-- Cakalang (stripe-bellied bonito) (katsuwonus pelamis)'],
            ['kodeHS' => '03034400', 'uraianBarang' => '-- Tuna mata besar (Thunnus obesus)'],
            ['kodeHS' => '03034590', 'uraianBarang' => '--- Tuna sirip biru Pasifik (Thunnus orientalis)'],
            ['kodeHS' => '03034900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03034910', 'uraianBarang' => '--- Longtail tuna (Thunnus tonggol)'],
            ['kodeHS' => '03034990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03035100', 'uraianBarang' => '-- Herring (Clupen harengus, clupea pallasii)'],
            ['kodeHS' => '03035300', 'uraianBarang' => '-- Sarden (sardina pilchardus, sardinops spp.), sardinella (sardinella spp.), brisling atau sparts (sprattus sprattus)'],
            ['kodeHS' => '03035410', 'uraianBarang' => '--- Makarel (scomber scombrus, scomber australasicus)'],
            ['kodeHS' => '03035420', 'uraianBarang' => '--- Makarel (scomber japanicus)'],
            ['kodeHS' => '03035500', 'uraianBarang' => '-- Makarel jack dan makarel kuda (trachurus spp.)'],
            ['kodeHS' => '03035600', 'uraianBarang' => '-- Cobia (rachycentron canadum)'],
            ['kodeHS' => '03035700', 'uraianBarang' => '-- Todak (xiphias gladius)'],
            ['kodeHS' => '03035910', 'uraianBarang' => '--- Makarel indian (rastrelliger spp.)'],
            ['kodeHS' => '03035920', 'uraianBarang' => '--- Bawal putih (pampus spp.)'],
            ['kodeHS' => '03035990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03036300', 'uraianBarang' => '-- Cod (gadus morhua, gadus ogac, gadus macrocephalus)'],
            ['kodeHS' => '03036400', 'uraianBarang' => '-- Haddock (Melanogrammus aeglefinus)'],
            ['kodeHS' => '03036500', 'uraianBarang' => '-- Coalfish (Pollachius virens)'],
            ['kodeHS' => '03036600', 'uraianBarang' => '-- Hake (merluccius spp., urophycis spp.)'],
            ['kodeHS' => '03036700', 'uraianBarang' => '-- Alaska pollock (Theragra chalcogramma)'],
            ['kodeHS' => '03036800', 'uraianBarang' => '-- Blue whitings (Micromesistius poutassou, Micromesistius australis)'],
            ['kodeHS' => '03036900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03038100', 'uraianBarang' => '-- Dogfish dan hiu lainnya'],
            ['kodeHS' => '03038200', 'uraianBarang' => '-- Pari dan skates (rajidae)'],
            ['kodeHS' => '03038300', 'uraianBarang' => '-- Toothfish (Dissostichus spp.)'],
            ['kodeHS' => '03038400', 'uraianBarang' => '-- Seabass (dicentrarchus spp.)'],
            ['kodeHS' => '03038911', 'uraianBarang' => '---- Kerapu'],
            ['kodeHS' => '03038913', 'uraianBarang' => '---- Bluntnose lizardfish (trachinocephalus myops)'],
            ['kodeHS' => '03038914', 'uraianBarang' => '---- Layur (lepturacanthus savala), belanger\'s croakers (johnius belangerii), reeve\'s croakers (chrysochir aureus) dan bigeye croakers (pennahia anea)'],
            ['kodeHS' => '03038915', 'uraianBarang' => '---- Indian threadfins (polynemus indicus)'],
            ['kodeHS' => '03038916', 'uraianBarang' => '---- Scad torpedo (megalaspis cordyla), spotted sicklefish (drepane punctata) dan barracuda besar (sphyraena barracuda)'],
            ['kodeHS' => '03038917', 'uraianBarang' => '---- Bawal hitam (parastromatus niger)'],
            ['kodeHS' => '03038918', 'uraianBarang' => '---- kakap merah (lutjanus argentimaculatus)'],
            ['kodeHS' => '03038922', 'uraianBarang' => '---- Swamp barb (puntius chola)'],
            ['kodeHS' => '03038923', 'uraianBarang' => '---- Bandeng (Chanos chanos)'],
            ['kodeHS' => '03038924', 'uraianBarang' => '---- Silver grunts (pomadasys argenteus)'],
            ['kodeHS' => '03038927', 'uraianBarang' => '---- Hilsa shad (telualosa ilisha)'],
            ['kodeHS' => '03038928', 'uraianBarang' => '---- Wallago (Wallago attu) dan giant river-catfish (sperata seenghala)'],
            ['kodeHS' => '03038929', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03039100', 'uraianBarang' => '-- Hati, telur dan sperma'],
            ['kodeHS' => '03039200', 'uraianBarang' => '-- Sirip hiu'],
            ['kodeHS' => '03039900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03043100', 'uraianBarang' => '-- Tilapia (Oreochromis spp.)'],
            ['kodeHS' => '03043200', 'uraianBarang' => '-- Catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.)'],
            ['kodeHS' => '03043300', 'uraianBarang' => '-- Nile perch (lates niloticus)'],
            ['kodeHS' => '03043900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03044100', 'uraianBarang' => '-- Salmon pasifik (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou dan Oncorhynchus rhodurus), Salmon Atlantik (Salmo salar) dan salmon danube (hucho hocho)'],
            ['kodeHS' => '03044200', 'uraianBarang' => '-- Trout (salmo trutta, oncorhynchus mykiss, oncorhynchus clarki, oncorhynchus aguabonita, oncorhynchus gilae, oncorhynchus apache dan oncorhynchus chrysogaster)'],
            ['kodeHS' => '03044300', 'uraianBarang' => '-- Ikan pipih (Pleuronectidae, bothidae, cynoglossidae, soleidae, scophthalmidae dan citharidae)'],
            ['kodeHS' => '03044400', 'uraianBarang' => '-- Ikan dari keluarga Bregmacerotidae, Euclichthyidae, Gadidae, Macrouridae, Melanonidae, Merlucciidae, Moridae dan Muraenolepididae'],
            ['kodeHS' => '03044500', 'uraianBarang' => '-- Todak (xiphias gladius)'],
            ['kodeHS' => '03044600', 'uraianBarang' => '-- Toothfish (Dissostichus spp.)'],
            ['kodeHS' => '03044700', 'uraianBarang' => '-- Dogfish dan hiu lainnya'],
            ['kodeHS' => '03044800', 'uraianBarang' => '-- Pari dan skates (rajidae)'],
            ['kodeHS' => '03044900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03045100', 'uraianBarang' => '-- Tilapia (Oreochromis spp.), catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.), ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.), sidat (anguilla spp.), nile perch (lates niloticus) dan gabus (channa spp.)'],
            ['kodeHS' => '03045200', 'uraianBarang' => '-- Salmon (Salmonidae)'],
            ['kodeHS' => '03045300', 'uraianBarang' => '-- Ikan dari keluarga Bregmacerotidae, Euclichthyidae, Gadidae, Macrouridae, Melanonidae, Merlucciidae, Moridae dan Muraenolepididae'],
            ['kodeHS' => '03045400', 'uraianBarang' => '-- Todak (xiphias gladius)'],
            ['kodeHS' => '03045500', 'uraianBarang' => '-- Toothfish (Dissostichus spp.)'],
            ['kodeHS' => '03045600', 'uraianBarang' => '-- Dogfish dan hiu lainnya'],
            ['kodeHS' => '03045700', 'uraianBarang' => '-- Pari dan skates (rajidae)'],
            ['kodeHS' => '03045900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03046100', 'uraianBarang' => '-- Tilapia (Oreochromis spp.)'],
            ['kodeHS' => '03046200', 'uraianBarang' => '-- Catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.)'],
            ['kodeHS' => '03046300', 'uraianBarang' => '-- Nile perch (lates niloticus)'],
            ['kodeHS' => '03046900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03047100', 'uraianBarang' => '-- Cod (gadus morhua, gadus ogac, gadus macrocephalus)'],
            ['kodeHS' => '03047200', 'uraianBarang' => '-- Haddock (Melanogrammus aeglefinus)'],
            ['kodeHS' => '03047300', 'uraianBarang' => '-- Coalfish (Pollachius virens)'],
            ['kodeHS' => '03047400', 'uraianBarang' => '-- Hake (merluccius spp., urophycis spp.)'],
            ['kodeHS' => '03047500', 'uraianBarang' => '-- Alaska pollock (Theragra chalcogramma)'],
            ['kodeHS' => '03047900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03048100', 'uraianBarang' => '-- Salmon pasifik (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou dan Oncorhynchus rhodurus), Salmon Atlantik (Salmo salar) dan salmon danube (hucho hocho)'],
            ['kodeHS' => '03048200', 'uraianBarang' => '-- Trout (salmo trutta, oncorhynchus mykiss, oncorhynchus clarki, oncorhynchus aguabonita, oncorhynchus gilae, oncorhynchus apache dan oncorhynchus chrysogaster)'],
            ['kodeHS' => '03048300', 'uraianBarang' => '-- Ikan pipih (Pleuronectidae, bothidae, cynoglossidae, soleidae, scophthalmidae dan citharidae)'],
            ['kodeHS' => '03048400', 'uraianBarang' => '-- Todak (xiphias gladius)'],
            ['kodeHS' => '03048500', 'uraianBarang' => '-- Toothfish (Dissostichus spp.)'],
            ['kodeHS' => '03048600', 'uraianBarang' => '-- Herring (Clupen harengus, clupea pallasii)'],
            ['kodeHS' => '03048700', 'uraianBarang' => '- Tuna (dari genus Thunnus), cakalang (stripe-bellied bonito) (katsuwonus pelamis)'],
            ['kodeHS' => '03048800', 'uraianBarang' => '-- Dogfish, hiu lainnya, pari dan skates (Rajidae)'],
            ['kodeHS' => '03048910', 'uraianBarang' => '--- Mahi-mahi (Coryphaena hippurus)'],
            ['kodeHS' => '03048990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03049100', 'uraianBarang' => '-- Todak (xiphias gladius)'],
            ['kodeHS' => '03049200', 'uraianBarang' => '-- Toothfish (Dissostichus spp.)'],
            ['kodeHS' => '03049300', 'uraianBarang' => '-- Tilapia (Oreochromis spp.), catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.), ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.), sidat (anguilla spp.), nile perch (lates niloticus) dan gabus (channa spp.)'],
            ['kodeHS' => '03049400', 'uraianBarang' => '-- Alaska pollock (Theragra chalcogramma)'],
            ['kodeHS' => '03049500', 'uraianBarang' => '-- Ikan dari keluarga Bregmacerotidae, Euclichthyidae, Gadidae, Macrouridae, Melanonidae, Merlucciidae, Moridae dan Muraenolepididae, selain dari Alaska Pollock (Theragra chalcogramma)'],
            ['kodeHS' => '03049600', 'uraianBarang' => '-- Dogfish dan hiu lainnya'],
            ['kodeHS' => '03049700', 'uraianBarang' => '-- Pari dan skates (rajidae)'],
            ['kodeHS' => '03049910', 'uraianBarang' => '--- Surimi (daging ikan cincang)'],
            ['kodeHS' => '03049990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03052010', 'uraianBarang' => '-- Dari ikan air tawar, dikeringkan, diasapi, diasinkan atau dalam air garam'],
            ['kodeHS' => '03052090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03053100', 'uraianBarang' => '-- Tilapia (Oreochromis spp.), catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.), ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.), sidat (anguilla spp.), nile perch (lates niloticus) dan gabus (channa spp.)'],
            ['kodeHS' => '03053200', 'uraianBarang' => '-- Ikan dari keluarga Bregmacerotidae, Euclichthyidae, Gadidae, Macrouridae, Melanonidae, Merlucciidae, Moridae dan Muraenolepididae'],
            ['kodeHS' => '03053910', 'uraianBarang' => '--- Ikan garnish air tawar (xenentodon cancila), ikan kambing bersirip kuning (upeneus vittatus) dan ikan long-rakered trevally (ulua mentalis)'],
            ['kodeHS' => '03053920', 'uraianBarang' => '--- Layur (lepturacanthus savala), belanger\'s croakers (johnius belangerii), reeve\'s croakers (chrysochir aureus) dan bigeye croakers (pennahia anea)'],
            ['kodeHS' => '03053991', 'uraianBarang' => '---- Ikan air tawar'],
            ['kodeHS' => '03053992', 'uraianBarang' => '---- Ikan air laut'],
            ['kodeHS' => '03053999', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03054100', 'uraianBarang' => '-- Salmon pasifik (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou dan Oncorhynchus rhodurus), Salmon Atlantik (Salmo salar) dan salmon danube (hucho hocho)'],
            ['kodeHS' => '03054200', 'uraianBarang' => '-- Herring (Clupen harengus, clupea pallasii)'],
            ['kodeHS' => '03054300', 'uraianBarang' => '-- Trout (salmo trutta, oncorhynchus mykiss, oncorhynchus clarki, oncorhynchus aguabonita, oncorhynchus gilae, oncorhynchus apache dan oncorhynchus chrysogaster)'],
            ['kodeHS' => '03054400', 'uraianBarang' => '-- Tilapia (Oreochromis spp.), catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.), ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.), sidat (anguilla spp.), nile perch (lates niloticus) dan gabus (channa spp.)'],
            ['kodeHS' => '03054910', 'uraianBarang' => '--- Cakalang (stripe-bellied bonito) (katsuwonus pelamis)'],
            ['kodeHS' => '03054990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03055100', 'uraianBarang' => '-- Cod (gadus morhua, gadus ogac, gadus macrocephalus)'],
            ['kodeHS' => '03055200', 'uraianBarang' => '-- Tilapia (Oreochromis spp.), catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.), ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.), sidat (anguilla spp.), nile perch (lates niloticus) dan gabus (channa spp.)'],
            ['kodeHS' => '03055300', 'uraianBarang' => '-- Ikan dari keluarga Bregmacerotidae, Euclichthyidae, Gadidae, Macrouridae, Melanonidae, Merlucciidae, Moridae dan Muraenolepididae, selain Cod (gadus morhua, gadus ogac, gadus macrocephalus)'],
            ['kodeHS' => '03055400', 'uraianBarang' => '-- Herring (Clupen harengus, clupea pallasii), teri (engraulis spp.), sarden (sardina pilchardus, sardinops spp.), sardinella (sardinella spp.), brisling atau sparts (sprattus sprattus), makarel (scomber scombrus, scomber australasicus, scomber japanicus), makarel indian (rastrelliger spp.), scerfishes (scomberomorus spp.), makarel jack dan makarel kuda (trachurus spp.), jacks, crevalles (caranx spp.), cobia (rachycentron canadum), bawal putih (pampus spp.), pacific saury (cololabis saira), scads (decapterus spp.), capelin (mallotus villosus), todak (xiphias gladius), kawakawa (euthymnus affinis), bonitos (sarda spp.), marlin, ikan layar, spcarfish (istiophoridae)'],
            ['kodeHS' => '03055921', 'uraianBarang' => '---- Teri (stolephorus spp., Coilia spp., Setipinna spp., Lycothrissa spp., Thryssa spp., Encrasicholina spp.)'],
            ['kodeHS' => '03055929', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03055990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03056100', 'uraianBarang' => '-- Herring (Clupen harengus, clupea pallasii)'],
            ['kodeHS' => '03056200', 'uraianBarang' => '-- Cod (gadus morhua, gadus ogac, gadus macrocephalus)'],
            ['kodeHS' => '03056300', 'uraianBarang' => '-- Teri (engraulis spp.)'],
            ['kodeHS' => '03056400', 'uraianBarang' => '-- Tilapia (Oreochromis spp.), catfish (pangasius spp., silurus spp., clarias spp., ictalurus spp.), ikan mas (cyprinus spp., carassius spp., ctenopharyngodon idellus, hypophthalmichthys spp., cirrhinus spp., mylopharyngodon piceus, catla catla, labeo spp., osteochilus hasselti, leptobarbus hoeveni, megalobrama spp.), sidat (anguilla spp.), nile perch (lates niloticus) dan gabus (channa spp.)'],
            ['kodeHS' => '03056910', 'uraianBarang' => '--- Ikan laut :'],
            ['kodeHS' => '03056990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03057110', 'uraianBarang' => '--- Dikeringkan atau diasapi'],
            ['kodeHS' => '03057190', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03057211', 'uraianBarang' => '---- Cod'],
            ['kodeHS' => '03057219', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03057291', 'uraianBarang' => '---- Cod'],
            ['kodeHS' => '03057299', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03057910', 'uraianBarang' => '--- Cod'],
            ['kodeHS' => '03057990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03061110', 'uraianBarang' => '--- Diasapi'],
            ['kodeHS' => '03061190', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03061210', 'uraianBarang' => '--- Diasapi'],
            ['kodeHS' => '03061290', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03061411', 'uraianBarang' => '--- Kepiting bercangkang lunak'],
            ['kodeHS' => '03061419', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03061491', 'uraianBarang' => '---- Swimming crab (Kepiting dari keluarga portunidae)'],
            ['kodeHS' => '03061492', 'uraianBarang' => '---- King crab (Kepiting dari keluarga lithodidae)'],
            ['kodeHS' => '03061493', 'uraianBarang' => '---- Snow crab (Kepiting dari keluarga oregoniidae)'],
            ['kodeHS' => '03061499', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03061500', 'uraianBarang' => '-- Lobster norwegia (nephrops norvegicus)'],
            ['kodeHS' => '03061600', 'uraianBarang' => '-- Udang dan udang besar air dingin (pandalus spp., crangon crangon)'],
            ['kodeHS' => '03061711', 'uraianBarang' => '---- Tanpa kepala'],
            ['kodeHS' => '03061719', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03061721', 'uraianBarang' => '---- Tanpa kepala, dengan ekor'],
            ['kodeHS' => '03061722', 'uraianBarang' => '---- Tanpa kepala, tanpa ekor'],
            ['kodeHS' => '03061729', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03061730', 'uraianBarang' => '--- Udang galah (macrobrachium rosenbergii)'],
            ['kodeHS' => '03061790', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '03061900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '03063110', 'uraianBarang' => '--- Bibit'],
            ['kodeHS' => '03063120', 'uraianBarang' => '--- Lain-lain, hidup'],
            ['kodeHS' => '03063130', 'uraianBarang' => '--- Segar atau dingin'],
            ['kodeHS' => '03063210', 'uraianBarang' => '--- Bibit'],
            ['kodeHS' => '03063220', 'uraianBarang' => '--- Lain-lain, hidup'],
            ['kodeHS' => '03063230', 'uraianBarang' => '--- Segar atau dingin'],
            ['kodeHS' => '03063311', 'uraianBarang' => '---- Hidup'],
            ['kodeHS' => '03063312', 'uraianBarang' => '---- Segar atau dingin'],
            ['kodeHS' => '03063391', 'uraianBarang' => '---- Hidup'],
            ['kodeHS' => '03063392', 'uraianBarang' => '---- Segar atau dingin'],
            ['kodeHS' => '03063400', 'uraianBarang' => '-- Lobster norwegia (nephrops norvegicus)'],
            ['kodeHS' => '03063510', 'uraianBarang' => '--- Bibit'],
            ['kodeHS' => '03063520', 'uraianBarang' => '--- Lain-lain, hidup'],
            ['kodeHS' => '03063530', 'uraianBarang' => '--- Segar atau dingin'],
            ['kodeHS' => '03063611', 'uraianBarang' => '---- Udang windu (penaeus monodon)'],
            ['kodeHS' => '03063612', 'uraianBarang' => '---- Udang vanamei (Liptopenaeus vannamei)'],
            ['kodeHS' => '03063613', 'uraianBarang' => '---- Udang galah (macrobrachium rosenbergii)'],
            ['kodeHS' => '03063619', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03063621', 'uraianBarang' => '---- Udang windu (penaeus monodon)'],
            ['kodeHS' => '03063622', 'uraianBarang' => '---- Udang vanamei (Liptopenaeus vannamei)'],
            ['kodeHS' => '03063623', 'uraianBarang' => '---- Udang galah (macrobrachium rosenbergii)'],
            ['kodeHS' => '03063629', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03063631', 'uraianBarang' => '---- Udang windu (penaeus monodon)'],
            ['kodeHS' => '03063632', 'uraianBarang' => '---- Udang vanamei (Liptopenaeus vannamei)'],
            ['kodeHS' => '03063633', 'uraianBarang' => '---- Udang galah (macrobrachium rosenbergii)'],
            ['kodeHS' => '03063639', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03063920', 'uraianBarang' => '--- Segar atau dingin'],
            ['kodeHS' => '03069121', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069129', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069131', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069139', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069221', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069229', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069231', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069239', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069321', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069329', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069331', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069339', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069421', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '03069429', 'uraianBarang' => '---- Lain-lain'],
            ['kodeHS' => '03069431', 'uraianBarang' => '---- Diasapi'],
            ['kodeHS' => '04011010', 'uraianBarang' => '-- Dalam bentuk cairan'],
            ['kodeHS' => '04011090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '04012010', 'uraianBarang' => '-- Dalam bentuk cairan'],
            ['kodeHS' => '04012090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '04014020', 'uraianBarang' => '-- Susu dalam bentuk beku'],
            ['kodeHS' => '04014090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '04015010', 'uraianBarang' => '-- Dalam bentuk cairan'],
            ['kodeHS' => '04015090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '04021041', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 20kg atau lebih'],
            ['kodeHS' => '04021042', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 2kg atau kurang'],
            ['kodeHS' => '04021049', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '04021091', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 20kg atau lebih'],
            ['kodeHS' => '04021092', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 2kg atau kurang'],
            ['kodeHS' => '04021099', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '04022120', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 20kg atau lebih'],
            ['kodeHS' => '04022130', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 2kg atau kurang'],
            ['kodeHS' => '04022190', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '04022920', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 20kg atau lebih'],
            ['kodeHS' => '04022930', 'uraianBarang' => '--- Dalam kemasan dengan berat bersih 2kg atau kurang'],
            ['kodeHS' => '04022990', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '04029100', 'uraianBarang' => '--- Tidak mengandung tambahan gula atau bahan pemanis lainnya'],
            ['kodeHS' => '04029900', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '05010000', 'uraianBarang' => 'Rambut manusia, tidak dikerjakan, dicuci atau digosok maupun tidak; sisa rambut manusia'],
            ['kodeHS' => '05021000', 'uraianBarang' => '- Bulu dan bulu kasar serta sisanya dari babi, babi ternak atau babi hutan'],
            ['kodeHS' => '05029000', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '05051010', 'uraianBarang' => '-- Bulu bebek '],
            ['kodeHS' => '05051090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '05059010', 'uraianBarang' => '-- Bulu bebek '],
            ['kodeHS' => '05059090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '05061000', 'uraianBarang' => '- Osein dan tulang dikerjakan dengan asam'],
            ['kodeHS' => '05069000', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '05071000', 'uraianBarang' => '- gading;bubuk gading dan sisanya'],
            ['kodeHS' => '05079020', 'uraianBarang' => '-- Tempurung kura-kura'],
            ['kodeHS' => '05079090', 'uraianBarang' => '-- Lain-lain'],
            ['kodeHS' => '05080020', 'uraianBarang' => '- Cangkang moluska, krustasea atau enchinodermata'],
            ['kodeHS' => '05080090', 'uraianBarang' => '- Lain-lain'],
            ['kodeHS' => '05111000', 'uraianBarang' => '- Mani dari binatang jenis lembu'],
            ['kodeHS' => '05119110', 'uraianBarang' => '--- Telur dan sperma'],
            ['kodeHS' => '05119120', 'uraianBarang' => '--- Telur artemia'],
            ['kodeHS' => '05119130', 'uraianBarang' => '--- Kulit ikan'],
            ['kodeHS' => '05119190', 'uraianBarang' => '--- Lain-lain'],
            ['kodeHS' => '05119910', 'uraianBarang' => '--- Mani dari binatang peliharaan'],
            ['kodeHS' => '05119920', 'uraianBarang' => '--- Telur ulat sutera'],
            ['kodeHS' => '05119930', 'uraianBarang' => '--- Sponge alami'],
            ['kodeHS' => '05119990', 'uraianBarang' => '--- Lain-lain'],
        ];


        DB::table('hs')->insert($hs);
        }
    }
