<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenisDokumenSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $array = [
            ['kodeJenisDokumen' => '10', 'namaDokumen' => 'RKSP'],
            ['kodeJenisDokumen' => '11', 'namaDokumen' => 'MANIFES'],
            ['kodeJenisDokumen' => '16', 'namaDokumen' => 'BC 1.6 - PEMBERITAHUAN PABEAN PENGELUARAN BARANG DARI KAWASAN PABEAN UNTUK DITIMBUN DI PUSAT LOGISTIK BERIKAT'],
            ['kodeJenisDokumen' => '20', 'namaDokumen' => 'BC 2.0 - PEMBERITAHUAN IMPOR BARANG'],
            ['kodeJenisDokumen' => '21', 'namaDokumen' => 'PIBK/IMPOR KHUSUS'],
            ['kodeJenisDokumen' => '23', 'namaDokumen' => 'BC 2.3 - PEMBERITAHUAN IMPOR BARANG UNTUK DITIMBUN DI TEMPAT PENIMBUNAN BERIKAT'],
            ['kodeJenisDokumen' => '25', 'namaDokumen' => 'BC 2.5 - PEMBERITAHUAN IMPOR BARANG DARI TEMPAT PENIMBUNAN BERIKAT'],
            ['kodeJenisDokumen' => '27', 'namaDokumen' => 'BC 2.7 - PEMBERITAHUAN PENGELUARAN UNTUK DIANGKUT DARI TEMPAT PENIMBUNAN BERIKAT KE TEMPAT PENIMBUNAN BERIKAT LAINNYA'],
            ['kodeJenisDokumen' => '28', 'namaDokumen' => 'BC 2.8 - PEMBERITAHUAN IMPOR BARANG DARI PUSAT LOGISTIK BERIKAT'],
            ['kodeJenisDokumen' => '30', 'namaDokumen' => 'BC 3.0 - PEMBERITAHUAN EKSPOR NARAMG'],
            ['kodeJenisDokumen' => '33', 'namaDokumen' => 'BC 3.3 - PEMBERITAHUAN EKSPOR BARANG MELALUI/DARI PUSAT LOGISTIK BERIKAT'],
            ['kodeJenisDokumen' => '40', 'namaDokumen' => 'BC 4.0 - PEMBERITAHUAN PEMASUKAN BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN KE TEMPAT PENIMBUNAN BERIKAT'],
            ['kodeJenisDokumen' => '41', 'namaDokumen' => 'BC 4.1 - PEMBERITAHUAN PENGELUARAN KEMBALI BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN DARI TEMPAT PENIMBUNAN BERIKAT'],
            ['kodeJenisDokumen' => '50', 'namaDokumen' => 'KITE'],
            ['kodeJenisDokumen' => '51', 'namaDokumen' => 'FTZ 01'],
            ['kodeJenisDokumen' => '52', 'namaDokumen' => 'FTZ 02'],
            ['kodeJenisDokumen' => '53', 'namaDokumen' => 'FTZ 03'],
            ['kodeJenisDokumen' => '65', 'namaDokumen' => 'BC 1.1 KONSOLIDASI PJT'],
            ['kodeJenisDokumen' => '111', 'namaDokumen' => 'Bank Devisa Hasil Ekspor (DHE]'],
            ['kodeJenisDokumen' => '161', 'namaDokumen' => 'PPB - PEMBERITAHUAN PERPINDAHAN BARANG ANTAR TEMPAT PENIMBUNAN DALAM SATU PUSAT LOGISTIK BERIKAT'],
            ['kodeJenisDokumen' => '217', 'namaDokumen' => 'PACKING LIST'],
            ['kodeJenisDokumen' => '246', 'namaDokumen' => 'L/C'],
            ['kodeJenisDokumen' => '261', 'namaDokumen' => 'BC 2.6.1 - PEMBERITAHUAN PENGELUARAN BARANG DARI TEMPAT PENIMBUNAN BERIKAT DENGAN JAMINAN'],
            ['kodeJenisDokumen' => '262', 'namaDokumen' => '262 BC 2.6.2 - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG YANG DI KELUARKAN DARI TEMPAT PENIMBUNAN BERIKAT DENGAN JAMINAN'],
            ['kodeJenisDokumen' => '281', 'namaDokumen' => 'PPK - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG ASAL PLB DARI LOKASI PENERIMA FASILITAS DI TEMPAT LAIN DALAM DAERAH PABEAN KE PLB'],
            ['kodeJenisDokumen' => '282', 'namaDokumen' => 'DOKAP PLB - PEMBERITAHUAN PENGELUARAN DENGAN DOKUMEN PELENGKAP'],
            ['kodeJenisDokumen' => '315', 'namaDokumen' => 'KONTRAK'],
            ['kodeJenisDokumen' => '331', 'namaDokumen' => 'P3BET - PEMBERITAHUAN PENGGABUNGAN DAN PEMECAHAN BARANG EKSPOR DAN TRANSHIPMENT'],
            ['kodeJenisDokumen' => '343', 'namaDokumen' => 'SHIPING ORDER'],
            ['kodeJenisDokumen' => '380', 'namaDokumen' => 'INVOICE'],
            ['kodeJenisDokumen' => '383', 'namaDokumen' => 'SSTB'],
            ['kodeJenisDokumen' => '388', 'namaDokumen' => 'FAKTUR PAJAK'],
            ['kodeJenisDokumen' => '410', 'namaDokumen' => 'SURAT SANGGUP BAYAR / SSB'],
            ['kodeJenisDokumen' => '430', 'namaDokumen' => 'BANK GARANSI'],
            ['kodeJenisDokumen' => '440', 'namaDokumen' => 'SURAT TANDA BUKTI SETOR / STBS'],
            ['kodeJenisDokumen' => '454', 'namaDokumen' => 'SSPCP / SSBC'],
            ['kodeJenisDokumen' => '455', 'namaDokumen' => 'SURAT SETORAN PAJAK (SSP]'],
            ['kodeJenisDokumen' => '456', 'namaDokumen' => 'SKB'],
            ['kodeJenisDokumen' => '457', 'namaDokumen' => 'Surat Keterangan Bebas (SKB] PPh'],
            ['kodeJenisDokumen' => '458', 'namaDokumen' => 'SURAT KETERANGAN TIDAK DIPUNGUT (SKTD] PPN'],
            ['kodeJenisDokumen' => '500', 'namaDokumen' => 'MOU PDE (Eksportir]'],
            ['kodeJenisDokumen' => '511', 'namaDokumen' => 'FTZ-01 PEMASUKAN DARI LUAR DAERAH PABEAN (IMPOR]'],
            ['kodeJenisDokumen' => '512', 'namaDokumen' => 'FTZ-01 PENGELUARAN KE LUAR DAERAH PABEAN (EKSPOR]'],
            ['kodeJenisDokumen' => '513', 'namaDokumen' => 'FTZ-01 PENGELUARAN KE TEMPAT LAIN DALAM DAERAH PABEAN'],
            ['kodeJenisDokumen' => '521', 'namaDokumen' => 'FTZ-02 PEMASUKAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT'],
            ['kodeJenisDokumen' => '522', 'namaDokumen' => 'FTZ-02 PENGELUARAN ANTARfree trade zone dan kawasan berikat'],
            ['kodeJenisDokumen' => '531', 'namaDokumen' => 'FTZ-03 PEMASUKAN DARI TEMPAT LAIN DALAM DAERAH PABEAN'],
            ['kodeJenisDokumen' => '640', 'namaDokumen' => 'DELIVERY ORDER'],
            ['kodeJenisDokumen' => '666', 'namaDokumen' => 'Pengecualian Dengan Surat Keputusan'],
            ['kodeJenisDokumen' => '704', 'namaDokumen' => 'MASTER B/L'],
            ['kodeJenisDokumen' => '705', 'namaDokumen' => 'B/L'],
            ['kodeJenisDokumen' => '740', 'namaDokumen' => 'AWB'],
            ['kodeJenisDokumen' => '741', 'namaDokumen' => 'MASTER AWB'],
            ['kodeJenisDokumen' => '800', 'namaDokumen' => 'SERTIFIKAT ALAT PERANGKAT TELEKOM/POSTEL'],
            ['kodeJenisDokumen' => '803', 'namaDokumen' => 'SATS LN / DEPHUT'],
            ['kodeJenisDokumen' => '805', 'namaDokumen' => 'REGISTRASI B3 / KLH'],
            ['kodeJenisDokumen' => '808', 'namaDokumen' => 'IJIN IMPOR / POLRI'],
            ['kodeJenisDokumen' => '809', 'namaDokumen' => 'SIE'],
            ['kodeJenisDokumen' => '810', 'namaDokumen' => 'SM/SPM'],
            ['kodeJenisDokumen' => '811', 'namaDokumen' => 'Sertifikat Legalitas Kayu (Dok.V-Legal]'],
            ['kodeJenisDokumen' => '812', 'namaDokumen' => 'Dok. Impor (PIB]'],
            ['kodeJenisDokumen' => '813', 'namaDokumen' => 'DOK. CUKAI (CK]'],
            ['kodeJenisDokumen' => '814', 'namaDokumen' => 'SKEP IJIN EKSPOR BERKALA'],
            ['kodeJenisDokumen' => '815', 'namaDokumen' => 'SKEP IJIN TATA NIAGA EKSPOR'],
            ['kodeJenisDokumen' => '816', 'namaDokumen' => 'DOK. EKSPOR (PEB]'],
            ['kodeJenisDokumen' => '817', 'namaDokumen' => 'Eksportir Terdaftar (ET] Depdag'],
            ['kodeJenisDokumen' => '818', 'namaDokumen' => 'Endorsement BRIK'],
            ['kodeJenisDokumen' => '819', 'namaDokumen' => 'Sertifikat Intan Kasar'],
            ['kodeJenisDokumen' => '820', 'namaDokumen' => 'Surat Persetujuan Ekspor (SPE]'],
            ['kodeJenisDokumen' => '821', 'namaDokumen' => 'Surat Tanda Registrasi UPPB'],
            ['kodeJenisDokumen' => '822', 'namaDokumen' => 'Srt Tanda Pendaftaran Pedagang Bokor SIR'],
            ['kodeJenisDokumen' => '834', 'namaDokumen' => 'SNI GULA KRISTAL MENTAH / DEPTAN'],
            ['kodeJenisDokumen' => '835', 'namaDokumen' => 'IZIN DAN/ATAU PENDAFT PESTISIDA / DEPTAN'],
            ['kodeJenisDokumen' => '836', 'namaDokumen' => 'IZIN IMPOR / DEPTAN'],
            ['kodeJenisDokumen' => '842', 'namaDokumen' => 'SNI/SPB/DEPDAG'],
            ['kodeJenisDokumen' => '843', 'namaDokumen' => 'NOMOR PELUMAS TERDAFTAR / ESDM'],
            ['kodeJenisDokumen' => '844', 'namaDokumen' => 'IZIN USAHA NIAGA/IU NIAGA TERBATAS/ESDM'],
            ['kodeJenisDokumen' => '845', 'namaDokumen' => 'REKOMENDASI IMPOR PELUMAS'],
            ['kodeJenisDokumen' => '846', 'namaDokumen' => 'SKEM'],
            ["kodeJenisDokumen" => "851", "namaDokumen" => "SURAT IJIN KARANTINA TANAMAN"],
            ["kodeJenisDokumen" => "853", "namaDokumen" => "SURAT IJIN KARANTINA HEWAN / IKAN"],
            ["kodeJenisDokumen" => "854", "namaDokumen" => "SURAT PERSETUJUAN MUAT BPOM"],
            ["kodeJenisDokumen" => "856", "namaDokumen" => "LAP. PEMERIKSAAN SURVEYOR (LPS-E)"],
            ["kodeJenisDokumen" => "857", "namaDokumen" => "FUMIGATION CERTIFICATE"],
            ["kodeJenisDokumen" => "858", "namaDokumen" => "CITES CERTIFICATE"],
            ["kodeJenisDokumen" => "860", "namaDokumen" => "Electronic Certificate Of Origin (E-CO)"],
            ["kodeJenisDokumen" => "861", "namaDokumen" => "CERTIFICATE OF ORIGIN (CO)"],
            ["kodeJenisDokumen" => "862", "namaDokumen" => "SKEP USDFS"],
            ["kodeJenisDokumen" => "871", "namaDokumen" => "Nomor Pendaftaran Alat Kesehatan/Depkes"],
            ["kodeJenisDokumen" => "872", "namaDokumen" => "LAPORAN SURVEYOR DEPKES"],
            ["kodeJenisDokumen" => "873", "namaDokumen" => "IP (NARKTK, PREKURSOR & PSIKOTR)/DEPKES"],
            ["kodeJenisDokumen" => "874", "namaDokumen" => "IT (PREKURSOR & PSIKOTR)/DEPKES"],
            ["kodeJenisDokumen" => "875", "namaDokumen" => "SPI (NARKTK, PREKURSOR & PSIKOTR)/DEPKES"],
            ["kodeJenisDokumen" => "876", "namaDokumen" => "Ijin Pembawaan UKA"],
            ["kodeJenisDokumen" => "877", "namaDokumen" => "Ijin Persetujuan Pembawaan UKA"],
            ["kodeJenisDokumen" => "878", "namaDokumen" => "Ijin Pelaporan Pembawaan UKA"],
            ["kodeJenisDokumen" => "888", "namaDokumen" => "PENGECUALIAN PERIJINAN"],
            ["kodeJenisDokumen" => "902", "namaDokumen" => "IJIN BAPETEN"],
            ["kodeJenisDokumen" => "911", "namaDokumen" => "SURAT KEPUTUSAN"],
            ["kodeJenisDokumen" => "912", "namaDokumen" => "SKEP FASILITAS BKPM"],
            ["kodeJenisDokumen" => "913", "namaDokumen" => "SKEP FASILITAS PERTAMBANGAN"],
            ["kodeJenisDokumen" => "914", "namaDokumen" => "KITE IKM"],
            ["kodeJenisDokumen" => "915", "namaDokumen" => "Skep Fasilitas Impor Sementara"],
            ["kodeJenisDokumen" => "917", "namaDokumen" => "BPBC / BPPAI"],
            ["kodeJenisDokumen" => "918", "namaDokumen" => "SK LABEL BAHASA INDONESIA"],
            ["kodeJenisDokumen" => "919", "namaDokumen" => "SK Bermotor"],
            ["kodeJenisDokumen" => "920", "namaDokumen" => "SKEP TPB"],
            ["kodeJenisDokumen" => "936", "namaDokumen" => "KH-9a/Izin Impor Karantina Hewan"],
            ["kodeJenisDokumen" => "937", "namaDokumen" => "KH-14/Izin Impor Karantina Hewan"],
            ["kodeJenisDokumen" => "938", "namaDokumen" => "KH-17/Izin Impor Karantina Hewan"],
            ["kodeJenisDokumen" => "939", "namaDokumen" => "KT-5/Izin Impor Karantina Pertanian"],
            ["kodeJenisDokumen" => "940", "namaDokumen" => "KT-9/Izin Impor Karantina Pertanian"],
            ["kodeJenisDokumen" => "941", "namaDokumen" => "KT-13/Izin Impor Karantina Pertanian"],
            ["kodeJenisDokumen" => "942", "namaDokumen" => "IZIN IMPOR KARANTINA TUMBUHAN"],
            ["kodeJenisDokumen" => "943", "namaDokumen" => "KH-5 / IZIN IMPOR KARANTINA HEWAN"],
            ["kodeJenisDokumen" => "944", "namaDokumen" => "KH-7 / IZIN IMPOR KARANTINA HEWAN"],
            ["kodeJenisDokumen" => "945", "namaDokumen" => "KH-12 / IZIN IMPOR KARANTINA HEWAN"],
            ["kodeJenisDokumen" => "946", "namaDokumen" => "KID-3 / IZIN IMPOR KARANTINA IKAN"],
            ["kodeJenisDokumen" => "947", "namaDokumen" => "KID-15 / IZIN IMPOR KARANTINA IKAN"],
            ["kodeJenisDokumen" => "948", "namaDokumen" => "NPIK"],
            ["kodeJenisDokumen" => "949", "namaDokumen" => "PENGAKUAN SBG IMPORTIR PRODUSEN"],
            ["kodeJenisDokumen" => "950", "namaDokumen" => "KID-4/IZIN KARANTINA IKAN"],
            ["kodeJenisDokumen" => "951", "namaDokumen" => "HC (HEALTH CERTIFICATE)"],
            ["kodeJenisDokumen" => "956", "namaDokumen" => "PENGAKUAN SBG IMPORTIR TERDAFTAR"],
            ["kodeJenisDokumen" => "957", "namaDokumen" => "SNI/SPB/DEPDAG"],
            ["kodeJenisDokumen" => "958", "namaDokumen" => "LAPORAN SURVEYOR / DEPDAG"],
            ["kodeJenisDokumen" => "959", "namaDokumen" => "SURAT PERSETUJUAN IMPOR DEP.DAG"],
            ["kodeJenisDokumen" => "960", "namaDokumen" => "3D/PC dan/atau PFP"],
            ["kodeJenisDokumen" => "961", "namaDokumen" => "Hasil Lab"],
            ["kodeJenisDokumen" => "993", "namaDokumen" => "SURAT IJIN MENTERI PERTANIAN"],
            ["kodeJenisDokumen" => "994", "namaDokumen" => "BUKTI PENERIMAAN JAMINAN (BPJ)"],
            ["kodeJenisDokumen" => "995", "namaDokumen" => "STBS / SSP-E (PAJAK EKSPOR)"],
            ["kodeJenisDokumen" => "996", "namaDokumen" => "SRT SANGGUP BAYAR (SSB)"],
            ["kodeJenisDokumen" => "997", "namaDokumen" => "COSTOMS BOND / STTJ"],
            ["kodeJenisDokumen" => "998", "namaDokumen" => "SKEP FASILITAS KEMUDAHAN EKSPOR"],
            ["kodeJenisDokumen" => "999", "namaDokumen" => "LAINNYA"],
            ["kodeJenisDokumen" => "3001", "namaDokumen" => "Izin Prinsip Pendirian Kawasan Berikat Sebelum Fisik Bangunan Berdiri"],
            ["kodeJenisDokumen" => "3002", "namaDokumen" => "Keputusan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat"],
            ["kodeJenisDokumen" => "3003", "namaDokumen" => "Persetujuan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat Sekaligus Izin Pengusaha Kawasan Berikat"],
            ["kodeJenisDokumen" => "3004", "namaDokumen" => "Izin PDKB"],
            ["kodeJenisDokumen" => "3005", "namaDokumen" => "Perpanjangan Penetapan Tempat Sebagai Kawasan Berikat Dan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB Sebelum Jangka Waktu Izin Tersebut Berakhir"],
            ["kodeJenisDokumen" => "3006", "namaDokumen" => "Perubahan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB (Terdapat Perubahan Nama Perusahaan Yang Bukan Dikarenakan Merger Atau Diakuisisi, Jenis Hasil Produksi, Atau Luas Kawasan Berikat)"],
            ["kodeJenisDokumen" => "3007", "namaDokumen" => "Perubahan Keputusan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB"],
            ["kodeJenisDokumen" => "3008", "namaDokumen" => "Pemberian Izin Penambahan Pintu Khusus Pemasukan Dan Pengeluaran Barang Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3009", "namaDokumen" => "Pemberian Izin Penambahan Pintu Khusus Orang Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3010", "namaDokumen" => "Persetujuan Pemasukan Barang Dari Kawasan Bebas Ke Kawasan Berikat"],
            ["kodeJenisDokumen" => "3011", "namaDokumen" => "Persetujuan Pemasukan Barang Modal Dari Luar Daerah Pabean"],
            ["kodeJenisDokumen" => "3012", "namaDokumen" => "Persetujuan Pemasukan Barang Modal Dari Kawasan Berikat Lain"],
            ["kodeJenisDokumen" => "3013", "namaDokumen" => "Persetujuan Pemasukan Barang Jadi Asal Luar Daerah Pabean Untuk Digabungkan Dengan Hasil Produksi Utama Kawasan Berikat"],
            ["kodeJenisDokumen" => "3014", "namaDokumen" => "Persetujuan Pemasukan Peralatan Perkantoran Asal Luar Daerah Pabean Ke Kawasan Berikat"],
            ["kodeJenisDokumen" => "3015", "namaDokumen" => "Persetujuan Pemasukan Barang Contoh Asal Luar Daerah Pabean"],
            ["kodeJenisDokumen" => "3016", "namaDokumen" => "Persetujuan Pembebasan Bea Masuk Untuk Barang Contoh Yang Akan Dikeluarkan Ke Tempat Lain Dalam Daerah Pabean"],
            ["kodeJenisDokumen" => "3017", "namaDokumen" => "Persetujuan Mengeluarkan Hasil Produksi Kawasan Berikat Ke Tempat Penyelenggaraan Pameran Berikat (TPPB)"],
            ["kodeJenisDokumen" => "3018", "namaDokumen" => "Persetujuan Untuk Mengeluarkan Bahan Baku Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Yang Sama Sekali Tidak Diproses Ke Gudang Berikat Asal Barang"],
            ["kodeJenisDokumen" => "3019", "namaDokumen" => "Persetujuan Untuk Mengeluarkan Barang Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Asal Tlddp Ke TLDDP"],
            ["kodeJenisDokumen" => "3020", "namaDokumen" => "Persetujuan Pengeluaran Bahan Baku/Sisa Bahan Baku Asal Impor Untuk Direekspor"],
            ["kodeJenisDokumen" => "3021", "namaDokumen" => "Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Kawasan Berikat Lain"],
            ["kodeJenisDokumen" => "3022", "namaDokumen" => "Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Perusahaan Industri Di TLDDP"],
            ["kodeJenisDokumen" => "3023", "namaDokumen" => "Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu Manajemen"],
            ["kodeJenisDokumen" => "3024", "namaDokumen" => "Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu PKB"],
            ["kodeJenisDokumen" => "3025", "namaDokumen" => "Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lainnya"],
            ["kodeJenisDokumen" => "3026", "namaDokumen" => "Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Dibayar BM-nya Untuk Direekspor"],
            ["kodeJenisDokumen" => "3027", "namaDokumen" => "Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM-nya Ke Kawasan Berikat Lain Setelah Jangka Waktu 2 (Dua) Tahun Sejak Diimpor Dan Telahdipergunakan Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3028", "namaDokumen" => "Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM Ke Tempat Lain Dalam Daerah Pabean Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3029", "namaDokumen" => "Keputusan Pembebasan BM Atas Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3030", "namaDokumen" => "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Lunas BM Untuk Direekspor"],
            ["kodeJenisDokumen" => "3031", "namaDokumen" => "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke Kawasan Berikat Lain Setelah Dipergunakan Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3032", "namaDokumen" => "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke TLDDP Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat Yang Bersangkutan"],
            ["kodeJenisDokumen" => "3033", "namaDokumen" => "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat"],
            ["kodeJenisDokumen" => "3034", "namaDokumen" => "Persetujuan Untuk Memindahtangankan Barang Modal Dan/Atau Peralatan Perkantoran Yang Telah Dilunasi BM Dan PDRI Pada Saat Pemasukan Ke Kawasan Berikat"],
            ["kodeJenisDokumen" => "3035", "namaDokumen" => "Persetujuan Untuk Memindahtangankan Barang Modal Asal Tempat Lain Dalam Daerah Pabean"],
            ["kodeJenisDokumen" => "3036", "namaDokumen" => "Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke Luar Daerah Pabean"],
            ["kodeJenisDokumen" => "3037", "namaDokumen" => "Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke TLDDP"],
            ["kodeJenisDokumen" => "3038", "namaDokumen" => "Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke KB Lain"],
            ["kodeJenisDokumen" => "3039", "namaDokumen" => "Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke TLDDP"],
            ["kodeJenisDokumen" => "3040", "namaDokumen" => "Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke KB Lain"],
            ["kodeJenisDokumen" => "3041", "namaDokumen" => "Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke TLDDP"],
            ["kodeJenisDokumen" => "3042", "namaDokumen" => "Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke PDKB Lain"],
            ["kodeJenisDokumen" => "3043", "namaDokumen" => "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3044", "namaDokumen" => "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Bukan Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3045", "namaDokumen" => "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3046", "namaDokumen" => "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Bukan Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3047", "namaDokumen" => "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3048", "namaDokumen" => "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Bukan Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3049", "namaDokumen" => "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3050", "namaDokumen" => "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Selain Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3051", "namaDokumen" => "Persetujuan Peminjaman Mesin Atau Cetakan (Moulding) Yang Melebihi Jangka Waktu"],
            ["kodeJenisDokumen" => "3052", "namaDokumen" => "Persetujuan Pemusnahan Atas Barangbarang Yang Busuk Dan/Atau Yang Karena Sifat Dan Bentuknya Dapat Dimusnahkan"],
            ["kodeJenisDokumen" => "3053", "namaDokumen" => "Persetujuan Perusakan Atas Barang Asal Luar Daerah Pabean Yang Karena Sifat Dan Bentuknya Tidak Dapat Dimusnahkan"],
            ["kodeJenisDokumen" => "3054", "namaDokumen" => "Persetujuan Menerima Subkontrak Dari TLDDP"],
            ["kodeJenisDokumen" => "3055", "namaDokumen" => "Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3056", "namaDokumen" => "Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Bukan Dalam Rangka Subkontrak"],
            ["kodeJenisDokumen" => "3057", "namaDokumen" => "Persetujuan Peminjaman Mesin/Peralatan Pabrik Dari TLDDP"],
            ["kodeJenisDokumen" => "3060", "namaDokumen" => "Persetujuan Pemasukan Barang Modal Berupa Peralatan Pabrik Dari Luar Daerah Pabean"],
            ["kodeJenisDokumen" => "3061", "namaDokumen" => "Persetujuan Pemasukan Barang Modal Berupa Suku Cadang Dari Luar Daerah Pabean Yang Dimasukkan Tidak Bersamaan Dengan Barang Modal"],
            ["kodeJenisDokumen" => "3062", "namaDokumen" => "Persetujuan Pemasukan Kembali (Reimpor) Barang Hasil Produksi Asal TPB"],
            ["kodeJenisDokumen" => "3063", "namaDokumen" => "Persetujuan Pemasukan Kembali (Reimpor) Barang Modal Setelah Perbaikan/Reparasi Dari Luar Daerah Pabean"],
            ["kodeJenisDokumen" => "3064", "namaDokumen" => "Persetujuan Perpanjangan Jangka Waktu Pengeluaran Barang Modal Keperluan Perbaikan/Reparasi Tujuan TLDDP"],
            ["kodeJenisDokumen" => "3065", "namaDokumen" => "Persetujuan Pengeluaran Barang Contoh/Sampel KB Dengan Tujuan TLDDP"],
            ["kodeJenisDokumen" => "3066", "namaDokumen" => "Rekomendasi Meminjamkan Barang Modal Ke TLDDP Dalam Rangka Subkontrak Atau Bukan Lebih Dari 6 Bulan"]
        ];
        DB::table('jenis_dokumen')->insert($array);
        }
    }
