<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenisKemasanSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $kemasan = [
            ['kodeJenisKemasan' => '1A', 'namaKemasan' => 'Drum, steel'],
            ['kodeJenisKemasan' => '1B', 'namaKemasan' => 'Drum, aluminium'],
            ['kodeJenisKemasan' => '1D', 'namaKemasan' => 'Drum, plywood'],
            ['kodeJenisKemasan' => '1F', 'namaKemasan' => 'Container, flexible'],
            ['kodeJenisKemasan' => '1G', 'namaKemasan' => 'Drum, fibre'],
            ['kodeJenisKemasan' => '1W', 'namaKemasan' => 'Drum, wooden'],
            ['kodeJenisKemasan' => '2C', 'namaKemasan' => 'Barrel, wooden'],
            ['kodeJenisKemasan' => '3A', 'namaKemasan' => 'Jerrican, steel'],
            ['kodeJenisKemasan' => '3H', 'namaKemasan' => 'Jerrican, plastic'],
            ['kodeJenisKemasan' => '43', 'namaKemasan' => 'Bag, super bulk'],
            ['kodeJenisKemasan' => '44', 'namaKemasan' => 'Bag, polybag'],
            ['kodeJenisKemasan' => '4A', 'namaKemasan' => 'Box, steel'],
            ['kodeJenisKemasan' => '4B', 'namaKemasan' => 'Box, aluminium'],
            ['kodeJenisKemasan' => '4C', 'namaKemasan' => 'Box, natural wood'],
            ['kodeJenisKemasan' => '4D', 'namaKemasan' => 'Box, plywood'],
            ['kodeJenisKemasan' => '4F', 'namaKemasan' => 'Box, reconstituted wood'],
            ['kodeJenisKemasan' => '4G', 'namaKemasan' => 'Box, fibreboard'],
            ['kodeJenisKemasan' => '4H', 'namaKemasan' => 'Box, plastic'],
            ['kodeJenisKemasan' => '5H', 'namaKemasan' => 'Bag, woven plastic'],
            ['kodeJenisKemasan' => '5L', 'namaKemasan' => 'Bag, textile'],
            ['kodeJenisKemasan' => '5M', 'namaKemasan' => 'Bag, paper'],
            ['kodeJenisKemasan' => '6H', 'namaKemasan' => 'Composite packaging, plastic receptacle'],
            ['kodeJenisKemasan' => '6P', 'namaKemasan' => 'Composite packaging, glass receptacle'],
            ['kodeJenisKemasan' => '7A', 'namaKemasan' => 'Case, car'],
            ['kodeJenisKemasan' => '7B', 'namaKemasan' => 'Case, wooden'],
            ['kodeJenisKemasan' => '8A', 'namaKemasan' => 'Pallet, wooden'],
            ['kodeJenisKemasan' => '8B', 'namaKemasan' => 'Crate, wooden'],
            ['kodeJenisKemasan' => '8C', 'namaKemasan' => 'Bundle, wooden'],
            ['kodeJenisKemasan' => 'AA', 'namaKemasan' => 'Intermediate bulk container, rigid plastic'],
            ['kodeJenisKemasan' => 'AB', 'namaKemasan' => 'Receptacle, fibre'],
            ['kodeJenisKemasan' => 'AC', 'namaKemasan' => 'Receptacle, paper'],
            ['kodeJenisKemasan' => 'AD', 'namaKemasan' => 'Receptacle, wooden'],
            ['kodeJenisKemasan' => 'AE', 'namaKemasan' => 'Aerosol'],
            ['kodeJenisKemasan' => 'AF', 'namaKemasan' => 'Pallet, modular, collars 80cms * 60cms'],
            ['kodeJenisKemasan' => 'AG', 'namaKemasan' => 'Pallet, shrinkwrapped'],
            ['kodeJenisKemasan' => 'AH', 'namaKemasan' => 'Pallet, 100cms * 110cms'],
            ['kodeJenisKemasan' => 'AI', 'namaKemasan' => 'Clamshell'],
            ['kodeJenisKemasan' => 'AJ', 'namaKemasan' => 'Cone'],
            ['kodeJenisKemasan' => 'AL', 'namaKemasan' => 'Ball'],
            ['kodeJenisKemasan' => 'AM', 'namaKemasan' => 'Ampoule, non protected'],
            ['kodeJenisKemasan' => 'AP', 'namaKemasan' => 'Ampoule, protected'],
            ['kodeJenisKemasan' => 'AT', 'namaKemasan' => 'Atomizer'],
            ['kodeJenisKemasan' => 'AV', 'namaKemasan' => 'Capsule'],
            ['kodeJenisKemasan' => 'B4', 'namaKemasan' => 'Belt'],
            ['kodeJenisKemasan' => 'BA', 'namaKemasan' => 'Barrel'],
            ['kodeJenisKemasan' => 'BB', 'namaKemasan' => 'Bobbin'],
            ['kodeJenisKemasan' => 'BC', 'namaKemasan' => 'Bottlecrate, bottlerack'],
            ['kodeJenisKemasan' => 'BD', 'namaKemasan' => 'Board'],
            ['kodeJenisKemasan' => 'BE', 'namaKemasan' => 'Bundle'],
            ['kodeJenisKemasan' => 'BF', 'namaKemasan' => 'Balloon, non-protected'],
            ['kodeJenisKemasan' => 'BG', 'namaKemasan' => 'Bag'],
            ['kodeJenisKemasan' => 'BH', 'namaKemasan' => 'Bunch'],
            ['kodeJenisKemasan' => 'BI', 'namaKemasan' => 'Bin'],
            ['kodeJenisKemasan' => 'BJ', 'namaKemasan' => 'Bucket'],
            ['kodeJenisKemasan' => 'BK', 'namaKemasan' => 'Basket'],
            ['kodeJenisKemasan' => 'BL', 'namaKemasan' => 'Bale, compressed'],
            ['kodeJenisKemasan' => 'BM', 'namaKemasan' => 'Basin'],
            ['kodeJenisKemasan' => 'BN', 'namaKemasan' => 'Bale, non -compressed'],
            ['kodeJenisKemasan' => 'BO', 'namaKemasan' => 'Bottle, non-protected, cylindrical'],
            ['kodeJenisKemasan' => 'BP', 'namaKemasan' => 'Balloon, protected'],
            ['kodeJenisKemasan' => 'BQ', 'namaKemasan' => 'Bottle, protected cylindrical'],
            ['kodeJenisKemasan' => 'BR', 'namaKemasan' => 'Bar'],
            ['kodeJenisKemasan' => 'BS', 'namaKemasan' => 'Bottle, non-protected, bulbous'],
            ['kodeJenisKemasan' => 'BT', 'namaKemasan' => 'Bolt'],
            ['kodeJenisKemasan' => 'BU', 'namaKemasan' => 'Butt'],
            ['kodeJenisKemasan' => 'BV', 'namaKemasan' => 'Bottle, protected bulbous'],
            ['kodeJenisKemasan' => 'BW', 'namaKemasan' => 'Box, for liquids'],
            ['kodeJenisKemasan' => 'BX', 'namaKemasan' => 'Box'],
            ['kodeJenisKemasan' => 'BY', 'namaKemasan' => 'Board, in bundle/bunch/truss'],
            ['kodeJenisKemasan' => 'BZ', 'namaKemasan' => 'Bars, in bundle/bunch/truss'],
            ['kodeJenisKemasan' => 'CA', 'namaKemasan' => 'Can, rectangular'],
            ['kodeJenisKemasan' => 'CB', 'namaKemasan' => 'Beer crate'],
            ['kodeJenisKemasan' => 'CC', 'namaKemasan' => 'Churn'],
            ['kodeJenisKemasan' => 'CD', 'namaKemasan' => 'Can, with handle and spout'],
            ['kodeJenisKemasan' => 'CE', 'namaKemasan' => 'Creel'],
            ['kodeJenisKemasan' => 'CF', 'namaKemasan' => 'Coffer'],
            ['kodeJenisKemasan' => 'CG', 'namaKemasan' => 'Cage'],
            ['kodeJenisKemasan' => 'CH', 'namaKemasan' => 'Chest'],
            ['kodeJenisKemasan' => 'CI', 'namaKemasan' => 'Canister'],
            ['kodeJenisKemasan' => 'CJ', 'namaKemasan' => 'Coffin'],
            ["kodeJenisKemasan" => "CK", "namaKemasan" => "Cask"],
            ["kodeJenisKemasan" => "CL", "namaKemasan" => "Coil"],
            ["kodeJenisKemasan" => "CM", "namaKemasan" => "Card"],
            ["kodeJenisKemasan" => "CN", "namaKemasan" => "Cont, not otherwise specified as transport equipment"],
            ["kodeJenisKemasan" => "CO", "namaKemasan" => "Carboy, non-protected"],
            ["kodeJenisKemasan" => "CP", "namaKemasan" => "Carboy, protected"],
            ["kodeJenisKemasan" => "CQ", "namaKemasan" => "Cartridge"],
            ["kodeJenisKemasan" => "CR", "namaKemasan" => "Crate"],
            ["kodeJenisKemasan" => "CS", "namaKemasan" => "Case"],
            ["kodeJenisKemasan" => "CT", "namaKemasan" => "Carton"],
            ["kodeJenisKemasan" => "CU", "namaKemasan" => "Cup"],
            ["kodeJenisKemasan" => "CV", "namaKemasan" => "Cover"],
            ["kodeJenisKemasan" => "CW", "namaKemasan" => "Cage, roll"],
            ["kodeJenisKemasan" => "CX", "namaKemasan" => "Can, cylindrical"],
            ["kodeJenisKemasan" => "CY", "namaKemasan" => "Cylinder"],
            ["kodeJenisKemasan" => "CZ", "namaKemasan" => "Canvas"],
            ["kodeJenisKemasan" => "DA", "namaKemasan" => "Crate, multiple layer, plastic"],
            ["kodeJenisKemasan" => "DB", "namaKemasan" => "Crate, multiple layer, wooden"],
            ["kodeJenisKemasan" => "DC", "namaKemasan" => "Crate, multiple layer, cardboard"],
            ["kodeJenisKemasan" => "DG", "namaKemasan" => "Cage, Commonwealth Handling Equipment Pool (CHEP)"],
            ["kodeJenisKemasan" => "DH", "namaKemasan" => "Box, Commonwealth Handling Equipment Pool/CHEP, Eurobox"],
            ["kodeJenisKemasan" => "DI", "namaKemasan" => "Drum, iron"],
            ["kodeJenisKemasan" => "DJ", "namaKemasan" => "Demijohn, non-protected"],
            ["kodeJenisKemasan" => "DK", "namaKemasan" => "Crate, bulk, cardboard"],
            ["kodeJenisKemasan" => "DL", "namaKemasan" => "Crate, bulk, plastic"],
            ["kodeJenisKemasan" => "DM", "namaKemasan" => "Crate, bulk, wooden"],
            ["kodeJenisKemasan" => "DN", "namaKemasan" => "Dispenser"],
            ["kodeJenisKemasan" => "DP", "namaKemasan" => "Demijohn, protected"],
            ["kodeJenisKemasan" => "DR", "namaKemasan" => "Drum"],
            ["kodeJenisKemasan" => "DS", "namaKemasan" => "Tray, one layer no cover, plastic"],
            ["kodeJenisKemasan" => "DT", "namaKemasan" => "Tray, one layer no cover, wooden"],
            ["kodeJenisKemasan" => "DU", "namaKemasan" => "Tray, one layer no cover, polystyrene"],
            ["kodeJenisKemasan" => "DV", "namaKemasan" => "Tray, one layer no cover, cardboard"],
            ["kodeJenisKemasan" => "DW", "namaKemasan" => "Tray, two layers no cover, plastic tray"],
            ["kodeJenisKemasan" => "DX", "namaKemasan" => "Tray, two layers no cover, wooden"],
            ["kodeJenisKemasan" => "DY", "namaKemasan" => "Tray, two layers no cover, cardboard"],
            ["kodeJenisKemasan" => "EC", "namaKemasan" => "Bag, plastic"],
            ["kodeJenisKemasan" => "ED", "namaKemasan" => "Case, with pallet base"],
            ["kodeJenisKemasan" => "EE", "namaKemasan" => "Case, with pallet base, wooden"],
            ["kodeJenisKemasan" => "EF", "namaKemasan" => "Case, with pallet base, cardboard"],
            ["kodeJenisKemasan" => "EG", "namaKemasan" => "Case, with pallet base, plastic"],
            ["kodeJenisKemasan" => "EH", "namaKemasan" => "Case, with pallet base, metal"],
            ["kodeJenisKemasan" => "EI", "namaKemasan" => "Case, isothermic"],
            ["kodeJenisKemasan" => "EN", "namaKemasan" => "Envelope"],
            ["kodeJenisKemasan" => "FB", "namaKemasan" => "Flexibag"],
            ["kodeJenisKemasan" => "FC", "namaKemasan" => "Fruit crate"],
            ["kodeJenisKemasan" => "FD", "namaKemasan" => "Framed crate"],
            ["kodeJenisKemasan" => "FE", "namaKemasan" => "Flexitank"],
            ["kodeJenisKemasan" => "FI", "namaKemasan" => "Firkin"],
            ["kodeJenisKemasan" => "FL", "namaKemasan" => "Flask"],
            ["kodeJenisKemasan" => "FO", "namaKemasan" => "Footlocker"],
            ["kodeJenisKemasan" => "FP", "namaKemasan" => "Filmpack"],
            ["kodeJenisKemasan" => "FR", "namaKemasan" => "Frame"],
            ["kodeJenisKemasan" => "FT", "namaKemasan" => "Foodtainer"],
            ["kodeJenisKemasan" => "FW", "namaKemasan" => "Cart, flatbed"],
            ["kodeJenisKemasan" => "FX", "namaKemasan" => "Bag, flexible container"],
            ["kodeJenisKemasan" => "GB", "namaKemasan" => "Gas bottle"],
            ["kodeJenisKemasan" => "GI", "namaKemasan" => "Girder"],
            ["kodeJenisKemasan" => "GL", "namaKemasan" => "Container, gallon"],
            ["kodeJenisKemasan" => "GR", "namaKemasan" => "Receptacle, glass"],
            ["kodeJenisKemasan" => "GU", "namaKemasan" => "Tray, containing horizontally stacked flat items"],
            ["kodeJenisKemasan" => "GY", "namaKemasan" => "Bag, gunny"],
            ["kodeJenisKemasan" => "GZ", "namaKemasan" => "Girders, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "HA", "namaKemasan" => "Basket, with handle, plastic"],
            ["kodeJenisKemasan" => "HB", "namaKemasan" => "Basket, with handle, wooden"],
            ["kodeJenisKemasan" => "HC", "namaKemasan" => "Basket, with handle, cardboard"],
            ["kodeJenisKemasan" => "HG", "namaKemasan" => "Hogshead"],
            ["kodeJenisKemasan" => "HN", "namaKemasan" => "Hanger"],
            ["kodeJenisKemasan" => "HR", "namaKemasan" => "Hamper"],
            ["kodeJenisKemasan" => "HZ", "namaKemasan" => "bukan kaleng kaleng"],
            ["kodeJenisKemasan" => "IA", "namaKemasan" => "Package, display, wooden"],
            ["kodeJenisKemasan" => "IB", "namaKemasan" => "Package, display, cardboard"],
            ["kodeJenisKemasan" => "IC", "namaKemasan" => "Package, display, plastic"],
            ["kodeJenisKemasan" => "ID", "namaKemasan" => "Package, display, metal"],
            ["kodeJenisKemasan" => "IE", "namaKemasan" => "Package, show"],
            ["kodeJenisKemasan" => "IF", "namaKemasan" => "Package, flow"],
            ["kodeJenisKemasan" => "IG", "namaKemasan" => "Package, paper wrapped"],
            ["kodeJenisKemasan" => "IH", "namaKemasan" => "Drum, plastic"],
            ["kodeJenisKemasan" => "IK", "namaKemasan" => "Package, cardboard, with bottle grip-holes"],
            ["kodeJenisKemasan" => "IL", "namaKemasan" => "Tray, rigid, lidded stackable (CEN TS 14482:2002)"],
            ["kodeJenisKemasan" => "IN", "namaKemasan" => "Ingot"],
            ["kodeJenisKemasan" => "IZ", "namaKemasan" => "Ingots, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "JB", "namaKemasan" => "Bag, jumbo"],
            ["kodeJenisKemasan" => "JC", "namaKemasan" => "Jerrican, rectangular"],
            ["kodeJenisKemasan" => "JG", "namaKemasan" => "Jug"],
            ["kodeJenisKemasan" => "JR", "namaKemasan" => "Jar"],
            ["kodeJenisKemasan" => "JT", "namaKemasan" => "Jutebag"],
            ["kodeJenisKemasan" => "JY", "namaKemasan" => "Jerrican, cylindrical"],
            ["kodeJenisKemasan" => "KG", "namaKemasan" => "Keg"],
            ["kodeJenisKemasan" => "KI", "namaKemasan" => "Kit"],
            ["kodeJenisKemasan" => "KR", "namaKemasan" => "Karung"],
            ["kodeJenisKemasan" => "LE", "namaKemasan" => "Luggage"],
            ["kodeJenisKemasan" => "LG", "namaKemasan" => "Log"],
            ["kodeJenisKemasan" => "LT", "namaKemasan" => "Lot"],
            ["kodeJenisKemasan" => "LU", "namaKemasan" => "Lug"],
            ["kodeJenisKemasan" => "LV", "namaKemasan" => "Liftvan"],
            ["kodeJenisKemasan" => "LZ", "namaKemasan" => "Logs, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "MA", "namaKemasan" => "Crate, metal"],
            ["kodeJenisKemasan" => "MB", "namaKemasan" => "Multiply bag"],
            ["kodeJenisKemasan" => "MC", "namaKemasan" => "Milk crate"],
            ["kodeJenisKemasan" => "ME", "namaKemasan" => "Container, metal"],
            ["kodeJenisKemasan" => "MR", "namaKemasan" => "Receptacle, metal"],
            ["kodeJenisKemasan" => "MS", "namaKemasan" => "Multiwall sack"],
            ["kodeJenisKemasan" => "MT", "namaKemasan" => "Mat"],
            ["kodeJenisKemasan" => "MW", "namaKemasan" => "Receptacle, plastic wrapped"],
            ["kodeJenisKemasan" => "MX", "namaKemasan" => "Match box"],
            ["kodeJenisKemasan" => "NA", "namaKemasan" => "Not available"],
            ["kodeJenisKemasan" => "NE", "namaKemasan" => "Unpacked or unpackaged"],
            ["kodeJenisKemasan" => "NF", "namaKemasan" => "Unpacked or unpackaged, single unit"],
            ["kodeJenisKemasan" => "NG", "namaKemasan" => "Unpacked or unpackaged, multiple units"],
            ["kodeJenisKemasan" => "NS", "namaKemasan" => "Nest"],
            ["kodeJenisKemasan" => "NT", "namaKemasan" => "Net"],
            ["kodeJenisKemasan" => "NU", "namaKemasan" => "Net, tube, plastic"],
            ["kodeJenisKemasan" => "NV", "namaKemasan" => "Net, tube, textile"],
            ["kodeJenisKemasan" => "OA", "namaKemasan" => "Pallet, CHEP 40 cm x 60 cm"],
            ["kodeJenisKemasan" => "OB", "namaKemasan" => "Pallet, CHEP 80 cm x 120 cm"],
            ["kodeJenisKemasan" => "OC", "namaKemasan" => "Pallet, CHEP 100 cm x 120 cm"],
            ["kodeJenisKemasan" => "OD", "namaKemasan" => "Pallet, AS 4068-1993"],
            ["kodeJenisKemasan" => "OE", "namaKemasan" => "Pallet, ISO T11"],
            ["kodeJenisKemasan" => "OF", "namaKemasan" => "Platform, unspecified weight or dimension"],
            ["kodeJenisKemasan" => "OK", "namaKemasan" => "Block"],
            ["kodeJenisKemasan" => "OT", "namaKemasan" => "Octabin"],
            ["kodeJenisKemasan" => "OU", "namaKemasan" => "Container, outer"],
            ["kodeJenisKemasan" => "P2", "namaKemasan" => "Pan"],
            ["kodeJenisKemasan" => "PA", "namaKemasan" => "Packet"],
            ["kodeJenisKemasan" => "PB", "namaKemasan" => "Pallet, box Combined open-ended box and pallet"],
            ["kodeJenisKemasan" => "PC", "namaKemasan" => "Parcel"],
            ["kodeJenisKemasan" => "PD", "namaKemasan" => "Pallet, modular, collars 80cms * 100cms"],
            ["kodeJenisKemasan" => "PE", "namaKemasan" => "Pallet, modular, collars 80cms * 120cms"],
            ["kodeJenisKemasan" => "PF", "namaKemasan" => "Pen"],
            ["kodeJenisKemasan" => "PG", "namaKemasan" => "Plate"],
            ["kodeJenisKemasan" => "PH", "namaKemasan" => "Pitcher"],
            ["kodeJenisKemasan" => "PI", "namaKemasan" => "Pipe"],
            ["kodeJenisKemasan" => "PJ", "namaKemasan" => "Punnet"],
            ["kodeJenisKemasan" => "PK", "namaKemasan" => "Package"],
            ["kodeJenisKemasan" => "PL", "namaKemasan" => "Pail"],
            ["kodeJenisKemasan" => "PN", "namaKemasan" => "Plank"],
            ["kodeJenisKemasan" => "PO", "namaKemasan" => "Pouch"],
            ["kodeJenisKemasan" => "PP", "namaKemasan" => "Piece"],
            ["kodeJenisKemasan" => "PR", "namaKemasan" => "Receptacle, plastic"],
            ["kodeJenisKemasan" => "PT", "namaKemasan" => "Pot"],
            ["kodeJenisKemasan" => "PU", "namaKemasan" => "Tray"],
            ["kodeJenisKemasan" => "PV", "namaKemasan" => "Pipes, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "PX", "namaKemasan" => "Pallet"],
            ["kodeJenisKemasan" => "PY", "namaKemasan" => "Plates, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "PZ", "namaKemasan" => "Pipes, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "QA", "namaKemasan" => "Drum, steel, non-removable head"],
            ["kodeJenisKemasan" => "QB", "namaKemasan" => "Drum, steel, removable head"],
            ["kodeJenisKemasan" => "QC", "namaKemasan" => "Drum, aluminium, non-removable head"],
            ["kodeJenisKemasan" => "QD", "namaKemasan" => "Drum, aluminium, removable head"],
            ["kodeJenisKemasan" => "QF", "namaKemasan" => "Drum, plastic, non-removable head"],
            ["kodeJenisKemasan" => "QG", "namaKemasan" => "Drum, plastic, removable head"],
            ["kodeJenisKemasan" => "QH", "namaKemasan" => "Barrel, wooden, bung type"],
            ["kodeJenisKemasan" => "QJ", "namaKemasan" => "Barrel, wooden, removable head"],
            ["kodeJenisKemasan" => "QK", "namaKemasan" => "Jerrican, steel, non-removable head"],
            ["kodeJenisKemasan" => "QL", "namaKemasan" => "Jerrican, steel, removable head"],
            ["kodeJenisKemasan" => "QM", "namaKemasan" => "Jerrican, plastic, non-removable head"],
            ["kodeJenisKemasan" => "QN", "namaKemasan" => "Jerrican, plastic, removable head"],
            ["kodeJenisKemasan" => "QP", "namaKemasan" => "Box, wooden, natural wood, ordinary"],
            ["kodeJenisKemasan" => "QQ", "namaKemasan" => "Box, wooden, natural wood, with sift proof walls"],
            ["kodeJenisKemasan" => "QR", "namaKemasan" => "Box, plastic, expanded"],
            ["kodeJenisKemasan" => "QS", "namaKemasan" => "Box, plastic, solid"],
            ["kodeJenisKemasan" => "RD", "namaKemasan" => "Rod"],
            ["kodeJenisKemasan" => "RG", "namaKemasan" => "Ring"],
            ["kodeJenisKemasan" => "RJ", "namaKemasan" => "Rack, clothing hanger"],
            ["kodeJenisKemasan" => "RK", "namaKemasan" => "Rack"],
            ["kodeJenisKemasan" => "RL", "namaKemasan" => "Reel"],
            ["kodeJenisKemasan" => "RO", "namaKemasan" => "Roll"],
            ["kodeJenisKemasan" => "RT", "namaKemasan" => "Rednet"],
            ["kodeJenisKemasan" => "RZ", "namaKemasan" => "Rods, in bundle/ bunch/truss"],
            ["kodeJenisKemasan" => "SA", "namaKemasan" => "Sack"],
            ["kodeJenisKemasan" => "SB", "namaKemasan" => "Slab"],
            ["kodeJenisKemasan" => "SC", "namaKemasan" => "Shallow crate"],
            ["kodeJenisKemasan" => "SD", "namaKemasan" => "Spindle"],
            ["kodeJenisKemasan" => "SE", "namaKemasan" => "Sea-chest"],
            ["kodeJenisKemasan" => "SH", "namaKemasan" => "Sachet"],
            ["kodeJenisKemasan" => "SI", "namaKemasan" => "Skid"],
            ["kodeJenisKemasan" => "SK", "namaKemasan" => "Skeleton case"],
            ["kodeJenisKemasan" => "SL", "namaKemasan" => "Slipsheet"],
            ["kodeJenisKemasan" => "SM", "namaKemasan" => "Sheetmetal"],
            ["kodeJenisKemasan" => "SO", "namaKemasan" => "Spool"],
            ["kodeJenisKemasan" => "SP", "namaKemasan" => "Sheet, plastic wrapping"],
            ["kodeJenisKemasan" => "SS", "namaKemasan" => "Case, steel"],
            ["kodeJenisKemasan" => "ST", "namaKemasan" => "Sheet"],
            ["kodeJenisKemasan" => "SU", "namaKemasan" => "Suitcase"],
            ["kodeJenisKemasan" => "SV", "namaKemasan" => "Envelope, steel"],
            ["kodeJenisKemasan" => "SW", "namaKemasan" => "Shrinkwrapped"],
            ["kodeJenisKemasan" => "SX", "namaKemasan" => "Set"],
            ["kodeJenisKemasan" => "SY", "namaKemasan" => "Sleeve"],
            ["kodeJenisKemasan" => "SZ", "namaKemasan" => "Sheets, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "T1", "namaKemasan" => "Tablet"],
            ["kodeJenisKemasan" => "TB", "namaKemasan" => "Tub"],
            ["kodeJenisKemasan" => "TC", "namaKemasan" => "Tea-chest"],
            ["kodeJenisKemasan" => "TD", "namaKemasan" => "Collapsible tube"],
            ["kodeJenisKemasan" => "TE", "namaKemasan" => "Tyre"],
            ["kodeJenisKemasan" => "TG", "namaKemasan" => "Tank container, generic"],
            ["kodeJenisKemasan" => "TI", "namaKemasan" => "Tierce"],
            ["kodeJenisKemasan" => "TK", "namaKemasan" => "Tank, rectangular"],
            ["kodeJenisKemasan" => "TL", "namaKemasan" => "Tub, with lid"],
            ["kodeJenisKemasan" => "TN", "namaKemasan" => "Tin"],
            ["kodeJenisKemasan" => "TO", "namaKemasan" => "Tun"],
            ["kodeJenisKemasan" => "TP", "namaKemasan" => "Tray"],
            ["kodeJenisKemasan" => "TR", "namaKemasan" => "Trunk"],
            ["kodeJenisKemasan" => "TS", "namaKemasan" => "Truss"],
            ["kodeJenisKemasan" => "TT", "namaKemasan" => "Bag, tote"],
            ["kodeJenisKemasan" => "TU", "namaKemasan" => "Tube"],
            ["kodeJenisKemasan" => "TV", "namaKemasan" => "Tube, with nozzle"],
            ["kodeJenisKemasan" => "TW", "namaKemasan" => "Pallet, triwall"],
            ["kodeJenisKemasan" => "TY", "namaKemasan" => "Tank, cylindrical"],
            ["kodeJenisKemasan" => "TZ", "namaKemasan" => "Tubes, in bundle/bunch/truss"],
            ["kodeJenisKemasan" => "UC", "namaKemasan" => "Uncaged"],
            ["kodeJenisKemasan" => "UN", "namaKemasan" => "Unpackaged"],
            ["kodeJenisKemasan" => "VA", "namaKemasan" => "Vat"],
            ["kodeJenisKemasan" => "VG", "namaKemasan" => "Bulk, gas (at 1031 mbar and 15C)"],
            ["kodeJenisKemasan" => "VI", "namaKemasan" => "Vial"],
            ["kodeJenisKemasan" => "VK", "namaKemasan" => "Vanpack"],
            ["kodeJenisKemasan" => "VL", "namaKemasan" => "Bulk, liquid"],
            ["kodeJenisKemasan" => "VN", "namaKemasan" => "Vehicle"],
            ["kodeJenisKemasan" => "VO", "namaKemasan" => "Bulk, solid, large particles ('nodules')"],
            ["kodeJenisKemasan" => "VP", "namaKemasan" => "Vacuumpacked"],
            ["kodeJenisKemasan" => "VQ", "namaKemasan" => "Bulk, liquefied gas (at abnormal temperature/pressure)"],
            ["kodeJenisKemasan" => "VR", "namaKemasan" => "Bulk, solid, granular particles ('grains')"],
            ["kodeJenisKemasan" => "VS", "namaKemasan" => "Bulk, scrap metal"],
            ["kodeJenisKemasan" => "VY", "namaKemasan" => "Bulk, solid, fine particles ('powders')"],
            ["kodeJenisKemasan" => "WA", "namaKemasan" => "Intermediate bulk container"],
            ["kodeJenisKemasan" => "WB", "namaKemasan" => "Wickerbottle"],
            ["kodeJenisKemasan" => "WC", "namaKemasan" => "Intermediate bulk container, steel"],
            ["kodeJenisKemasan" => "WD", "namaKemasan" => "Intermediate bulk container, aluminium"],
            ["kodeJenisKemasan" => "WF", "namaKemasan" => "Intermediate bulk container, metal"],
            ["kodeJenisKemasan" => "WG", "namaKemasan" => "Intermediate bulk container, steel, pressurised >10 kpa"],
            ["kodeJenisKemasan" => "WH", "namaKemasan" => "Intermediate bulk container, aluminium, pressurised >10 kpa"],
            ["kodeJenisKemasan" => "WJ", "namaKemasan" => "Intermediate bulk container, metal, pressure 10 kpa"],
            ["kodeJenisKemasan" => "WK", "namaKemasan" => "Intermediate bulk container, steel, liquid"],
            ["kodeJenisKemasan" => "WL", "namaKemasan" => "Intermediate bulk container, aluminium, liquid"],
            ["kodeJenisKemasan" => "WM", "namaKemasan" => "Intermediate bulk container, metal, liquid"],
             ["kodeJenisKemasan" => "WN", "namaKemasan" => "Intermd bulk cont, woven plastic, without coat/liner"],
    ["kodeJenisKemasan" => "WP", "namaKemasan" => "Intermediate bulk container, woven plastic, coated"],
    ["kodeJenisKemasan" => "WQ", "namaKemasan" => "Intermd bulk cont, woven plastic, with liner"],
    ["kodeJenisKemasan" => "WR", "namaKemasan" => "Intermedt bulk cont, woven plastic, coated and liner"],
    ["kodeJenisKemasan" => "WS", "namaKemasan" => "Intermediate bulk container, plastic film"],
    ["kodeJenisKemasan" => "WT", "namaKemasan" => "Intermediate bulk cont, textile with out coat/liner"],
    ["kodeJenisKemasan" => "WU", "namaKemasan" => "Intermdte bulk cont, natural wood, with inner liner"],
    ["kodeJenisKemasan" => "WV", "namaKemasan" => "Intermediate bulk container, textile, coated"],
    ["kodeJenisKemasan" => "WW", "namaKemasan" => "Intermediate bulk container, textile, with liner"],
    ["kodeJenisKemasan" => "WX", "namaKemasan" => "Intermediate bulk cont, textile, coated and liner"],
    ["kodeJenisKemasan" => "WY", "namaKemasan" => "Intermediate bulk cont, plywood, with inner liner"],
    ["kodeJenisKemasan" => "WZ", "namaKemasan" => "Intermd bulk cont, reconstttd wood, with inner liner"],
    ["kodeJenisKemasan" => "XA", "namaKemasan" => "Bag, woven plastic, without inner coat/liner"],
    ["kodeJenisKemasan" => "XB", "namaKemasan" => "Bag, woven plastic, sift proof"],
    ["kodeJenisKemasan" => "XC", "namaKemasan" => "Bag, woven plastic, water resistant"],
    ["kodeJenisKemasan" => "XD", "namaKemasan" => "Bag, plastics film"],
    ["kodeJenisKemasan" => "XF", "namaKemasan" => "Bag, textile, without inner coat/liner"],
    ["kodeJenisKemasan" => "XG", "namaKemasan" => "Bag, textile, sift proof"],
    ["kodeJenisKemasan" => "XH", "namaKemasan" => "Bag, textile, water resistant"],
    ["kodeJenisKemasan" => "XJ", "namaKemasan" => "Bag, paper, multi-wall"],
    ["kodeJenisKemasan" => "XK", "namaKemasan" => "Bag, paper, multi-wall, water resistant"],
    ["kodeJenisKemasan" => "XN", "namaKemasan" => "test"],
    ["kodeJenisKemasan" => "YA", "namaKemasan" => "Compsite packging,plastic receptacle in steel drum"],
    ["kodeJenisKemasan" => "YB", "namaKemasan" => "Compste packgng,plastc recptcle in steel crate box"],
    ["kodeJenisKemasan" => "YC", "namaKemasan" => "Compste packgng,plastic recptcle in aluminium drum"],
    ["kodeJenisKemasan" => "YD", "namaKemasan" => "Compste packgng,plastic recptcle in alumnium crate"],
    ["kodeJenisKemasan" => "YF", "namaKemasan" => "Compsite packging,plastic receptacle in wooden box"],
    ["kodeJenisKemasan" => "YG", "namaKemasan" => "Compste packgng,plastic receptacle in plywood drum"],
    ["kodeJenisKemasan" => "YH", "namaKemasan" => "Compste packging,plastic receptacle in plywood box"],
    ["kodeJenisKemasan" => "YJ", "namaKemasan" => "Compsite packging,plastic receptacle in fibre drum"],
    ["kodeJenisKemasan" => "YK", "namaKemasan" => "Compste packgng,plastic recptcle in fibreboard box"],
    ["kodeJenisKemasan" => "YL", "namaKemasan" => "Compste packgng,plastic receptacle in plastic drum"],
            ["kodeJenisKemasan" => "YM", "namaKemasan" => "Compsite packgng,plstc recptcle in solid plstc box"],
            ["kodeJenisKemasan" => "YN", "namaKemasan" => "Composite packaging,glass receptacle in steel drum"],
            ["kodeJenisKemasan" => "YP", "namaKemasan" => "Compste packgng,glass recptacle in steel crate box"],
            ["kodeJenisKemasan" => "YQ", "namaKemasan" => "Compste packgng,glass receptacle in aluminium drum"],
            ["kodeJenisKemasan" => "YR", "namaKemasan" => "Compste packgng,glass recptacle in aluminium crate"],
            ["kodeJenisKemasan" => "YS", "namaKemasan" => "Composite packaging,glass receptacle in wooden box"],
            ["kodeJenisKemasan" => "YT", "namaKemasan" => "Compsite packging,glass receptacle in plywood drum"],
            ["kodeJenisKemasan" => "YV", "namaKemasan" => "Compste packgng,glass recptcle in wickrwork hamper"],
            ["kodeJenisKemasan" => "YW", "namaKemasan" => "Composite packaging,glass receptacle in fibre drum"],
            ["kodeJenisKemasan" => "YX", "namaKemasan" => "Compste packgng,glass receptacle in fibreboard box"],
            ["kodeJenisKemasan" => "YY", "namaKemasan" => "Compste pckgng,glss recptcl in expndbl plastc pack"],
            ["kodeJenisKemasan" => "YZ", "namaKemasan" => "Compsite packgng,glass recptcle in solid plstc pck"],
            ["kodeJenisKemasan" => "ZA", "namaKemasan" => "Intermediate bulk container, paper, multi-wall"],
            ["kodeJenisKemasan" => "ZB", "namaKemasan" => "Bag, large"],
            ["kodeJenisKemasan" => "ZC", "namaKemasan" => "Intermd bulk cont,paper,multi-wall,water resistant"],
            ["kodeJenisKemasan" => "ZD", "namaKemasan" => "Intermd bulk cont,rgd plstc,w/strctrl equipm,solid"],
            ["kodeJenisKemasan" => "ZF", "namaKemasan" => "Intermd bulk cont,rgid plstc,freestandng,solds"],
            ["kodeJenisKemasan" => "ZG", "namaKemasan" => "Intermdbulk cnt,rgd plstc,w/strctrl equipm,pressrd"],
            ["kodeJenisKemasan" => "ZH", "namaKemasan" => "Intermd bulk cont,rgd plstc,freestnd,pressurised"],
            ["kodeJenisKemasan" => "ZJ", "namaKemasan" => "Intermd bulk cont,rgd plstc,w/strctrl equipm,lquid"],
            ["kodeJenisKemasan" => "ZK", "namaKemasan" => "Intermd bulk cont,rgid plstc,freestanding,liquids"],
            ["kodeJenisKemasan" => "ZL", "namaKemasan" => "Intermd bulk cont,composite,rigid plastic,solids"],
            ["kodeJenisKemasan" => "ZM", "namaKemasan" => "Intermd bulk cont,compste,flexbl plastic, solids"],
            ["kodeJenisKemasan" => "ZN", "namaKemasan" => "Intermd bulk cont,compsit,rgid plstc,pressurised"],
            ["kodeJenisKemasan" => "ZP", "namaKemasan" => "Intermd bulk cont,compsit,flexbl plstc,pressurised"],
            ["kodeJenisKemasan" => "ZQ", "namaKemasan" => "Intermd bulk cont,composite,rigid plastic,liquids"],
            ["kodeJenisKemasan" => "ZR", "namaKemasan" => "Intermd bulk cont,compsite,flexible plastc,liquids"],
            ["kodeJenisKemasan" => "ZS", "namaKemasan" => "Intermediate bulk container, composite"],
            ["kodeJenisKemasan" => "ZT", "namaKemasan" => "Intermediate bulk container, fibreboard"],
            ["kodeJenisKemasan" => "ZU", "namaKemasan" => "Intermediate bulk container, flexible"],
            ["kodeJenisKemasan" => "ZV", "namaKemasan" => "Intermediate bulk container,metal,other than steel"],
            ["kodeJenisKemasan" => "ZW", "namaKemasan" => "Intermediate bulk container, natural wood"],
            ["kodeJenisKemasan" => "ZX", "namaKemasan" => "Intermediate bulk container, plywood"],
            ["kodeJenisKemasan" => "ZY", "namaKemasan" => "Intermediate bulk container, reconstituted wood"],
            ["kodeJenisKemasan" => "ZZ", "namaKemasan" => "Mutually defined"],

        ];
        $kemasan = array_unique($kemasan, SORT_REGULAR);
        DB::table('jenis_kemasan')->insert($kemasan);
        }
    }
