<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KantorSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $kantor = [
            ['kodeKantor' => "000000", 'namaKantor' => "DJBC"],
            ['kodeKantor' => "001000", 'namaKantor' => "SEKRETARIAT"],
            ['kodeKantor' => "001100", 'namaKantor' => "TP BIDANG I"],
            ['kodeKantor' => "001200", 'namaKantor' => "TP BIDANG II"],
            ['kodeKantor' => "001300", 'namaKantor' => "TP BIDANG III"],
            ['kodeKantor' => "001400", 'namaKantor' => "DIREKTORAT KI"],
            ['kodeKantor' => "001500", 'namaKantor' => "DIREKTORAT KBP"],
            ['kodeKantor' => "002000", 'namaKantor' => "DIREKTORAT TEKNIS"],
            ['kodeKantor' => "003000", 'namaKantor' => "DIREKTORAT FASILITAS"],
            ['kodeKantor' => "004000", 'namaKantor' => "DIREKTORAT CUKAI"],
            ['kodeKantor' => "005000", 'namaKantor' => "DIREKTORAT P2"],
            ['kodeKantor' => "006000", 'namaKantor' => "DIREKTORAT AUDIT"],
            ['kodeKantor' => "007000", 'namaKantor' => "DIREKTORAT KIAL"],
            ['kodeKantor' => "008000", 'namaKantor' => "DIREKTORAT PPS"],
            ['kodeKantor' => "009000", 'namaKantor' => "DIREKTORAT IKC"],
            ['kodeKantor' => "010000", 'namaKantor' => "KANWIL SUMUT"],
            ['kodeKantor' => "010100", 'namaKantor' => "KPPBC KUALANAMU"],
            ['kodeKantor' => "010700", 'namaKantor' => "KPPBC ELAWAN"],
            ['kodeKantor' => "010800", 'namaKantor' => "KPPBC MEDAN"],
            ['kodeKantor' => "010900", 'namaKantor' => "KPPBC PANGKALAN SUSU"],
            ['kodeKantor' => "011000", 'namaKantor' => "KPPBC PEMATANGSIANTAR"],
            ['kodeKantor' => "011100", 'namaKantor' => "KPPBC TELUK NIBUNG"],
            ['kodeKantor' => "011200", 'namaKantor' => "KPPBC KUALA TANJUNG"],
            ['kodeKantor' => "011300", 'namaKantor' => "KPPBC SIBOLGA"],
            ['kodeKantor' => "011500", 'namaKantor' => "KPPBC TELUK BAYUR"],
            ['kodeKantor' => "011600", 'namaKantor' => "BLBC KELAS II MEDAN"],
            ['kodeKantor' => "020000", 'namaKantor' => "KANWIL KHUSUS KEPRI"],
            ['kodeKantor' => "020100", 'namaKantor' => "KPPBC TBK"],
            ['kodeKantor' => "020200", 'namaKantor' => "KPPBC SAMBU BELAKANG PADANG"],
            ['kodeKantor' => "020300", 'namaKantor' => "KPPBC SELAT PANJANG"],
            ['kodeKantor' => "020400", 'namaKantor' => "KPU BATAM"],
            ['kodeKantor' => "020500", 'namaKantor' => "KPPBC TANJUNG PINANG"],
            ['kodeKantor' => "020800", 'namaKantor' => "KPPBC DABO SINGKEP"],
            ['kodeKantor' => "020900", 'namaKantor' => "KPPBC DUMAI"],
            ['kodeKantor' => "021000", 'namaKantor' => "KPPBC BAGAN SIAPIAPI"],
            ['kodeKantor' => "021100", 'namaKantor' => "KPPBC BENGKALIS"],
            ['kodeKantor' => "021200", 'namaKantor' => "KPPBC PEKANBARU"],
            ['kodeKantor' => "021300", 'namaKantor' => "KPPBC SIAK SRI INDRAPURA"],
            ['kodeKantor' => "021500", 'namaKantor' => "KPPBC TEMBILAHAN"],
            ['kodeKantor' => "021700", 'namaKantor' => "KPPBC TAREMPA"],
            ['kodeKantor' => "021800", 'namaKantor' => "PANGSAROP BATAM"],
            ['kodeKantor' => "021900", 'namaKantor' => "PANGSAROP  TANJUNG BALAI KARIMUN"],
            ['kodeKantor' => "030000", 'namaKantor' => "KANWIL SUMBAGTIM"],
            ['kodeKantor' => "030100", 'namaKantor' => "KPPBC PALEMBANG"],
            ['kodeKantor' => "030200", 'namaKantor' => "KPPBC BENGKULU"],
            ['kodeKantor' => "030300", 'namaKantor' => "KPPBC PANGKALPINANG"],
            ['kodeKantor' => "030500", 'namaKantor' => "KPPBC TANJUNGPANDAN"],
            ['kodeKantor' => "030600", 'namaKantor' => "KPPBC JAMBI"],
            ['kodeKantor' => "030700", 'namaKantor' => "KPPBC BANDAR LAMPUNG"],
            ['kodeKantor' => "040000", 'namaKantor' => "KANWIL JAKARTA"],
            ['kodeKantor' => "040300", 'namaKantor' => "KPU TANJUNG PRIOK"],
            ['kodeKantor' => "040400", 'namaKantor' => "KPPBC JAKARTA"],
            ['kodeKantor' => "040500", 'namaKantor' => "BLBC KELAS I JAKARTA"],
            ['kodeKantor' => "040600", 'namaKantor' => "KPPBC KANTOR POS PASAR BARU"],
            ['kodeKantor' => "040700", 'namaKantor' => "PANGSAROP TANJUNG PRIOK"],
            ['kodeKantor' => "050000", 'namaKantor' => "KANWIL JABAR"],
            ['kodeKantor' => "050100", 'namaKantor' => "KPU  SOEKARNO-HATTA"],
            ['kodeKantor' => "050300", 'namaKantor' => "KPPBC  BOGOR"],
            ['kodeKantor' => "050400", 'namaKantor' => "KPPBC TMP MERAK"],
            ['kodeKantor' => "050500", 'namaKantor' => "KPPBC BANDUNG"],
            ['kodeKantor' => "050600", 'namaKantor' => "KPPBC TASIKMALAYA"],
            ['kodeKantor' => "050700", 'namaKantor' => "KPPBC CIREBON"],
            ['kodeKantor' => "050800", 'namaKantor' => "KPPBC PURWAKARTA"],
            ['kodeKantor' => "050900", 'namaKantor' => "KPPBC BEKASI"],
            ['kodeKantor' => "051000", 'namaKantor' => "KPPBC IKARANG"],
            ['kodeKantor' => "060000", 'namaKantor' => "KANWIL JATENG DIY"],
            ['kodeKantor' => "060100", 'namaKantor' => "KPPBC TMP TANJUNG EMAS"],
            ['kodeKantor' => "060200", 'namaKantor' => "KPPBC PEKALONGAN"],
            ['kodeKantor' => "060300", 'namaKantor' => "KPPBC TMC KUDUS"],
            ['kodeKantor' => "060400", 'namaKantor' => "KPPBC CILACAP"],
            ['kodeKantor' => "060600", 'namaKantor' => "KPPBC SURAKARTA"],
            ['kodeKantor' => "060700", 'namaKantor' => "KPPBC YOGYAKARTA"],
            ['kodeKantor' => "060800", 'namaKantor' => "KPPBC SEMARANG"],
            ['kodeKantor' => "061000", 'namaKantor' => "KPPBC TEGAL"],
            ['kodeKantor' => "061100", 'namaKantor' => "KPPBC MAGELANG"],
            ['kodeKantor' => "062000", 'namaKantor' => "KPPBC PURWOKERTO"],
            ['kodeKantor' => "070000", 'namaKantor' => "KANWIL JATIM I"],
            ['kodeKantor' => "070100", 'namaKantor' => "KPPBC TMP TANJUNG PERAK"],
            ['kodeKantor' => "070200", 'namaKantor' => "KPPBC MADURA"],
            ['kodeKantor' => "070300", 'namaKantor' => "KPPBC GRESIK"],
            ['kodeKantor' => "070400", 'namaKantor' => "KPPBC BOJONEGORO"],
            ['kodeKantor' => "070500", 'namaKantor' => "KPPBC TMP JUANDA"],
            ['kodeKantor' => "070600", 'namaKantor' => "KPPBC TMC MALANG"],
            ['kodeKantor' => "070700", 'namaKantor' => "KPPBC BLITAR"],
            ['kodeKantor' => "070800", 'namaKantor' => "KPPBC TMC KEDIRI"],
            ['kodeKantor' => "070900", 'namaKantor' => "KPPBC TULUNG AGUNG"],
            ['kodeKantor' => "071000", 'namaKantor' => "KPPBC MADIUN"],
            ['kodeKantor' => "071100", 'namaKantor' => "KPPBC JEMBER"],
            ['kodeKantor' => "071200", 'namaKantor' => "KPPBC PROBOLINGGO"],
            ['kodeKantor' => "071300", 'namaKantor' => "KPPBC PASURUAN"],
            ['kodeKantor' => "071400", 'namaKantor' => "BLBC KELAS II SURABAYA"],
            ['kodeKantor' => "071500", 'namaKantor' => "KPPBC SIDOARJO"],
            ['kodeKantor' => "080000", 'namaKantor' => "KANWIL BALI, NTB DAN NTT"],
            ['kodeKantor' => "080100", 'namaKantor' => "KPPBC TMP NGURAH RAI"],
            ['kodeKantor' => "080200", 'namaKantor' => "KPPBC DENPASAR"],
            ['kodeKantor' => "080300", 'namaKantor' => "KPPBC MATARAM"],
            ['kodeKantor' => "080400", 'namaKantor' => "KPPBC SUMBAWA"],
            ['kodeKantor' => "080500", 'namaKantor' => "KPPBC KUPANG"],
            ['kodeKantor' => "080700", 'namaKantor' => "KPPBC MAUMERE"],
            ['kodeKantor' => "081200", 'namaKantor' => "KPPBC BENOA"],
            ['kodeKantor' => "081300", 'namaKantor' => "KPPBC ATAPUPU"],
            ['kodeKantor' => "081400", 'namaKantor' => "KPPBC ATAMBUA"],
            ['kodeKantor' => "090000", 'namaKantor' => "KANWIL KALBAGBAR"],
            ['kodeKantor' => "090100", 'namaKantor' => "KPPBC PONTIANAK"],
            ['kodeKantor' => "090200", 'namaKantor' => "KPPBC ENTIKONG"],
            ['kodeKantor' => "090400", 'namaKantor' => "KPPBC KETAPANG"],
            ['kodeKantor' => "090500", 'namaKantor' => "KPPBC SINTETE"],
            ['kodeKantor' => "090700", 'namaKantor' => "KPPBC SAMPIT"],
            ['kodeKantor' => "090800", 'namaKantor' => "KPPBC PANGKALAN BUN"],
            ['kodeKantor' => "090900", 'namaKantor' => "KPPBC PULANG PISAU"],
            ['kodeKantor' => "091000", 'namaKantor' => "KPPBC NANGA BADAU"],
            ['kodeKantor' => "092000", 'namaKantor' => "KPPBC JAGOI BABANG"],
            ['kodeKantor' => "100000", 'namaKantor' => "KANWIL KALBAGTIM"],
            ['kodeKantor' => "100100", 'namaKantor' => "KPPBC BANJARMASIN"],
            ['kodeKantor' => "100200", 'namaKantor' => "KPPBC KOTABARU"],
            ['kodeKantor' => "100300", 'namaKantor' => "KPPBC BALIKPAPAN"],
            ['kodeKantor' => "100500", 'namaKantor' => "KPPBC SAMARINDA"],
            ['kodeKantor' => "100600", 'namaKantor' => "KPPBC BONTANG"],
            ['kodeKantor' => "100800", 'namaKantor' => "KPPBC TARAKAN"],
            ['kodeKantor' => "100900", 'namaKantor' => "KPPBC NUNUKAN"],
            ['kodeKantor' => "101000", 'namaKantor' => "KPPBC SANGATTA"],
            ['kodeKantor' => "110000", 'namaKantor' => "KANWIL SULBAGSEL"],
            ['kodeKantor' => "110100", 'namaKantor' => "KPPBC MAKASSAR"],
            ['kodeKantor' => "110300", 'namaKantor' => "KPPBC PAREPARE"],
            ['kodeKantor' => "110400", 'namaKantor' => "KPPBC MALILI"],
            ['kodeKantor' => "110500", 'namaKantor' => "KPPBC BAJOE"],
            ['kodeKantor' => "110600", 'namaKantor' => "KPPBC KENDARI"],
            ['kodeKantor' => "110700", 'namaKantor' => "KPPBC POMALAA"],
            ['kodeKantor' => "110800", 'namaKantor' => "KPPBC PANTOLOAN"],
            ['kodeKantor' => "110900", 'namaKantor' => "KPPBC MOROWALI"],
            ['kodeKantor' => "111000", 'namaKantor' => "KPPBC LUWUK"],
            ['kodeKantor' => "111100", 'namaKantor' => "KPPBC BITUNG"],
            ['kodeKantor' => "111200", 'namaKantor' => "KPPBC MANADO"],
            ['kodeKantor' => "111300", 'namaKantor' => "KPPBC GORONTALO"],
            ['kodeKantor' => "111400", 'namaKantor' => "PANGSAROP PANTOLOAN"],
            ['kodeKantor' => "120000", 'namaKantor' => "KANWIL MALUKU"],
            ['kodeKantor' => "120100", 'namaKantor' => "KPPBC AMBON"],
            ['kodeKantor' => "120200", 'namaKantor' => "KPPBC TERNATE"],
            ['kodeKantor' => "120300", 'namaKantor' => "KPPBC SORONG"],
            ['kodeKantor' => "120400", 'namaKantor' => "KPPBC MANOKWARI"],
            ['kodeKantor' => "120500", 'namaKantor' => "KPPBC FAK-FAK"],
            ['kodeKantor' => "120600", 'namaKantor' => "KPPBC JAYAPURA"],
            ['kodeKantor' => "120700", 'namaKantor' => "KPPBC MERAUKE"],
            ['kodeKantor' => "120800", 'namaKantor' => "KPPBC AMAMAPARE"],
            ['kodeKantor' => "120900", 'namaKantor' => "KPPBC BIAK"],
            ['kodeKantor' => "121000", 'namaKantor' => "KPPBC TUAL"],
            ['kodeKantor' => "121100", 'namaKantor' => "PANGSAROP SORONG"],
            ['kodeKantor' => "122000", 'namaKantor' => "KPPBC BINTUNI"],
            ['kodeKantor' => "122100", 'namaKantor' => "KPPBC KAIMANA"],
            ['kodeKantor' => "122200", 'namaKantor' => "KPPBC NABIRE"],
            ['kodeKantor' => "122300", 'namaKantor' => "KPPBC BABO"],
            ['kodeKantor' => "130000", 'namaKantor' => "KANWIL ACEH"],
            ['kodeKantor' => "130100", 'namaKantor' => "KPPBC BANDA ACEH"],
            ['kodeKantor' => "130300", 'namaKantor' => "KPPBC SABANG"],
            ['kodeKantor' => "130400", 'namaKantor' => "KPPBC MEULABOH"],
            ['kodeKantor' => "130500", 'namaKantor' => "KPPBC LHOKSEUMAWE"],
            ['kodeKantor' => "130600", 'namaKantor' => "KPPBC KUALA LANGSA"],
            ['kodeKantor' => "140000", 'namaKantor' => "KANWIL RIAU"],
            ['kodeKantor' => "150000", 'namaKantor' => "KANWIL BANTEN"],
            ['kodeKantor' => "150300", 'namaKantor' => "KPPBC TANGERANG"],
            ['kodeKantor' => "160000", 'namaKantor' => "KANWIL JATIM II"],
            ['kodeKantor' => "160200", 'namaKantor' => "KPPBC MARUNDA"],
            ['kodeKantor' => "160700", 'namaKantor' => "KPPBC BANYUWANGI"],
            ['kodeKantor' => "170000", 'namaKantor' => "KANWIL SUMBAGBAR"],
            ['kodeKantor' => "180000", 'namaKantor' => "KANWIL KALBAGSEL"],
            ['kodeKantor' => "180100", 'namaKantor' => "KPPBC Nashta"],
            ['kodeKantor' => "180200", 'namaKantor' => "KPPBC Nashta"],
            ['kodeKantor' => "190000", 'namaKantor' => "KANWIL SULBAGTARA"],
            ['kodeKantor' => "200000", 'namaKantor' => "KANWIL KHUSUS PAPUA"],
            ['kodeKantor' => "760000", 'namaKantor' => "PUSDIKLAT BEA DAN CUKAI"],
            ['kodeKantor' => "999999", 'namaKantor' => "UNIT LAIN DI LUAR DJBC"]
        ];

        DB::table('kantor')->insert($kantor);

        }
    }
