<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NegaraSeeder extends Seeder
    {
    public function run()
        {
        $negara = [
            ['kodeNegara' => 'AD', 'namaNegara' => 'ANDORRA'],
            ['kodeNegara' => 'AE', 'namaNegara' => 'UNITED ARAB EMIRATES'],
            ['kodeNegara' => 'AF', 'namaNegara' => 'AFGHANISTAN'],
            ['kodeNegara' => 'AG', 'namaNegara' => 'ANTIGUA AND BARBUDA'],
            ['kodeNegara' => 'AI', 'namaNegara' => 'ANGUILLA'],
            ['kodeNegara' => 'AL', 'namaNegara' => 'ALBANIA'],
            ['kodeNegara' => 'AM', 'namaNegara' => 'ARMENIA'],
            ['kodeNegara' => 'AN', 'namaNegara' => 'NETHERLANDS ANTILLES'],
            ['kodeNegara' => 'AO', 'namaNegara' => 'ANGOLA'],
            ['kodeNegara' => 'AQ', 'namaNegara' => 'ANTARCTICA'],
            ['kodeNegara' => 'AR', 'namaNegara' => 'ARGENTINA'],
            ['kodeNegara' => 'AS', 'namaNegara' => 'AMERICAN SAMOA'],
            ['kodeNegara' => 'AT', 'namaNegara' => 'AUSTRIA'],
            ['kodeNegara' => 'AU', 'namaNegara' => 'AUSTRALIA'],
            ['kodeNegara' => 'AW', 'namaNegara' => 'ARUBA'],
            ['kodeNegara' => 'AX', 'namaNegara' => 'Aland Islands'],
            ['kodeNegara' => 'AZ', 'namaNegara' => 'AZERBAIJAN'],
            ['kodeNegara' => 'BA', 'namaNegara' => 'BOSNIA AND HERZEGOVINA'],
            ['kodeNegara' => 'BB', 'namaNegara' => 'BARBADOS'],
            ['kodeNegara' => 'BD', 'namaNegara' => 'BANGLADESH'],
            ['kodeNegara' => 'BE', 'namaNegara' => 'BELGIUM'],
            ['kodeNegara' => 'BF', 'namaNegara' => 'BURKINA FASO'],
            ['kodeNegara' => 'BG', 'namaNegara' => 'BULGARIA'],
            ['kodeNegara' => 'BH', 'namaNegara' => 'BAHRAIN'],
            ['kodeNegara' => 'BI', 'namaNegara' => 'BURUNDI'],
            ['kodeNegara' => 'BJ', 'namaNegara' => 'BENIN'],
            ['kodeNegara' => 'BL', 'namaNegara' => 'Saint Barthelemy'],
            ['kodeNegara' => 'BM', 'namaNegara' => 'BERMUDA'],
            ['kodeNegara' => 'BN', 'namaNegara' => 'BRUNEI DARUSSALAM'],
            ['kodeNegara' => 'BO', 'namaNegara' => 'BOLIVIA'],
            ['kodeNegara' => 'BQ', 'namaNegara' => 'Bonaire, Sint Eustatius and Saba'],
            ['kodeNegara' => 'BR', 'namaNegara' => 'BRAZIL'],
            ['kodeNegara' => 'BS', 'namaNegara' => 'BAHAMAS'],
            ['kodeNegara' => 'BT', 'namaNegara' => 'BHUTAN'],
            ['kodeNegara' => 'BV', 'namaNegara' => 'BOUVET ISLAND'],
            ['kodeNegara' => 'BW', 'namaNegara' => 'BOTSWANA'],
            ['kodeNegara' => 'BY', 'namaNegara' => 'BELARUS'],
            ['kodeNegara' => 'BZ', 'namaNegara' => 'BELIZE'],
            ['kodeNegara' => 'CA', 'namaNegara' => 'CANADA'],
            ['kodeNegara' => 'CC', 'namaNegara' => 'COCOS (KEELING) ISLANDS'],
            ['kodeNegara' => 'CD', 'namaNegara' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'],
            ['kodeNegara' => 'CF', 'namaNegara' => 'CENTRAL AFRICAN REPUBLIC'],
            ['kodeNegara' => 'CG', 'namaNegara' => 'CONGO'],
            ['kodeNegara' => 'CH', 'namaNegara' => 'SWITZERLAND'],
            ['kodeNegara' => 'CI', 'namaNegara' => 'COTE D\'IVOIRE'],
            ['kodeNegara' => 'CK', 'namaNegara' => 'COOK ISLANDS'],
            ['kodeNegara' => 'CL', 'namaNegara' => 'CHILE'],
            ['kodeNegara' => 'CM', 'namaNegara' => 'CAMEROON'],
            ['kodeNegara' => 'CN', 'namaNegara' => 'CHINA'],
            ['kodeNegara' => 'CO', 'namaNegara' => 'COLOMBIA'],
            ['kodeNegara' => 'CR', 'namaNegara' => 'COSTA RICA'],
            ['kodeNegara' => 'CS', 'namaNegara' => 'FORMER CZECHOSLOVAKIA'],
            ['kodeNegara' => 'CU', 'namaNegara' => 'CUBA'],
            ['kodeNegara' => 'CV', 'namaNegara' => 'CAPE VERDE'],
            ['kodeNegara' => 'CW', 'namaNegara' => 'Curacao'],
            ['kodeNegara' => 'CX', 'namaNegara' => 'CHRISTMAS ISLAND'],
            ['kodeNegara' => 'CY', 'namaNegara' => 'CYPRUS'],
            ['kodeNegara' => 'CZ', 'namaNegara' => 'CZECH REPUBLIC'],
            ['kodeNegara' => 'DE', 'namaNegara' => 'GERMANY'],
            ['kodeNegara' => 'DJ', 'namaNegara' => 'DJIBOUTI'],
            ['kodeNegara' => 'DK', 'namaNegara' => 'DENMARK'],
            ['kodeNegara' => 'DM', 'namaNegara' => 'DOMINICA'],
            ['kodeNegara' => 'DO', 'namaNegara' => 'DOMINICAN REPUBLIC'],
            ['kodeNegara' => 'DZ', 'namaNegara' => 'ALGERIA'],
            ['kodeNegara' => 'EC', 'namaNegara' => 'ECUADOR'],
            ['kodeNegara' => 'EE', 'namaNegara' => 'ESTONIA'],
            ['kodeNegara' => 'EG', 'namaNegara' => 'EGYPT'],
            ['kodeNegara' => 'EH', 'namaNegara' => 'WESTERN SAHARA'],
            ['kodeNegara' => 'ER', 'namaNegara' => 'ERITREA'],
            ['kodeNegara' => 'ES', 'namaNegara' => 'SPAIN'],
            ['kodeNegara' => 'ET', 'namaNegara' => 'ETHIOPIA'],
            ['kodeNegara' => 'FI', 'namaNegara' => 'FINLAND'],
            ['kodeNegara' => 'FJ', 'namaNegara' => 'FIJI'],
            ['kodeNegara' => 'FK', 'namaNegara' => 'FALKLAND ISLANDS (MALVINAS)'],
            ['kodeNegara' => 'FM', 'namaNegara' => 'MICRONESIA, FEDERATED STATES OF'],
            ['kodeNegara' => 'FO', 'namaNegara' => 'FAROE ISLANDS'],
            ['kodeNegara' => 'FR', 'namaNegara' => 'FRANCE'],
            ['kodeNegara' => 'GA', 'namaNegara' => 'GABON'],
            ['kodeNegara' => 'GB', 'namaNegara' => 'UNITED KINGDOM'],
            ['kodeNegara' => 'GD', 'namaNegara' => 'GRENADA'],
            ['kodeNegara' => 'GE', 'namaNegara' => 'GEORGIA'],
            ['kodeNegara' => 'GF', 'namaNegara' => 'FRENCH GUIANA'],
            ['kodeNegara' => 'GG', 'namaNegara' => 'Guernsey'],
            ['kodeNegara' => 'GH', 'namaNegara' => 'GHANA'],
            ['kodeNegara' => 'GI', 'namaNegara' => 'GIBRALTAR'],
            ['kodeNegara' => 'GL', 'namaNegara' => 'GREENLAND'],
            ['kodeNegara' => 'GM', 'namaNegara' => 'GAMBIA'],
            ['kodeNegara' => 'GN', 'namaNegara' => 'GUINEA'],
            ['kodeNegara' => 'GP', 'namaNegara' => 'GUADELOUPE'],
            ['kodeNegara' => 'GQ', 'namaNegara' => 'EQUATORIAL GUINEA'],
            ['kodeNegara' => 'GR', 'namaNegara' => 'GREECE'],
            ['kodeNegara' => 'GS', 'namaNegara' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL'],
            ['kodeNegara' => 'GT', 'namaNegara' => 'GUATEMALA'],
            ['kodeNegara' => 'GU', 'namaNegara' => 'GUAM'],
            ['kodeNegara' => 'GW', 'namaNegara' => 'GUINEA-BISSAU'],
            ['kodeNegara' => 'GY', 'namaNegara' => 'GUYANA'],
            ['kodeNegara' => 'HK', 'namaNegara' => 'HONG KONG'],
            ['kodeNegara' => 'HM', 'namaNegara' => 'HEARD ISLAND AND MCDONALD ISLANDS'],
            ['kodeNegara' => 'HN', 'namaNegara' => 'HONDURAS'],
            ['kodeNegara' => 'HR', 'namaNegara' => 'CROATIA'],
            ['kodeNegara' => 'HT', 'namaNegara' => 'HAITI'],
            ['kodeNegara' => 'HU', 'namaNegara' => 'HUNGARY'],
            ['kodeNegara' => 'ID', 'namaNegara' => 'INDONESIA'],
            ['kodeNegara' => 'IE', 'namaNegara' => 'IRELAND'],
            ['kodeNegara' => 'IL', 'namaNegara' => 'ISRAEL'],
            ['kodeNegara' => 'IM', 'namaNegara' => 'Isle of Man'],
            ['kodeNegara' => 'IN', 'namaNegara' => 'INDIA'],
            ['kodeNegara' => 'IO', 'namaNegara' => 'BRITISH INDIAN OCEAN TERRITORY'],
            ['kodeNegara' => 'IQ', 'namaNegara' => 'IRAQ'],
            ['kodeNegara' => 'IR', 'namaNegara' => 'IRAN, ISLAMIC REPUBLIC OF'],
            ['kodeNegara' => 'IS', 'namaNegara' => 'ICELAND'],
            ['kodeNegara' => 'IT', 'namaNegara' => 'ITALY'],
            ['kodeNegara' => 'JE', 'namaNegara' => 'Jersey'],
            ['kodeNegara' => 'JM', 'namaNegara' => 'JAMAICA'],
            ['kodeNegara' => 'JO', 'namaNegara' => 'JORDAN'],
            ['kodeNegara' => 'JP', 'namaNegara' => 'JAPAN'],
            ['kodeNegara' => 'KE', 'namaNegara' => 'KENYA'],
            ['kodeNegara' => 'KG', 'namaNegara' => 'KYRGYZSTAN'],
            ['kodeNegara' => 'KH', 'namaNegara' => 'CAMBODIA'],
            ['kodeNegara' => 'KI', 'namaNegara' => 'KIRIBATI'],
            ['kodeNegara' => 'KM', 'namaNegara' => 'COMOROS'],
            ['kodeNegara' => 'KN', 'namaNegara' => 'SAINT KITTS AND NEVIS'],
            ['kodeNegara' => 'KP', 'namaNegara' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF'],
            ['kodeNegara' => 'KR', 'namaNegara' => 'KOREA, REPUBLIC OF'],
            ['kodeNegara' => 'KW', 'namaNegara' => 'KUWAIT'],
            ['kodeNegara' => 'KY', 'namaNegara' => 'CAYMAN ISLANDS'],
            ['kodeNegara' => 'KZ', 'namaNegara' => 'KAZAKSTAN'],
            ['kodeNegara' => 'LA', 'namaNegara' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC'],
            ['kodeNegara' => 'LB', 'namaNegara' => 'LEBANON'],
            ['kodeNegara' => 'LC', 'namaNegara' => 'SAINT LUCIA'],
            ['kodeNegara' => 'LI', 'namaNegara' => 'LIECHTENSTEIN'],
            ['kodeNegara' => 'LK', 'namaNegara' => 'SRI LANKA'],
            ['kodeNegara' => 'LR', 'namaNegara' => 'LIBERIA'],
            ['kodeNegara' => 'LS', 'namaNegara' => 'LESOTHO'],
            ['kodeNegara' => 'LT', 'namaNegara' => 'LITHUANIA'],
            ['kodeNegara' => 'LU', 'namaNegara' => 'LUXEMBOURG'],
            ['kodeNegara' => 'LV', 'namaNegara' => 'LATVIA'],
            ['kodeNegara' => 'LY', 'namaNegara' => 'LIBYAN ARAB JAMAHIRIYA'],
            ['kodeNegara' => 'MA', 'namaNegara' => 'MOROCCO'],
            ['kodeNegara' => 'MC', 'namaNegara' => 'MONACO'],
            ['kodeNegara' => 'MD', 'namaNegara' => 'MOLDOVA, REPUBLIC OF'],
            ['kodeNegara' => 'ME', 'namaNegara' => 'Montenegro'],
            ['kodeNegara' => 'MF', 'namaNegara' => 'Saint Martin (French Part)'],
            ['kodeNegara' => 'MG', 'namaNegara' => 'MADAGASCAR'],
            ['kodeNegara' => 'MH', 'namaNegara' => 'MARSHALL ISLANDS'],
            ['kodeNegara' => 'MK', 'namaNegara' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC'],
            ['kodeNegara' => 'ML', 'namaNegara' => 'MALI'],
            ['kodeNegara' => 'MM', 'namaNegara' => 'MYANMAR'],
            ['kodeNegara' => 'MN', 'namaNegara' => 'MONGOLIA'],
            ['kodeNegara' => 'MO', 'namaNegara' => 'MACAU'],
            ['kodeNegara' => 'MP', 'namaNegara' => 'NORTHERN MARIANA ISLANDS'],
            ['kodeNegara' => 'MQ', 'namaNegara' => 'MARTINIQUE'],
            ['kodeNegara' => 'MR', 'namaNegara' => 'MAURITANIA'],
            ['kodeNegara' => 'MS', 'namaNegara' => 'MONTSERRAT'],
            ['kodeNegara' => 'MT', 'namaNegara' => 'MALTA'],
            ['kodeNegara' => 'MU', 'namaNegara' => 'MAURITIUS'],
            ['kodeNegara' => 'MV', 'namaNegara' => 'MALDIVES'],
            ['kodeNegara' => 'MW', 'namaNegara' => 'MALAWI'],
            ['kodeNegara' => 'MX', 'namaNegara' => 'MEXICO'],
            ['kodeNegara' => 'MY', 'namaNegara' => 'MALAYSIA'],
            ['kodeNegara' => 'MZ', 'namaNegara' => 'MOZAMBIQUE'],
            ['kodeNegara' => 'NA', 'namaNegara' => 'NAMIBIA'],
            ['kodeNegara' => 'NC', 'namaNegara' => 'NEW CALEDONIA'],
            ['kodeNegara' => 'NE', 'namaNegara' => 'NIGER'],
            ['kodeNegara' => 'NF', 'namaNegara' => 'NORFOLK ISLAND'],
            ['kodeNegara' => 'NG', 'namaNegara' => 'NIGERIA'],
            ['kodeNegara' => 'NI', 'namaNegara' => 'NICARAGUA'],
            ['kodeNegara' => 'NL', 'namaNegara' => 'NETHERLANDS'],
            ['kodeNegara' => 'NO', 'namaNegara' => 'NORWAY'],
            ['kodeNegara' => 'NP', 'namaNegara' => 'NEPAL'],
            ['kodeNegara' => 'NR', 'namaNegara' => 'NAURU'],
            ['kodeNegara' => 'NU', 'namaNegara' => 'NIUE'],
            ['kodeNegara' => 'NZ', 'namaNegara' => 'NEW ZEALAND'],
            ['kodeNegara' => 'OM', 'namaNegara' => 'OMAN'],
            ['kodeNegara' => 'PA', 'namaNegara' => 'PANAMA'],
            ['kodeNegara' => 'PE', 'namaNegara' => 'PERU'],
            ['kodeNegara' => 'PF', 'namaNegara' => 'FRENCH POLYNESIA'],
            ['kodeNegara' => 'PG', 'namaNegara' => 'PAPUA NEW GUINEA'],
            ['kodeNegara' => 'PH', 'namaNegara' => 'PHILIPPINES'],
            ['kodeNegara' => 'PK', 'namaNegara' => 'PAKISTAN'],
            ['kodeNegara' => 'PL', 'namaNegara' => 'POLAND'],
            ['kodeNegara' => 'PM', 'namaNegara' => 'SAINT PIERRE AND MIQUELON'],
            ['kodeNegara' => 'PN', 'namaNegara' => 'PITCAIRN'],
            ['kodeNegara' => 'PR', 'namaNegara' => 'PUERTO RICO'],
            ['kodeNegara' => 'PS', 'namaNegara' => 'PALESTINIAN TERRITORY, OCCUPIED'],
            ['kodeNegara' => 'PT', 'namaNegara' => 'PORTUGAL'],
            ['kodeNegara' => 'PW', 'namaNegara' => 'PALAU'],
            ['kodeNegara' => 'PY', 'namaNegara' => 'PARAGUAY'],
            ['kodeNegara' => 'QA', 'namaNegara' => 'QATAR'],
            ['kodeNegara' => 'RE', 'namaNegara' => 'REUNION'],
            ['kodeNegara' => 'RO', 'namaNegara' => 'ROMANIA'],
            ['kodeNegara' => 'RS', 'namaNegara' => 'SERBIA'],
            ['kodeNegara' => 'RU', 'namaNegara' => 'RUSSIAN FEDERATION'],
            ['kodeNegara' => 'RW', 'namaNegara' => 'RWANDA'],
            ['kodeNegara' => 'SA', 'namaNegara' => 'SAUDI ARABIA'],
            ['kodeNegara' => 'SB', 'namaNegara' => 'SOLOMON ISLANDS'],
            ['kodeNegara' => 'SC', 'namaNegara' => 'SEYCHELLES'],
            ['kodeNegara' => 'SD', 'namaNegara' => 'SUDAN'],
            ['kodeNegara' => 'SE', 'namaNegara' => 'SWEDEN'],
            ['kodeNegara' => 'SG', 'namaNegara' => 'SINGAPORE'],
            ['kodeNegara' => 'SH', 'namaNegara' => 'SAINT HELENA'],
            ['kodeNegara' => 'SI', 'namaNegara' => 'SLOVENIA'],
            ['kodeNegara' => 'SJ', 'namaNegara' => 'SVALBARD AND JAN MAYEN'],
            ['kodeNegara' => 'SK', 'namaNegara' => 'SLOVAKIA'],
            ['kodeNegara' => 'SL', 'namaNegara' => 'SIERRA LEONE'],
            ['kodeNegara' => 'SM', 'namaNegara' => 'SAN MARINO'],
            ['kodeNegara' => 'SN', 'namaNegara' => 'SENEGAL'],
            ['kodeNegara' => 'SO', 'namaNegara' => 'SOMALIA'],
            ['kodeNegara' => 'SR', 'namaNegara' => 'SURINAME'],
            ['kodeNegara' => 'SS', 'namaNegara' => 'South Sudan'],
            ['kodeNegara' => 'ST', 'namaNegara' => 'SAO TOME AND PRINCIPE'],
            ['kodeNegara' => 'SV', 'namaNegara' => 'EL SALVADOR'],
            ['kodeNegara' => 'SX', 'namaNegara' => 'Sint Maarten (Dutch Part)'],
            ['kodeNegara' => 'SY', 'namaNegara' => 'SYRIAN ARAB REPUBLIC'],
            ['kodeNegara' => 'SZ', 'namaNegara' => 'SWAZILAND'],
            ['kodeNegara' => 'TC', 'namaNegara' => 'TURKS AND CAICOS ISLANDS'],
            ['kodeNegara' => 'TD', 'namaNegara' => 'CHAD'],
            ['kodeNegara' => 'TF', 'namaNegara' => 'FRENCH SOUTHERN TERRITORIES'],
            ['kodeNegara' => 'TG', 'namaNegara' => 'TOGO'],
            ['kodeNegara' => 'TH', 'namaNegara' => 'THAILAND'],
            ['kodeNegara' => 'TJ', 'namaNegara' => 'TAJIKISTAN'],
            ['kodeNegara' => 'TK', 'namaNegara' => 'TOKELAU'],
            ['kodeNegara' => 'TL', 'namaNegara' => 'Timor-Leste'],
            ['kodeNegara' => 'TM', 'namaNegara' => 'TURKMENISTAN'],
            ['kodeNegara' => 'TN', 'namaNegara' => 'TUNISIA'],
            ['kodeNegara' => 'TO', 'namaNegara' => 'TONGA'],
            ['kodeNegara' => 'TP', 'namaNegara' => 'EAST TIMOR'],
            ['kodeNegara' => 'TR', 'namaNegara' => 'TURKEY'],
            ['kodeNegara' => 'TT', 'namaNegara' => 'TRINIDAD AND TOBAGO'],
            ['kodeNegara' => 'TV', 'namaNegara' => 'TUVALU'],
            ['kodeNegara' => 'TW', 'namaNegara' => 'TAIWAN, PROVINCE OF CHINA'],
            ['kodeNegara' => 'TZ', 'namaNegara' => 'TANZANIA, UNITED REPUBLIC OF'],
            ['kodeNegara' => 'UA', 'namaNegara' => 'UKRAINE'],
            ['kodeNegara' => 'UG', 'namaNegara' => 'UGANDA'],
            ['kodeNegara' => 'UM', 'namaNegara' => 'UNITED STATES MINOR OUTLYING ISLANDS'],
            ['kodeNegara' => 'US', 'namaNegara' => 'UNITED STATES'],
            ['kodeNegara' => 'UY', 'namaNegara' => 'URUGUAY'],
            ['kodeNegara' => 'UZ', 'namaNegara' => 'UZBEKISTAN'],
            ['kodeNegara' => 'VA', 'namaNegara' => 'HOLY SEE (VATICAN CITY STATE)'],
            ['kodeNegara' => 'VC', 'namaNegara' => 'SAINT VINCENT AND THE GRENADINES'],
            ['kodeNegara' => 'VE', 'namaNegara' => 'VENEZUELA'],
            ['kodeNegara' => 'VG', 'namaNegara' => 'VIRGIN ISLANDS, BRITISH'],
            ['kodeNegara' => 'VI', 'namaNegara' => 'VIRGIN ISLANDS, U.S.'],
            ['kodeNegara' => 'VN', 'namaNegara' => 'VIET NAM'],
            ['kodeNegara' => 'VU', 'namaNegara' => 'VANUATU'],
            ['kodeNegara' => 'WF', 'namaNegara' => 'WALLIS AND FUTUNA'],
            ['kodeNegara' => 'WS', 'namaNegara' => 'SAMOA'],
            ['kodeNegara' => 'XZ', 'namaNegara' => 'KOSOVO'],
            ['kodeNegara' => 'YE', 'namaNegara' => 'YEMEN'],
            ['kodeNegara' => 'YT', 'namaNegara' => 'MAYOTTE'],
            ['kodeNegara' => 'YU', 'namaNegara' => 'YUGOSLAVIA'],
            ['kodeNegara' => 'ZA', 'namaNegara' => 'SOUTH AFRICA'],
            ['kodeNegara' => 'ZM', 'namaNegara' => 'ZAMBIA'],
            ['kodeNegara' => 'ZW', 'namaNegara' => 'ZIMBABWE'],
        ];

        DB::table('negara')->insert($negara);
        }
    }

