<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PelabuhanSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $pelabuhan = [
            ['kodePelabuhan' => 'ID5AN', 'namaPelabuhan' => 'Bangkalan', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5BO', 'namaPelabuhan' => 'Bondowoso', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5BT', 'namaPelabuhan' => 'Batubantar', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5CI', 'namaPelabuhan' => 'Ciamis', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5GK', 'namaPelabuhan' => 'Gunung Kidul', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5LE', 'namaPelabuhan' => 'Lembang', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5MA', 'namaPelabuhan' => 'Majalengka', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5MT', 'namaPelabuhan' => 'Magetan', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5NG', 'namaPelabuhan' => 'Nganjuk', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5PE', 'namaPelabuhan' => 'Petamburan', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5PN', 'namaPelabuhan' => 'Pangandaran', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5PP', 'namaPelabuhan' => 'Pacitan', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5SA', 'namaPelabuhan' => 'Salemba', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5SP', 'namaPelabuhan' => 'Sampang', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5SS', 'namaPelabuhan' => 'Pamekasan', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5SU', 'namaPelabuhan' => 'Sumedang', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5TR', 'namaPelabuhan' => 'Trenggalek', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID5TU', 'namaPelabuhan' => 'Batu', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ID6DI', 'namaPelabuhan' => 'Wajo', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAAS', 'namaPelabuhan' => 'Apalapsili', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDABU', 'namaPelabuhan' => 'Atambua', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDADB', 'namaPelabuhan' => 'Adang Bay', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAEG', 'namaPelabuhan' => 'Aekgodang', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAGD', 'namaPelabuhan' => 'Anggi', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAHI', 'namaPelabuhan' => 'Amahai', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAJN', 'namaPelabuhan' => 'Arjuna, Java', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAJS', 'namaPelabuhan' => 'Arjasa', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAKE', 'namaPelabuhan' => 'Akeselaka', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAMA', 'namaPelabuhan' => 'Amamapare, Ij', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAMI', 'namaPelabuhan' => 'Mataram', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAMP', 'namaPelabuhan' => 'Ampenan, Bali', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDAMQ', 'namaPelabuhan' => 'Ambon, Molucas', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDANC', 'namaPelabuhan' => 'Ancol', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDANG', 'namaPelabuhan' => 'Angar', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDANK', 'namaPelabuhan' => 'Angke', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDBTH', 'namaPelabuhan' => 'Batam (ex Batu Besar)', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDBTM', 'namaPelabuhan' => 'Batam Island', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'IDBUR', 'namaPelabuhan' => 'Batu Ampar', 'namaNegara' => 'INDONESIA'],
            ['kodePelabuhan' => 'ADALV', 'namaPelabuhan' => 'ANDORRA LA VELLA', 'namaNegara' => 'ANDORRA'],
            ['kodePelabuhan' => 'AEAAN', 'namaPelabuhan' => 'AL AIN', 'namaNegara' => 'UNITED ARAB EMIRATES'],
            ['kodePelabuhan' => 'AEABU', 'namaPelabuhan' => 'ABU AL BUKHOOSH', 'namaNegara' => 'UNITED ARAB EMIRATES'],
            ['kodePelabuhan' => 'SGAYC', 'namaPelabuhan' => 'Pulau Ayer Chawan', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGBKM', 'namaPelabuhan' => 'Bukit Merah Estate', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGCCK', 'namaPelabuhan' => 'Choa Chu Kang', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGCHG', 'namaPelabuhan' => 'Changi', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGCLE', 'namaPelabuhan' => 'Clementi', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGJUR', 'namaPelabuhan' => 'Jurong/Singapore', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGKEP', 'namaPelabuhan' => 'Keppel Wharves', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGPAP', 'namaPelabuhan' => 'Pasir Panjang Wharves', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGPAR', 'namaPelabuhan' => 'Pasir Ris New Town', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGPNR', 'namaPelabuhan' => 'Pioneer', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGPPT', 'namaPelabuhan' => 'PASIR PANJANG Terminal', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGPUB', 'namaPelabuhan' => 'Pulau Bukom', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGQPG', 'namaPelabuhan' => 'Paya Lebar', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGSCT', 'namaPelabuhan' => 'Singapore Container Terminal', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGSEB', 'namaPelabuhan' => 'Pulau Sebarok', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGSEM', 'namaPelabuhan' => 'Sembawang Port', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGSIN', 'namaPelabuhan' => 'Singapore', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGSLT', 'namaPelabuhan' => 'Seletar', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTAM', 'namaPelabuhan' => 'Tampines', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTAY', 'namaPelabuhan' => 'Telok Ayer Basin', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTGA', 'namaPelabuhan' => 'Tengah', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTPG', 'namaPelabuhan' => 'Tanjong Pagar', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTPN', 'namaPelabuhan' => 'Tanjong Penjuru', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTPY', 'namaPelabuhan' => 'Toa Payoh', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGTUA', 'namaPelabuhan' => 'Tuas', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGWDL', 'namaPelabuhan' => 'Woodlands', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'SGWES', 'namaPelabuhan' => 'West Coast Town', 'namaNegara' => 'SINGAPORE'],
            ['kodePelabuhan' => 'MY2SF', 'namaPelabuhan' => 'Bandar Baru Bangi', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYABU', 'namaPelabuhan' => 'Abu', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYAIR', 'namaPelabuhan' => 'Air Itam/Penang', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYAKA', 'namaPelabuhan' => 'Long Akah', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYANG', 'namaPelabuhan' => 'Angsi', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYAOG', 'namaPelabuhan' => 'Alor Gajah', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYAOR', 'namaPelabuhan' => 'Alor Setar', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYAPG', 'namaPelabuhan' => 'Ampang', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYASQ', 'namaPelabuhan' => 'Teronoh', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAG', 'namaPelabuhan' => 'Bagan Datok', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAH', 'namaPelabuhan' => 'Bahau', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAI', 'namaPelabuhan' => 'Bangi', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAK', 'namaPelabuhan' => 'Batang Kali', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAL', 'namaPelabuhan' => 'Balakong', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAN', 'namaPelabuhan' => 'Banting', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAT', 'namaPelabuhan' => 'Batu Pahat', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBAU', 'namaPelabuhan' => 'Bau, Sarawak', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBBA', 'namaPelabuhan' => 'Batu Batu, Sabah', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBBE', 'namaPelabuhan' => 'Bukit Beruntung', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBBN', 'namaPelabuhan' => 'Bario', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBBS', 'namaPelabuhan' => 'Bandar Baru Selayang', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBCA', 'namaPelabuhan' => 'Batu Caves', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBDG', 'namaPelabuhan' => 'Bedong', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBDR', 'namaPelabuhan' => 'Bidor', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBDV', 'namaPelabuhan' => 'Bandau, Sabah', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBEA', 'namaPelabuhan' => 'Beaufort', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBEK', 'namaPelabuhan' => 'Bandar Enstek', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBEL', 'namaPelabuhan' => 'Beluran, Sabah', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBEN', 'namaPelabuhan' => 'Bentong', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBGG', 'namaPelabuhan' => 'Bunan Gega, Sarawak', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBGK', 'namaPelabuhan' => 'Bunga Kekwa', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBGR', 'namaPelabuhan' => 'Bunga Raya', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBGU', 'namaPelabuhan' => 'Bangau', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBIA', 'namaPelabuhan' => 'Biawak, Sarawak', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBKH', 'namaPelabuhan' => 'Bukit Kayu Hitam', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBKI', 'namaPelabuhan' => 'Kota Kinabalu, Sabah', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBKM', 'namaPelabuhan' => 'Ba Kelalan', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBKP', 'namaPelabuhan' => 'Bakapit', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBKR', 'namaPelabuhan' => 'Bukit Keteri', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBLE', 'namaPelabuhan' => 'Bayan Lepas', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBLG', 'namaPelabuhan' => 'Belaga, Sarawak', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBLI', 'namaPelabuhan' => 'Batu Lintang, Sarawak', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBMA', 'namaPelabuhan' => 'Bandar Maharani', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBMT', 'namaPelabuhan' => 'Bukit Mertajam', 'namaNegara' => 'MALAYSIA'],
            ['kodePelabuhan' => 'MYBNG', 'namaPelabuhan' => 'Binatang, Sarawak', 'namaNegara' => 'MALAYSIA'],
        ];

        DB::table('pelabuhan')->insert($pelabuhan);
        }
    }
