<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SatuanBarangSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $satuanBarang = [
            ['kodeSatuanBarang' => 6, 'namaSatuanBarang' => 'small spray'],
            ['kodeSatuanBarang' => 8, 'namaSatuanBarang' => 'heat lot'],
            ['kodeSatuanBarang' => 10, 'namaSatuanBarang' => 'group'],
            ['kodeSatuanBarang' => 13, 'namaSatuanBarang' => 'ration'],
            ['kodeSatuanBarang' => 14, 'namaSatuanBarang' => 'shot'],
            ['kodeSatuanBarang' => 15, 'namaSatuanBarang' => 'stick, military'],
            ['kodeSatuanBarang' => 16, 'namaSatuanBarang' => 'hundred fifteen kg drum'],
            ['kodeSatuanBarang' => 17, 'namaSatuanBarang' => 'hundred lb drum'],
            ['kodeSatuanBarang' => 18, 'namaSatuanBarang' => 'fiftyfive gallon (US) drum'],
            ['kodeSatuanBarang' => 19, 'namaSatuanBarang' => 'tank truck'],
            ['kodeSatuanBarang' => 20, 'namaSatuanBarang' => 'twenty foot container'],
            ['kodeSatuanBarang' => 21, 'namaSatuanBarang' => 'forty foot container'],
            ['kodeSatuanBarang' => 22, 'namaSatuanBarang' => 'decilitre per gram'],
            ['kodeSatuanBarang' => 24, 'namaSatuanBarang' => 'theoretical pound'],
            ['kodeSatuanBarang' => 26, 'namaSatuanBarang' => 'actual ton'],
            ['kodeSatuanBarang' => 28, 'namaSatuanBarang' => 'kilogram per square metre'],
            ['kodeSatuanBarang' => 29, 'namaSatuanBarang' => 'pound per thousand square foot'],
            ['kodeSatuanBarang' => 30, 'namaSatuanBarang' => 'horse power day per air dry metric ton'],
            ['kodeSatuanBarang' => 31, 'namaSatuanBarang' => 'catch weight'],
            ['kodeSatuanBarang' => 32, 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => 33, 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => 34, 'namaSatuanBarang' => 'kilopascal per millimetre'],
            ['kodeSatuanBarang' => 35, 'namaSatuanBarang' => 'millilitre per square centimetre second'],
            ['kodeSatuanBarang' => 36, 'namaSatuanBarang' => 'cubic foot per minute per square foot'],
            ['kodeSatuanBarang' => 38, 'namaSatuanBarang' => 'ounce per square foot per 0,01inch'],
            ['kodeSatuanBarang' => 40, 'namaSatuanBarang' => 'millilitre per second'],
            ['kodeSatuanBarang' => 43, 'namaSatuanBarang' => 'super bulk bag'],
            ['kodeSatuanBarang' => 44, 'namaSatuanBarang' => 'fivehundred kg bulk bag'],
            ['kodeSatuanBarang' => 46, 'namaSatuanBarang' => 'fifty lb bulk bag'],
            ['kodeSatuanBarang' => 47, 'namaSatuanBarang' => 'fifty lb bag'],
            ['kodeSatuanBarang' => 48, 'namaSatuanBarang' => 'bulk car load'],
            ['kodeSatuanBarang' => 53, 'namaSatuanBarang' => 'theoretical kilogram'],
            ['kodeSatuanBarang' => 54, 'namaSatuanBarang' => 'theoretical tonne'],
            ['kodeSatuanBarang' => 57, 'namaSatuanBarang' => 'mesh'],
            ['kodeSatuanBarang' => 58, 'namaSatuanBarang' => 'net kilogram'],
            ['kodeSatuanBarang' => 60, 'namaSatuanBarang' => 'percent weight'],
            ['kodeSatuanBarang' => 61, 'namaSatuanBarang' => 'part per billion (US)'],
            ['kodeSatuanBarang' => 62, 'namaSatuanBarang' => 'percent per 1000 hour'],
            ['kodeSatuanBarang' => 63, 'namaSatuanBarang' => 'failure rate in time'],
            ['kodeSatuanBarang' => 64, 'namaSatuanBarang' => 'pound per square inch, gauge'],
            ['kodeSatuanBarang' => 66, 'namaSatuanBarang' => 'oersted'],
            ['kodeSatuanBarang' => 71, 'namaSatuanBarang' => 'volt ampere per pound'],
            ['kodeSatuanBarang' => 72, 'namaSatuanBarang' => 'watt per pound'],
            ['kodeSatuanBarang' => 73, 'namaSatuanBarang' => 'ampere tum per centimetre'],
            ['kodeSatuanBarang' => 78, 'namaSatuanBarang' => 'kilogauss'],
            ['kodeSatuanBarang' => 84, 'namaSatuanBarang' => 'kilopound-force per square inch'],
            ['kodeSatuanBarang' => 85, 'namaSatuanBarang' => 'foot pound-force'],
            ['kodeSatuanBarang' => 89, 'namaSatuanBarang' => 'poise'],
            ['kodeSatuanBarang' => 92, 'namaSatuanBarang' => 'calorie per cubic centimetre'],
            ['kodeSatuanBarang' => 93, 'namaSatuanBarang' => 'calorie per gram'],
            ['kodeSatuanBarang' => 94, 'namaSatuanBarang' => 'curl unit'],
            ['kodeSatuanBarang' => 96, 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => 97, 'namaSatuanBarang' => 'ten kg drum'],
            ['kodeSatuanBarang' => 98, 'namaSatuanBarang' => 'fifteen kg drum'],
            ['kodeSatuanBarang' => '1C', 'namaSatuanBarang' => 'locomotive count'],
            ['kodeSatuanBarang' => '1F', 'namaSatuanBarang' => 'train mile'],
            ['kodeSatuanBarang' => '1I', 'namaSatuanBarang' => 'fixed rate'],
            ['kodeSatuanBarang' => '1L', 'namaSatuanBarang' => 'total car count'],
            ['kodeSatuanBarang' => '1M', 'namaSatuanBarang' => 'total train count'],
            ['kodeSatuanBarang' => '1X', 'namaSatuanBarang' => 'car count'],
            ['kodeSatuanBarang' => '1Y', 'namaSatuanBarang' => 'car mile'],
            ['kodeSatuanBarang' => '2A', 'namaSatuanBarang' => 'twenty thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '2B', 'namaSatuanBarang' => 'barrel, dry (US)'],
            ['kodeSatuanBarang' => '2C', 'namaSatuanBarang' => 'barrel, liquid (US)'],
            ['kodeSatuanBarang' => '2G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '2H', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '2I', 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => '2J', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '2K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '2L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '2M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '2N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '2Q', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '2R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '2U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '2X', 'namaSatuanBarang' => 'ton mile'],
            ['kodeSatuanBarang' => '2Y', 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => '2Z', 'namaSatuanBarang' => 'megajoule per cubic metre'],
            ['kodeSatuanBarang' => '4G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '4H', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '4K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '4L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '4M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '4N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '4P', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '4R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '4U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '5D', 'namaSatuanBarang' => 'barrel, liquid (US)'],
            ['kodeSatuanBarang' => '5E', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '5F', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '5K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '5L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '5M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '5N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '5P', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '5R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '5U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '7G', 'namaSatuanBarang' => 'microcurie'],
            ["kodeSatuanBarang" => "N79", "namaSatuanBarang" => "kelvin per pascal"],
            ["kodeSatuanBarang" => "N81", "namaSatuanBarang" => "kilowatt per metre kelvin"],
            ["kodeSatuanBarang" => "N82", "namaSatuanBarang" => "kilowatt per metre degree Celsius"],
            ["kodeSatuanBarang" => "N83", "namaSatuanBarang" => "metre per degree Celcius metre"],
            ["kodeSatuanBarang" => "N90", "namaSatuanBarang" => "kilofarad"],
            ["kodeSatuanBarang" => "N92", "namaSatuanBarang" => "picosiemens"],
            ["kodeSatuanBarang" => "N97", "namaSatuanBarang" => "gilbert"],
            ["kodeSatuanBarang" => "N98", "namaSatuanBarang" => "volt per pascal"],
            ["kodeSatuanBarang" => "N99", "namaSatuanBarang" => "picovolt"],
            ["kodeSatuanBarang" => "NA", "namaSatuanBarang" => "milligram per kilogram"],
            ["kodeSatuanBarang" => "NAD", "namaSatuanBarang" => "Namibia Dollar"],
            ["kodeSatuanBarang" => "NAR", "namaSatuanBarang" => "Number of articles"],
            ["kodeSatuanBarang" => "NB", "namaSatuanBarang" => "barge"],
            ["kodeSatuanBarang" => "NBB", "namaSatuanBarang" => "Number bobbins"],
            ["kodeSatuanBarang" => "NCL", "namaSatuanBarang" => "number of cells"],
            ["kodeSatuanBarang" => "NE", "namaSatuanBarang" => "net litre"],
            ["kodeSatuanBarang" => "NEW", "namaSatuanBarang" => "Newton"],
            ["kodeSatuanBarang" => "NG", "namaSatuanBarang" => "net gallon (us)"],
            ["kodeSatuanBarang" => "NGN", "namaSatuanBarang" => "Nigeria Naira"],
            ["kodeSatuanBarang" => "NH", "namaSatuanBarang" => "message hour"],
            ["kodeSatuanBarang" => "NI", "namaSatuanBarang" => "net imperial gallon"],
            ["kodeSatuanBarang" => "NIL", "namaSatuanBarang" => "nil"],
            ["kodeSatuanBarang" => "NIO", "namaSatuanBarang" => "Nicaragua Cordoba"],
            ["kodeSatuanBarang" => "NJ", "namaSatuanBarang" => "number of screens"],
            ["kodeSatuanBarang" => "NMB", "namaSatuanBarang" => "Number"],
            ["kodeSatuanBarang" => "NMI", "namaSatuanBarang" => "Nautical mile (1852 m)"],
            ["kodeSatuanBarang" => "NMP", "namaSatuanBarang" => "Number of packs"],
            ["kodeSatuanBarang" => "NOK", "namaSatuanBarang" => "Norway Krone"],
            ["kodeSatuanBarang" => "NPL", "namaSatuanBarang" => "Number of parcels"],
            ["kodeSatuanBarang" => "NPR", "namaSatuanBarang" => "number of pairs"],
            ["kodeSatuanBarang" => "NPT", "namaSatuanBarang" => "Number of parts"],
            ["kodeSatuanBarang" => "NQ", "namaSatuanBarang" => "mho"],
            ["kodeSatuanBarang" => "NR", "namaSatuanBarang" => "micromho"],
            ["kodeSatuanBarang" => "NRL", "namaSatuanBarang" => "Number of rolls"],
            ["kodeSatuanBarang" => "NT", "namaSatuanBarang" => "net ton"],
            ["kodeSatuanBarang" => "NTT", "namaSatuanBarang" => "Net (regirter) ton"],
            ["kodeSatuanBarang" => "NU", "namaSatuanBarang" => "newton metre"],
            ["kodeSatuanBarang" => "NV", "namaSatuanBarang" => "vehicle"],
            ["kodeSatuanBarang" => "NX", "namaSatuanBarang" => "part per thousand"],
            ["kodeSatuanBarang" => "NY", "namaSatuanBarang" => "pound per air dry metric ton"],
            ["kodeSatuanBarang" => "NZD", "namaSatuanBarang" => "New Zealand Dollar"],
            ["kodeSatuanBarang" => "OA", "namaSatuanBarang" => "panel"],
            ["kodeSatuanBarang" => "ODE", "namaSatuanBarang" => "ozone depletion equivalent"],
            ["kodeSatuanBarang" => "ODG", "namaSatuanBarang" => "ODS Grams"],
            ["kodeSatuanBarang" => "ODK", "namaSatuanBarang" => "ODS Kilograms"],
            ["kodeSatuanBarang" => "ODM", "namaSatuanBarang" => "ODS Milligrams"],
            ["kodeSatuanBarang" => "OHM", "namaSatuanBarang" => "Ohm"],
            ["kodeSatuanBarang" => "ON", "namaSatuanBarang" => "ounce per square yard"],
            ["kodeSatuanBarang" => "ONZ", "namaSatuanBarang" => "Ounce GB,US (28,349523 g)"],
            ["kodeSatuanBarang" => "OP", "namaSatuanBarang" => "two pack"],
            ["kodeSatuanBarang" => "OPM", "namaSatuanBarang" => "oscillations per minute"],
            ["kodeSatuanBarang" => "OT", "namaSatuanBarang" => "overtime hour"],
            ["kodeSatuanBarang" => "OZ", "namaSatuanBarang" => "ounce av"],
            ["kodeSatuanBarang" => "OZA", "namaSatuanBarang" => "Fluid ounce (29,5735 cm3)"],
            ["kodeSatuanBarang" => "OZI", "namaSatuanBarang" => "Fluid ounce (29,5735 cm3)"],
            ["kodeSatuanBarang" => "P0", "namaSatuanBarang" => "page - electronic"],
            ["kodeSatuanBarang" => "P1", "namaSatuanBarang" => "percent"],
            ["kodeSatuanBarang" => "P10", "namaSatuanBarang" => "coulomb per metre"],
            ["kodeSatuanBarang" => "P11", "namaSatuanBarang" => "kiloweber"],
            ["kodeSatuanBarang" => "P13", "namaSatuanBarang" => "kilotesla"],
            ["kodeSatuanBarang" => "P15", "namaSatuanBarang" => "joule per minute"],
            ["kodeSatuanBarang" => "P16", "namaSatuanBarang" => "joule per hour"],
            ["kodeSatuanBarang" => "P17", "namaSatuanBarang" => "joule per day"],
            ["kodeSatuanBarang" => "P18", "namaSatuanBarang" => "kilojoule per second"],
            ["kodeSatuanBarang" => "P19", "namaSatuanBarang" => "kilojoule per minute"],
            ["kodeSatuanBarang" => "P2", "namaSatuanBarang" => "pound per foot"],
            ["kodeSatuanBarang" => "P20", "namaSatuanBarang" => "kilojoule per hour"],
            ["kodeSatuanBarang" => "P21", "namaSatuanBarang" => "kilojoule per day"],
            ["kodeSatuanBarang" => "P22", "namaSatuanBarang" => "nanoohm"],
            ["kodeSatuanBarang" => "P24", "namaSatuanBarang" => "kilohenry"],
            ["kodeSatuanBarang" => "P25", "namaSatuanBarang" => "lumen per square foot"],
            ["kodeSatuanBarang" => "P26", "namaSatuanBarang" => "phot"],
            ["kodeSatuanBarang" => "P27", "namaSatuanBarang" => "footcandle"],
            ["kodeSatuanBarang" => "P28", "namaSatuanBarang" => "candela per square inch"],
            ["kodeSatuanBarang" => "P29", "namaSatuanBarang" => "footlambert"],
            ["kodeSatuanBarang" => "P3", "namaSatuanBarang" => "three pack"],
            ["kodeSatuanBarang" => "P32", "namaSatuanBarang" => "candela per square foot"],
            ["kodeSatuanBarang" => "P33", "namaSatuanBarang" => "kilocandela"],
            ["kodeSatuanBarang" => "P34", "namaSatuanBarang" => "millicandela"],
            ["kodeSatuanBarang" => "P39", "namaSatuanBarang" => "calorie (thermochemical) per square centimetre"],
            ["kodeSatuanBarang" => "P4", "namaSatuanBarang" => "four pack"],
            ["kodeSatuanBarang" => "P40", "namaSatuanBarang" => "langley"],
            ["kodeSatuanBarang" => "P42", "namaSatuanBarang" => "pascal squared second"],
            ["kodeSatuanBarang" => "P43", "namaSatuanBarang" => "bel per metre"],
            ["kodeSatuanBarang" => "P44", "namaSatuanBarang" => "pound mole"],
            ["kodeSatuanBarang" => "P45", "namaSatuanBarang" => "pound mole per second"],
            ["kodeSatuanBarang" => "P46", "namaSatuanBarang" => "pound mole per minute"],
            ["kodeSatuanBarang" => "P49", "namaSatuanBarang" => "newton square metre per ampere"],
            ["kodeSatuanBarang" => "P50", "namaSatuanBarang" => "weber metre"],
            ["kodeSatuanBarang" => "P53", "namaSatuanBarang" => "unit pole"],
            ["kodeSatuanBarang" => "P54", "namaSatuanBarang" => "milligray per second"],
            ["kodeSatuanBarang" => "P55", "namaSatuanBarang" => "microgray per second"],
            ["kodeSatuanBarang" => "P56", "namaSatuanBarang" => "nanogray per second"],
            ["kodeSatuanBarang" => "P59", "namaSatuanBarang" => "microgray per minute"],
            ["kodeSatuanBarang" => "P6", "namaSatuanBarang" => "six pack"],
            ["kodeSatuanBarang" => "P60", "namaSatuanBarang" => "nanogray per minute"],
            ["kodeSatuanBarang" => "P61", "namaSatuanBarang" => "gray per hour"],
            ["kodeSatuanBarang" => "P62", "namaSatuanBarang" => "milligray per hour"],
            ["kodeSatuanBarang" => "P64", "namaSatuanBarang" => "nanogray per hour"],
            ["kodeSatuanBarang" => "P65", "namaSatuanBarang" => "sievert per second"],
            ["kodeSatuanBarang" => "P66", "namaSatuanBarang" => "millisievert per second"],
            ["kodeSatuanBarang" => "P67", "namaSatuanBarang" => "microsievert per second"],
            ["kodeSatuanBarang" => "RH", "namaSatuanBarang" => "running or operating hour"],
            ["kodeSatuanBarang" => "RK", "namaSatuanBarang" => "roll metric measure"],
            ["kodeSatuanBarang" => "RL", "namaSatuanBarang" => "reel"],
            ["kodeSatuanBarang" => "RM", "namaSatuanBarang" => "ream"],
            ["kodeSatuanBarang" => "RO", "namaSatuanBarang" => "roll"],
            ["kodeSatuanBarang" => "ROM", "namaSatuanBarang" => "room"],
            ["kodeSatuanBarang" => "RON", "namaSatuanBarang" => "Romania Leu"],
            ["kodeSatuanBarang" => "RP", "namaSatuanBarang" => "pound per ream"],
            ["kodeSatuanBarang" => "RPM", "namaSatuanBarang" => "Revolution per minute"],
            ["kodeSatuanBarang" => "RPS", "namaSatuanBarang" => "Revolution per second"],
            ["kodeSatuanBarang" => "RS", "namaSatuanBarang" => "reset"],
            ["kodeSatuanBarang" => "RT", "namaSatuanBarang" => "revenue ton mile"],
            ["kodeSatuanBarang" => "RUB", "namaSatuanBarang" => "Russia Ruble"],
            ["kodeSatuanBarang" => "RWF", "namaSatuanBarang" => "Rwanda Franc"],
            ["kodeSatuanBarang" => "S3", "namaSatuanBarang" => "square foot per second"],
            ["kodeSatuanBarang" => "S4", "namaSatuanBarang" => "square metre per second"],
            ["kodeSatuanBarang" => "S6", "namaSatuanBarang" => "session"],
            ["kodeSatuanBarang" => "S7", "namaSatuanBarang" => "storage unit"],
            ["kodeSatuanBarang" => "S8", "namaSatuanBarang" => "standard advertising unit"],
            ["kodeSatuanBarang" => "SA", "namaSatuanBarang" => "sack"],
            ["kodeSatuanBarang" => "SAN", "namaSatuanBarang" => "Half year (six Months)"],
            ["kodeSatuanBarang" => "SBD", "namaSatuanBarang" => "Solomon Islands Dollar"],
            ["kodeSatuanBarang" => "SCO", "namaSatuanBarang" => "Score"],
            ["kodeSatuanBarang" => "SCR", "namaSatuanBarang" => "Scruple GP,US (1,295982 g)"],
            ["kodeSatuanBarang" => "SD", "namaSatuanBarang" => "solid pound"],
            ["kodeSatuanBarang" => "SDG", "namaSatuanBarang" => "Sudan Pound"],
            ["kodeSatuanBarang" => "SE", "namaSatuanBarang" => "section"],
            ["kodeSatuanBarang" => "SEC", "namaSatuanBarang" => "Second"],
            ["kodeSatuanBarang" => "SEK", "namaSatuanBarang" => "Sweden Krona"],
            ["kodeSatuanBarang" => "SET", "namaSatuanBarang" => "Set"],
            ["kodeSatuanBarang" => "SG", "namaSatuanBarang" => "segment"],
            ["kodeSatuanBarang" => "SGD", "namaSatuanBarang" => "Singapore Dollar"],
            ["kodeSatuanBarang" => "SHP", "namaSatuanBarang" => "Saint Helena Pound"],
            ["kodeSatuanBarang" => "SHT", "namaSatuanBarang" => "Shipping ton"],
            ["kodeSatuanBarang" => "SIE", "namaSatuanBarang" => "Siemens"],
            ["kodeSatuanBarang" => "SK", "namaSatuanBarang" => "split tank truck"],
            ["kodeSatuanBarang" => "SL", "namaSatuanBarang" => "slipsheet"],
            ["kodeSatuanBarang" => "SLL", "namaSatuanBarang" => "Sierra Leone Leone"],
            ["kodeSatuanBarang" => "SM3", "namaSatuanBarang" => "Standard cubic metre"],
            ["kodeSatuanBarang" => "SMI", "namaSatuanBarang" => "Statute mile (1609.344 m)"],
            ["kodeSatuanBarang" => "SN", "namaSatuanBarang" => "square rod"],
            ["kodeSatuanBarang" => "SOS", "namaSatuanBarang" => "Somalia Shilling"],
            ["kodeSatuanBarang" => "SPL", "namaSatuanBarang" => "Seborga Luigino"],
            ["kodeSatuanBarang" => "SQ", "namaSatuanBarang" => "square"],
            ["kodeSatuanBarang" => "SQR", "namaSatuanBarang" => "square, roofing"],
            ["kodeSatuanBarang" => "SRD", "namaSatuanBarang" => "Suriname Dollar"],
            ["kodeSatuanBarang" => "SS", "namaSatuanBarang" => "sheet metric measure"],
            ["kodeSatuanBarang" => "ST", "namaSatuanBarang" => "sheet"],
            ["kodeSatuanBarang" => "STC", "namaSatuanBarang" => "stick"],
            ["kodeSatuanBarang" => "STI", "namaSatuanBarang" => "Stone GB (6,350293 kg)"],
            ["kodeSatuanBarang" => "STK", "namaSatuanBarang" => "stick, cigarette"],
            ["kodeSatuanBarang" => "STL", "namaSatuanBarang" => "standard litre"],
            ["kodeSatuanBarang" => "STN", "namaSatuanBarang" => "Short ton GB, US 2/ (0,90718474 t)"],
            ["kodeSatuanBarang" => "STW", "namaSatuanBarang" => "straw"],
            ["kodeSatuanBarang" => "SW", "namaSatuanBarang" => "skein"],
            ["kodeSatuanBarang" => "SX", "namaSatuanBarang" => "shipment"],
            ["kodeSatuanBarang" => "SZL", "namaSatuanBarang" => "Swaziland Lilangeni"],
            ["kodeSatuanBarang" => "T0", "namaSatuanBarang" => "telecommunication line in service"],
            ["kodeSatuanBarang" => "T1", "namaSatuanBarang" => "thousand pound gross"],
            ["kodeSatuanBarang" => "K15", "namaSatuanBarang" => "foot pound-force per hour"],
            ["kodeSatuanBarang" => "K16", "namaSatuanBarang" => "foot pound-force per minute"],
            ["kodeSatuanBarang" => "K17", "namaSatuanBarang" => "foot per psi"],
            ["kodeSatuanBarang" => "K19", "namaSatuanBarang" => "foot per second psi"],
            ["kodeSatuanBarang" => "K2", "namaSatuanBarang" => "kilovolt ampere reactive demand"],
            ["kodeSatuanBarang" => "K20", "namaSatuanBarang" => "reciprocal cubic foot"],
            ["kodeSatuanBarang" => "K21", "namaSatuanBarang" => "cubic foot per degree Fahrenheit"],
            ["kodeSatuanBarang" => "K22", "namaSatuanBarang" => "cubic foot per day"],
            ["kodeSatuanBarang" => "K23", "namaSatuanBarang" => "cubic foot per psi"],
            ["kodeSatuanBarang" => "K25", "namaSatuanBarang" => "foot of mercury"],
            ["kodeSatuanBarang" => "K26", "namaSatuanBarang" => "gallon (UK) per day"],
            ["kodeSatuanBarang" => "K27", "namaSatuanBarang" => "gallon (UK) per hour"],
            ["kodeSatuanBarang" => "K28", "namaSatuanBarang" => "gallon (UK) per second"],
            ["kodeSatuanBarang" => "K3", "namaSatuanBarang" => "kilovolt ampere reactive hour"],
            ["kodeSatuanBarang" => "K31", "namaSatuanBarang" => "gram-force per square centimetre"],
            ["kodeSatuanBarang" => "K32", "namaSatuanBarang" => "gill (UK) per day"],
            ["kodeSatuanBarang" => "K33", "namaSatuanBarang" => "gill (UK) per hour"],
            ["kodeSatuanBarang" => "K35", "namaSatuanBarang" => "gill (UK) per second"],
            ["kodeSatuanBarang" => "K37", "namaSatuanBarang" => "gill (US) per hour"],
            ["kodeSatuanBarang" => "K38", "namaSatuanBarang" => "gill (US) per minute"],
            ["kodeSatuanBarang" => "K39", "namaSatuanBarang" => "gill (US) per second"],
            ["kodeSatuanBarang" => "K41", "namaSatuanBarang" => "grain per gallon (US)"],
            ["kodeSatuanBarang" => "K42", "namaSatuanBarang" => "horsepower (boiler)"],
            ["kodeSatuanBarang" => "K43", "namaSatuanBarang" => "horsepower (electric)"],
            ["kodeSatuanBarang" => "K46", "namaSatuanBarang" => "inch per psi"],
            ["kodeSatuanBarang" => "K48", "namaSatuanBarang" => "inch per second psi"],
            ["kodeSatuanBarang" => "K49", "namaSatuanBarang" => "reciprocal cubic inch"],
            ["kodeSatuanBarang" => "K5", "namaSatuanBarang" => "kilovolt ampere (reactive)"],
            ["kodeSatuanBarang" => "K50", "namaSatuanBarang" => "kilobaud"],
            ["kodeSatuanBarang" => "K51", "namaSatuanBarang" => "kilocalorie (mean)"],
            ["kodeSatuanBarang" => "K52", "namaSatuanBarang" => "kilocalorie (IT) per hour metre degree Celsius"],
            ["kodeSatuanBarang" => "K53", "namaSatuanBarang" => "kilocalorie (thermochemical)"],
            ["kodeSatuanBarang" => "K54", "namaSatuanBarang" => "kilocalorie (thermochemical) per minute"],
            ["kodeSatuanBarang" => "K55", "namaSatuanBarang" => "kilocalorie (thermochemical) per second"],
            ["kodeSatuanBarang" => "K58", "namaSatuanBarang" => "kilomole per hour"],
            ["kodeSatuanBarang" => "K59", "namaSatuanBarang" => "kilomole per cubic metre kelvin"],
            ["kodeSatuanBarang" => "K6", "namaSatuanBarang" => "kilolitre"],
            ["kodeSatuanBarang" => "K60", "namaSatuanBarang" => "kilomole per cubic metre bar"],
            ["kodeSatuanBarang" => "K61", "namaSatuanBarang" => "kilomole per minute"],
            ["kodeSatuanBarang" => "K62", "namaSatuanBarang" => "litre per litre"],
            ["kodeSatuanBarang" => "K63", "namaSatuanBarang" => "reciprocal litre"],
            ["kodeSatuanBarang" => "K64", "namaSatuanBarang" => "pound (avoirdupois) per degree Fahrenheit"],
            ["kodeSatuanBarang" => "K65", "namaSatuanBarang" => "pound (avoirdupois) square foot"],
            ["kodeSatuanBarang" => "K67", "namaSatuanBarang" => "pound per foot hour"],
            ["kodeSatuanBarang" => "K68", "namaSatuanBarang" => "pound per foot second"],
            ["kodeSatuanBarang" => "K70", "namaSatuanBarang" => "pound (avoirdupois) per cubic foot psi"],
            ["kodeSatuanBarang" => "K71", "namaSatuanBarang" => "pound (avoirdupois) per gallon (UK)"],
            ["kodeSatuanBarang" => "K73", "namaSatuanBarang" => "pound (avoirdupois) per hour degree Fahrenheit"],
            ["kodeSatuanBarang" => "K74", "namaSatuanBarang" => "pound (avoirdupois) per hour psi"],
            ["kodeSatuanBarang" => "K75", "namaSatuanBarang" => "pound/avoirdupois per cubic inch degree Fahrenheit"],
            ["kodeSatuanBarang" => "K76", "namaSatuanBarang" => "pound (avoirdupois) per cubic inch psi"],
            ["kodeSatuanBarang" => "K77", "namaSatuanBarang" => "pound (avoirdupois) per psi"],
            ["kodeSatuanBarang" => "K78", "namaSatuanBarang" => "pound (avoirdupois) per minute"],
            ["kodeSatuanBarang" => "K79", "namaSatuanBarang" => "pound (avoirdupois) per minute degree Fahrenheit"],
            ["kodeSatuanBarang" => "K80", "namaSatuanBarang" => "pound (avoirdupois) per minute psi"],
            ["kodeSatuanBarang" => "K81", "namaSatuanBarang" => "pound (avoirdupois) per second"],
            ["kodeSatuanBarang" => "K83", "namaSatuanBarang" => "pound (avoirdupois) per second psi"],
            ["kodeSatuanBarang" => "K84", "namaSatuanBarang" => "pound per cubic yard"],
            ["kodeSatuanBarang" => "K85", "namaSatuanBarang" => "pound-force per square foot"],
            ["kodeSatuanBarang" => "K86", "namaSatuanBarang" => "pound-force per square inch degree Fahrenheit"],
            ["kodeSatuanBarang" => "K87", "namaSatuanBarang" => "psi cubic inch per second"],
            ["kodeSatuanBarang" => "K88", "namaSatuanBarang" => "psi litre per second"],
            ["kodeSatuanBarang" => "K89", "namaSatuanBarang" => "psi cubic metre per second"],
            ["kodeSatuanBarang" => "K90", "namaSatuanBarang" => "psi cubic yard per second"],
            ["kodeSatuanBarang" => "K92", "namaSatuanBarang" => "pound-force second per square inch"],
            ["kodeSatuanBarang" => "K93", "namaSatuanBarang" => "reciprocal psi"],
            ["kodeSatuanBarang" => "K95", "namaSatuanBarang" => "quart (UK liquid) per hour"],
            ["kodeSatuanBarang" => "K97", "namaSatuanBarang" => "quart (UK liquid) per second"],
            ["kodeSatuanBarang" => "K98", "namaSatuanBarang" => "quart (US liquid) per day"],
            ["kodeSatuanBarang" => "KA", "namaSatuanBarang" => "cake"],
            ["kodeSatuanBarang" => "KAT", "namaSatuanBarang" => "katal"],
            ["kodeSatuanBarang" => "KB", "namaSatuanBarang" => "kilocharacter"],
            ["kodeSatuanBarang" => "KBA", "namaSatuanBarang" => "Kilobar"],
            ["kodeSatuanBarang" => "KCC", "namaSatuanBarang" => "kilogram of choline chloride"],
            ["kodeSatuanBarang" => "KD", "namaSatuanBarang" => "kilogram decimal"],
            ["kodeSatuanBarang" => "KDW", "namaSatuanBarang" => "kilogram drained net weight"],
            ["kodeSatuanBarang" => "KEL", "namaSatuanBarang" => "Kelvin"],
            ["kodeSatuanBarang" => "KES", "namaSatuanBarang" => "Kenya Shilling"],
            ["kodeSatuanBarang" => "KF", "namaSatuanBarang" => "kilopacket"],
            ["kodeSatuanBarang" => "KGM", "namaSatuanBarang" => "Kilogram"],
            ["kodeSatuanBarang" => "KGS", "namaSatuanBarang" => "Kilogram Per Second"],
            ["kodeSatuanBarang" => "KHR", "namaSatuanBarang" => "Cambodia Riel"],
            ["kodeSatuanBarang" => "KI", "namaSatuanBarang" => "kilogram per millimetre width"],
            ["kodeSatuanBarang" => "KIC", "namaSatuanBarang" => "kilogram, including container"],
            ["kodeSatuanBarang" => "KIP", "namaSatuanBarang" => "kilogram, including inner packaging"],
            ["kodeSatuanBarang" => "KJO", "namaSatuanBarang" => "Kilojoule"],
            ["kodeSatuanBarang" => "KL", "namaSatuanBarang" => "kilogram per metre"],
            ["kodeSatuanBarang" => "KLK", "namaSatuanBarang" => "lactic dry material percentage"],
            ["kodeSatuanBarang" => "KMA", "namaSatuanBarang" => "kilogram of methylamine"],
            ["kodeSatuanBarang" => "KMF", "namaSatuanBarang" => "Comorian Franc"],
            ["kodeSatuanBarang" => "KMK", "namaSatuanBarang" => "Square kilometre"],
            ["kodeSatuanBarang" => "KMQ", "namaSatuanBarang" => "Kilogram per cubic meter"],
            ["kodeSatuanBarang" => "KNI", "namaSatuanBarang" => "Kilogram of nitrogen"],
            ["kodeSatuanBarang" => "KNM", "namaSatuanBarang" => "kilonewton per square metre"],
            ["kodeSatuanBarang" => "KNS", "namaSatuanBarang" => "Kilogram of named substance"],
            ["kodeSatuanBarang" => "KNT", "namaSatuanBarang" => "Knot ( 1 n mile oer hour"],
            ["kodeSatuanBarang" => "KO", "namaSatuanBarang" => "milliequivalence causticpotash per gram of product"],
            ["kodeSatuanBarang" => "KPA", "namaSatuanBarang" => "kilopascal"],
            ["kodeSatuanBarang" => "KPH", "namaSatuanBarang" => "Kilogram of potassium hydroxide (caustic potasn)"],
            ["kodeSatuanBarang" => "KPP", "namaSatuanBarang" => "Kgm of phosphorus pentoxide(phosphoric anhydride"],
            ["kodeSatuanBarang" => "KPW", "namaSatuanBarang" => "Korea (North) Won"],
            ["kodeSatuanBarang" => "KR", "namaSatuanBarang" => "kiloroentgen"],
            ["kodeSatuanBarang" => "KRW", "namaSatuanBarang" => "Korea (South) Won"],
            ["kodeSatuanBarang" => "KS", "namaSatuanBarang" => "thousand pound per square inch"],
            ["kodeSatuanBarang" => "KSD", "namaSatuanBarang" => "Kilogram of substance 90 per cent dry"],
            ["kodeSatuanBarang" => "KSH", "namaSatuanBarang" => "Kilogram of sodium hydyoxide (caustic soda)"],
            ["kodeSatuanBarang" => "KTM", "namaSatuanBarang" => "kilometre"],
            ["kodeSatuanBarang" => "KTN", "namaSatuanBarang" => "Kilotonne"],
            ["kodeSatuanBarang" => "KUR", "namaSatuanBarang" => "Kilogram of uranium"],
            ["kodeSatuanBarang" => "KVA", "namaSatuanBarang" => "Kilovolt - ampere"],
            ["kodeSatuanBarang" => "KVT", "namaSatuanBarang" => "kilovolt"],
            ["kodeSatuanBarang" => "KW", "namaSatuanBarang" => "kilogram per millimetre"],
            ["kodeSatuanBarang" => "KWD", "namaSatuanBarang" => "Kuwait Dinar"],
            ["kodeSatuanBarang" => "KWN", "namaSatuanBarang" => "Kilowatt hour per normalized cubic metre"],
            ["kodeSatuanBarang" => "KWO", "namaSatuanBarang" => "kilogram of tungsten trioxide"],
            ["kodeSatuanBarang" => "KWS", "namaSatuanBarang" => "Kilowatt hour per standard cubic metre"],
            ["kodeSatuanBarang" => "KWT", "namaSatuanBarang" => "Kilowatt"],
            ["kodeSatuanBarang" => "KX", "namaSatuanBarang" => "millilitre per kilogram"],
            ["kodeSatuanBarang" => "KYD", "namaSatuanBarang" => "Cayman Islands Dollar"],
            ["kodeSatuanBarang" => "KZT", "namaSatuanBarang" => "Kazakhstan Tenge"],
            ["kodeSatuanBarang" => "L13", "namaSatuanBarang" => "metre per second bar"],
            ["kodeSatuanBarang" => "L14", "namaSatuanBarang" => "square metre hour degree Celsius per kilocalorie"],
            ["kodeSatuanBarang" => "L15", "namaSatuanBarang" => "millipascal second per kelvin"],
            ["kodeSatuanBarang" => "L16", "namaSatuanBarang" => "millipascal second per bar"],
            ["kodeSatuanBarang" => "L17", "namaSatuanBarang" => "milligram per cubic metre kelvin"],
            ["kodeSatuanBarang" => "L18", "namaSatuanBarang" => "milligram per cubic metre bar"],
            ["kodeSatuanBarang" => "L19", "namaSatuanBarang" => "millilitre per litre"],
            ["kodeSatuanBarang" => "L2", "namaSatuanBarang" => "litre per minute"],
            ["kodeSatuanBarang" => "L23", "namaSatuanBarang" => "mole per hour"],
            ["kodeSatuanBarang" => "L25", "namaSatuanBarang" => "mole per kilogram bar"],
            ["kodeSatuanBarang" => "L26", "namaSatuanBarang" => "mole per litre kelvin"],
            ["kodeSatuanBarang" => "L27", "namaSatuanBarang" => "mole per litre bar"],
            ["kodeSatuanBarang" => "L31", "namaSatuanBarang" => "milliroentgen aequivalent men"],
            ["kodeSatuanBarang" => "L32", "namaSatuanBarang" => "nanogram per kilogram"],
            ["kodeSatuanBarang" => "L33", "namaSatuanBarang" => "ounce (avoirdupois) per day"],
            ["kodeSatuanBarang" => "L34", "namaSatuanBarang" => "ounce (avoirdupois) per hour"],
            ["kodeSatuanBarang" => "L35", "namaSatuanBarang" => "ounce (avoirdupois) per minute"],
            ["kodeSatuanBarang" => "L36", "namaSatuanBarang" => "ounce (avoirdupois) per second"],
            ["kodeSatuanBarang" => "L37", "namaSatuanBarang" => "ounce (avoirdupois) per gallon (UK)"],
            ["kodeSatuanBarang" => "L39", "namaSatuanBarang" => "ounce (avoirdupois) per cubic inch"],
            ["kodeSatuanBarang" => "L43", "namaSatuanBarang" => "peck (UK)"],
            ["kodeSatuanBarang" => "L45", "namaSatuanBarang" => "peck (UK) per hour"],
            ["kodeSatuanBarang" => "L46", "namaSatuanBarang" => "peck (UK) per minute"],
            ["kodeSatuanBarang" => "L47", "namaSatuanBarang" => "peck (UK) per second"],
            ["kodeSatuanBarang" => "L51", "namaSatuanBarang" => "peck (US dry) per second"],
            ["kodeSatuanBarang" => "L52", "namaSatuanBarang" => "psi per psi"],
            ["kodeSatuanBarang" => "L53", "namaSatuanBarang" => "pint (UK) per day"],
            ["kodeSatuanBarang" => "L54", "namaSatuanBarang" => "pint (UK) per hour"],
            ["kodeSatuanBarang" => "L55", "namaSatuanBarang" => "pint (UK) per minute"],
            ["kodeSatuanBarang" => "L58", "namaSatuanBarang" => "pint (US liquid) per hour"],
            ["kodeSatuanBarang" => "L60", "namaSatuanBarang" => "pint (US liquid) per second"],
            ["kodeSatuanBarang" => "L61", "namaSatuanBarang" => "pint (US dry)"],
            ["kodeSatuanBarang" => "L63", "namaSatuanBarang" => "slug per day"],
            ["kodeSatuanBarang" => "L64", "namaSatuanBarang" => "slug per foot second"],
            ["kodeSatuanBarang" => "L65", "namaSatuanBarang" => "slug per cubic foot"],
            ["kodeSatuanBarang" => "L66", "namaSatuanBarang" => "slug per hoursecond"],
            ["kodeSatuanBarang" => "L69", "namaSatuanBarang" => "tonne per kelvin"],
            ["kodeSatuanBarang" => "L72", "namaSatuanBarang" => "tonne per day kelvin"],
            ["kodeSatuanBarang" => "L73", "namaSatuanBarang" => "tonne per day bar"],
            ["kodeSatuanBarang" => "L74", "namaSatuanBarang" => "tonne per hour kelvin"],
            ["kodeSatuanBarang" => "L78", "namaSatuanBarang" => "tonne per minute"],
            ["kodeSatuanBarang" => "L81", "namaSatuanBarang" => "tonne per second"],
            ["kodeSatuanBarang" => "L82", "namaSatuanBarang" => "tonne per second kelvin"],
            ["kodeSatuanBarang" => "L83", "namaSatuanBarang" => "tonne per second bar"],
            ["kodeSatuanBarang" => "L84", "namaSatuanBarang" => "ton (UK shipping)"],
            ["kodeSatuanBarang" => "L85", "namaSatuanBarang" => "ton long per day"],
            ["kodeSatuanBarang" => "L87", "namaSatuanBarang" => "ton short per degree Fahrenheit"],
            ["kodeSatuanBarang" => "L88", "namaSatuanBarang" => "ton short per day"],
            ["kodeSatuanBarang" => "L89", "namaSatuanBarang" => "ton short per hour degree Fahrenheit"],
            ["kodeSatuanBarang" => "L92", "namaSatuanBarang" => "ton (UK long) per cubic yard"],
            ["kodeSatuanBarang" => "L94", "namaSatuanBarang" => "ton-force (US short)"],
            ["kodeSatuanBarang" => "L95", "namaSatuanBarang" => "common year"],
            ["kodeSatuanBarang" => "L96", "namaSatuanBarang" => "sidereal year"],
            ["kodeSatuanBarang" => "L99", "namaSatuanBarang" => "yard per psi"],
            ["kodeSatuanBarang" => "LA", "namaSatuanBarang" => "pound per cubic inch"],
            ["kodeSatuanBarang" => "LAC", "namaSatuanBarang" => "lactose excess percentage"],
            ["kodeSatuanBarang" => "LAK", "namaSatuanBarang" => "Laos Kip"],
            ["kodeSatuanBarang" => "LBP", "namaSatuanBarang" => "Lebanon Pound"],
            ["kodeSatuanBarang" => "LBR", "namaSatuanBarang" => "Pound GB,US (0,45359237 kg)"],
            ["kodeSatuanBarang" => "LC", "namaSatuanBarang" => "linear centimetre"],
            ["kodeSatuanBarang" => "LD", "namaSatuanBarang" => "litre per day"],
            ["kodeSatuanBarang" => "LEF", "namaSatuanBarang" => "leaf"],
            ["kodeSatuanBarang" => "LF", "namaSatuanBarang" => "linear foot"],
            ["kodeSatuanBarang" => "LH", "namaSatuanBarang" => "labour hour"],
            ["kodeSatuanBarang" => "LJ", "namaSatuanBarang" => "large spray"],
            ["kodeSatuanBarang" => "LK", "namaSatuanBarang" => "link"],
            ["kodeSatuanBarang" => "LKR", "namaSatuanBarang" => "Sri Lanka Rupee"],
            ["kodeSatuanBarang" => "LM", "namaSatuanBarang" => "linear metre"],
            ["kodeSatuanBarang" => "LN", "namaSatuanBarang" => "length"],
            ["kodeSatuanBarang" => "LO", "namaSatuanBarang" => "lot [unit of procurement]"],
            ["kodeSatuanBarang" => "LPA", "namaSatuanBarang" => "Litre of pure alcohol"],
            ["kodeSatuanBarang" => "LS", "namaSatuanBarang" => "lump sum"],
            ["kodeSatuanBarang" => "LSL", "namaSatuanBarang" => "Lesotho Loti"],
            ["kodeSatuanBarang" => "LUB", "namaSatuanBarang" => "metric ton, lubricating oil"],
            ["kodeSatuanBarang" => "LUM", "namaSatuanBarang" => "Lumen"],
            ["kodeSatuanBarang" => "LX", "namaSatuanBarang" => "linear yard per pound"],
            ["kodeSatuanBarang" => "LY", "namaSatuanBarang" => "linear yard"],
            ["kodeSatuanBarang" => "LYD", "namaSatuanBarang" => "Libya Dinar"],
            ["kodeSatuanBarang" => "M0", "namaSatuanBarang" => "magnetic tape"],
            ["kodeSatuanBarang" => "M1", "namaSatuanBarang" => "milligram per litre"],
            ["kodeSatuanBarang" => "M11", "namaSatuanBarang" => "cubic yard per degree Fahrenheit"],
            ["kodeSatuanBarang" => "M13", "namaSatuanBarang" => "cubic yard per hour"],
            ["kodeSatuanBarang" => "M15", "namaSatuanBarang" => "cubic yard per minute"],
            ["kodeSatuanBarang" => "M16", "namaSatuanBarang" => "cubic yard per second"],
            ["kodeSatuanBarang" => "M17", "namaSatuanBarang" => "kilohertz metre"],
            ["kodeSatuanBarang" => "M19", "namaSatuanBarang" => "Beaufort"],
            ["kodeSatuanBarang" => "M21", "namaSatuanBarang" => "reciprocal kilovolt - ampere hour"],
            ["kodeSatuanBarang" => "M22", "namaSatuanBarang" => "millilitre per square centimetre minute"],
            ["kodeSatuanBarang" => "M23", "namaSatuanBarang" => "newton per centimetre"],
            ["kodeSatuanBarang" => "M25", "namaSatuanBarang" => "percent per degree Celsius"],
            ["kodeSatuanBarang" => "M26", "namaSatuanBarang" => "gigaohm per metre"],
            ["kodeSatuanBarang" => "M30", "namaSatuanBarang" => "reciprocalvolt - ampere second"],
["kodeSatuanBarang" => "M32", "namaSatuanBarang" => "pascal second per litre"],
    ["kodeSatuanBarang" => "M33", "namaSatuanBarang" => "millimole per litre"],
    ["kodeSatuanBarang" => "M34", "namaSatuanBarang" => "newton metre per square metre"],
    ["kodeSatuanBarang" => "M35", "namaSatuanBarang" => "millivolt - ampere"],
    ["kodeSatuanBarang" => "M39", "namaSatuanBarang" => "centimetre per second squared"],
    ["kodeSatuanBarang" => "M4", "namaSatuanBarang" => "monetary value"],
    ["kodeSatuanBarang" => "M40", "namaSatuanBarang" => "yard per second squared"],
    ["kodeSatuanBarang" => "M44", "namaSatuanBarang" => "revolution"],
    ["kodeSatuanBarang" => "M46", "namaSatuanBarang" => "revolution per minute"],
    ["kodeSatuanBarang" => "M49", "namaSatuanBarang" => "chain (based on U.S. survey foot)"],
    ["kodeSatuanBarang" => "M5", "namaSatuanBarang" => "microcurie"],
    ["kodeSatuanBarang" => "M50", "namaSatuanBarang" => "furlong"],
    ["kodeSatuanBarang" => "M51", "namaSatuanBarang" => "foot (U.S. survey)"],
    ["kodeSatuanBarang" => "M52", "namaSatuanBarang" => "mile (based on U.S. survey foot)"],
    ["kodeSatuanBarang" => "M55", "namaSatuanBarang" => "metre per radiant"],
    ["kodeSatuanBarang" => "M57", "namaSatuanBarang" => "mile per minute"],
    ["kodeSatuanBarang" => "M58", "namaSatuanBarang" => "mile per second"],
    ["kodeSatuanBarang" => "M59", "namaSatuanBarang" => "metre per second pascal"],
    ["kodeSatuanBarang" => "M60", "namaSatuanBarang" => "metre per hour"],
    ["kodeSatuanBarang" => "M61", "namaSatuanBarang" => "inch per year"],
    ["kodeSatuanBarang" => "M62", "namaSatuanBarang" => "kilometre per second"],
    ["kodeSatuanBarang" => "M63", "namaSatuanBarang" => "inch per minute"],
    ["kodeSatuanBarang" => "M64", "namaSatuanBarang" => "yard per second"],
    ["kodeSatuanBarang" => "M65", "namaSatuanBarang" => "yard per minute"],
    ["kodeSatuanBarang" => "M66", "namaSatuanBarang" => "yard per hour"],
    ["kodeSatuanBarang" => "M7", "namaSatuanBarang" => "micro-inch"],
    ["kodeSatuanBarang" => "M70", "namaSatuanBarang" => "ton, register"],
    ["kodeSatuanBarang" => "M71", "namaSatuanBarang" => "cubic metre per pascal"],
    ["kodeSatuanBarang" => "M73", "namaSatuanBarang" => "kilogram per cubic metre pascal"],
    ["kodeSatuanBarang" => "M74", "namaSatuanBarang" => "kilogram per pascal"],
    ["kodeSatuanBarang" => "M76", "namaSatuanBarang" => "poundal"],
    ["kodeSatuanBarang" => "M78", "namaSatuanBarang" => "pond"],
    ["kodeSatuanBarang" => "M81", "namaSatuanBarang" => "square centimetre per second"],
    ["kodeSatuanBarang" => "M82", "namaSatuanBarang" => "square metre per second pascal"],
    ["kodeSatuanBarang" => "M83", "namaSatuanBarang" => "denier"],
    ["kodeSatuanBarang" => "M84", "namaSatuanBarang" => "pound per yard"],
    ["kodeSatuanBarang" => "M87", "namaSatuanBarang" => "kilogram per second pascal"],
    ["kodeSatuanBarang" => "M89", "namaSatuanBarang" => "tonne per year"],
    ["kodeSatuanBarang" => "M90", "namaSatuanBarang" => "kilopound per hour"],
    ["kodeSatuanBarang" => "M95", "namaSatuanBarang" => "poundal foot"],
    ["kodeSatuanBarang" => "M97", "namaSatuanBarang" => "dyne metre"],
    ["kodeSatuanBarang" => "MA", "namaSatuanBarang" => "machine per unit"],
    ["kodeSatuanBarang" => "MAD", "namaSatuanBarang" => "Morocco Dirham"],
    ["kodeSatuanBarang" => "MAH", "namaSatuanBarang" => "megavolt ampere reactive hour"],
    ["kodeSatuanBarang" => "MAL", "namaSatuanBarang" => "Megalitre"],
    ["kodeSatuanBarang" => "MAR", "namaSatuanBarang" => "megavolt ampere reactive"],
    ["kodeSatuanBarang" => "MAW", "namaSatuanBarang" => "Megawatt"],
    ["kodeSatuanBarang" => "MBE", "namaSatuanBarang" => "thousand standard brick equivalent"],
    ["kodeSatuanBarang" => "MBF", "namaSatuanBarang" => "thousand board foot"],
    ["kodeSatuanBarang" => "MDL", "namaSatuanBarang" => "Moldova Leu"],
    ["kodeSatuanBarang" => "MF", "namaSatuanBarang" => "milligram per square foot per side"],
    ["kodeSatuanBarang" => "MGA", "namaSatuanBarang" => "Madagascar Ariary"],
    ["kodeSatuanBarang" => "MGM", "namaSatuanBarang" => "Milligram"],
    ["kodeSatuanBarang" => "MID", "namaSatuanBarang" => "Thousand"],
    ["kodeSatuanBarang" => "MIL", "namaSatuanBarang" => "thousand"],
    ["kodeSatuanBarang"=> "MIN", "namaSatuanBarang" => "Minute"],
    ["kodeSatuanBarang" => "MKD", "namaSatuanBarang" => "Macedonia Denar"],
    ["kodeSatuanBarang" => "MLD", "namaSatuanBarang" => "Billion US"],
    ["kodeSatuanBarang" => "MMK", "namaSatuanBarang" => "Square millimetre"],
    ["kodeSatuanBarang" => "MMT", "namaSatuanBarang" => "Millimetre"],
    ["kodeSatuanBarang" => "MNT", "namaSatuanBarang" => "Mongolia Tughrik"],
    ["kodeSatuanBarang" => "MOP", "namaSatuanBarang" => "Macau Pataca"],
    ["kodeSatuanBarang" => "MPA", "namaSatuanBarang" => "megapascal"],
    ["kodeSatuanBarang" => "MQ", "namaSatuanBarang" => "thousand metre"],
    ["kodeSatuanBarang" => "MQH", "namaSatuanBarang" => "cubic metre per hour"],
    ["kodeSatuanBarang" => "MQS", "namaSatuanBarang" => "cubic metre per second"],
    ["kodeSatuanBarang" => "MT", "namaSatuanBarang" => "mat"],
    ["kodeSatuanBarang" => "MTK", "namaSatuanBarang" => "Square metre"],
    ["kodeSatuanBarang" => "MUR", "namaSatuanBarang" => "Mauritius Rupee"],
    ["kodeSatuanBarang" => "MWK", "namaSatuanBarang" => "Malawi Kwacha"],
    ["kodeSatuanBarang" => "MXN", "namaSatuanBarang" => "Mexico Peso"],
    ["kodeSatuanBarang" => "MYR", "namaSatuanBarang" => "Malaysia Ringgit"],
    ["kodeSatuanBarang" => "N10", "namaSatuanBarang" => "pound foot per second"],
    ["kodeSatuanBarang" => "N11", "namaSatuanBarang" => "pound inch per second"]
        ];

        DB::table('satuan_barang')->insert($satuanBarang);
        }
    }
