<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SatuanBarangSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $satuanBarang = [
            ['kodeSatuanBarang' => 6, 'namaSatuanBarang' => 'small spray'],
            ['kodeSatuanBarang' => 6, 'namaSatuanBarang' => 'small spray'],
            ['kodeSatuanBarang' => 8, 'namaSatuanBarang' => 'heat lot'],
            ['kodeSatuanBarang' => 10, 'namaSatuanBarang' => 'group'],
            ['kodeSatuanBarang' => 13, 'namaSatuanBarang' => 'ration'],
            ['kodeSatuanBarang' => 13, 'namaSatuanBarang' => 'ration'],
            ['kodeSatuanBarang' => 14, 'namaSatuanBarang' => 'shot'],
            ['kodeSatuanBarang' => 15, 'namaSatuanBarang' => 'stick, military'],
            ['kodeSatuanBarang' => 16, 'namaSatuanBarang' => 'hundred fifteen kg drum'],
            ['kodeSatuanBarang' => 16, 'namaSatuanBarang' => 'hundred fifteen kg drum'],
            ['kodeSatuanBarang' => 17, 'namaSatuanBarang' => 'hundred lb drum'],
            ['kodeSatuanBarang' => 17, 'namaSatuanBarang' => 'hundred lb drum'],
            ['kodeSatuanBarang' => 18, 'namaSatuanBarang' => 'fiftyfive gallon (US) drum'],
            ['kodeSatuanBarang' => 18, 'namaSatuanBarang' => 'fiftyfive gallon (US) drum'],
            ['kodeSatuanBarang' => 19, 'namaSatuanBarang' => 'tank truck'],
            ['kodeSatuanBarang' => 20, 'namaSatuanBarang' => 'twenty foot container'],
            ['kodeSatuanBarang' => 20, 'namaSatuanBarang' => 'twenty foot container'],
            ['kodeSatuanBarang' => 21, 'namaSatuanBarang' => 'forty foot container'],
            ['kodeSatuanBarang' => 22, 'namaSatuanBarang' => 'decilitre per gram'],
            ['kodeSatuanBarang' => 24, 'namaSatuanBarang' => 'theoretical pound'],
            ['kodeSatuanBarang' => 26, 'namaSatuanBarang' => 'actual ton'],
            ['kodeSatuanBarang' => 28, 'namaSatuanBarang' => 'kilogram per square metre'],
            ['kodeSatuanBarang' => 28, 'namaSatuanBarang' => 'kilogram per square metre'],
            ['kodeSatuanBarang' => 29, 'namaSatuanBarang' => 'pound per thousand square foot'],
            ['kodeSatuanBarang' => 30, 'namaSatuanBarang' => 'horse power day per air dry metric ton'],
            ['kodeSatuanBarang' => 31, 'namaSatuanBarang' => 'catch weight'],
            ['kodeSatuanBarang' => 32, 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => 33, 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => 34, 'namaSatuanBarang' => 'kilopascal per millimetre'],
            ['kodeSatuanBarang' => 35, 'namaSatuanBarang' => 'millilitre per square centimetre second'],
            ['kodeSatuanBarang' => 36, 'namaSatuanBarang' => 'cubic foot per minute per square foot'],
            ['kodeSatuanBarang' => 38, 'namaSatuanBarang' => 'ounce per square foot per 0,01inch'],
            ['kodeSatuanBarang' => 40, 'namaSatuanBarang' => 'millilitre per second'],
            ['kodeSatuanBarang' => 40, 'namaSatuanBarang' => 'millilitre per second'],
            ['kodeSatuanBarang' => 43, 'namaSatuanBarang' => 'super bulk bag'],
            ['kodeSatuanBarang' => 44, 'namaSatuanBarang' => 'fivehundred kg bulk bag'],
            ['kodeSatuanBarang' => 46, 'namaSatuanBarang' => 'fifty lb bulk bag'],
            ['kodeSatuanBarang' => 47, 'namaSatuanBarang' => 'fifty lb bag'],
            ['kodeSatuanBarang' => 48, 'namaSatuanBarang' => 'bulk car load'],
            ['kodeSatuanBarang' => 53, 'namaSatuanBarang' => 'theoretical kilogram'],
            ['kodeSatuanBarang' => 54, 'namaSatuanBarang' => 'theoretical tonne'],
            ['kodeSatuanBarang' => 57, 'namaSatuanBarang' => 'mesh'],
            ['kodeSatuanBarang' => 58, 'namaSatuanBarang' => 'net kilogram'],
            ['kodeSatuanBarang' => 60, 'namaSatuanBarang' => 'percent weight'],
            ['kodeSatuanBarang' => 61, 'namaSatuanBarang' => 'part per billion (US)'],
            ['kodeSatuanBarang' => 62, 'namaSatuanBarang' => 'percent per 1000 hour'],
            ['kodeSatuanBarang' => 63, 'namaSatuanBarang' => 'failure rate in time'],
            ['kodeSatuanBarang' => 64, 'namaSatuanBarang' => 'pound per square inch, gauge'],
            ['kodeSatuanBarang' => 64, 'namaSatuanBarang' => 'pound per square inch, gauge'],
            ['kodeSatuanBarang' => 66, 'namaSatuanBarang' => 'oersted'],
            ['kodeSatuanBarang' => 66, 'namaSatuanBarang' => 'oersted'],
            ['kodeSatuanBarang' => 71, 'namaSatuanBarang' => 'volt ampere per pound'],
            ['kodeSatuanBarang' => 71, 'namaSatuanBarang' => 'volt ampere per pound'],
            ['kodeSatuanBarang' => 72, 'namaSatuanBarang' => 'watt per pound'],
            ['kodeSatuanBarang' => 73, 'namaSatuanBarang' => 'ampere tum per centimetre'],
            ['kodeSatuanBarang' => 73, 'namaSatuanBarang' => 'ampere tum per centimetre'],
            ['kodeSatuanBarang' => 78, 'namaSatuanBarang' => 'kilogauss'],
            ['kodeSatuanBarang' => 78, 'namaSatuanBarang' => 'kilogauss'],
            ['kodeSatuanBarang' => 84, 'namaSatuanBarang' => 'kilopound-force per square inch'],
            ['kodeSatuanBarang' => 84, 'namaSatuanBarang' => 'kilopound-force per square inch'],
            ['kodeSatuanBarang' => 85, 'namaSatuanBarang' => 'foot pound-force'],
            ['kodeSatuanBarang' => 85, 'namaSatuanBarang' => 'foot pound-force'],
            ['kodeSatuanBarang' => 89, 'namaSatuanBarang' => 'poise'],
            ['kodeSatuanBarang' => 89, 'namaSatuanBarang' => 'poise'],
            ['kodeSatuanBarang' => 92, 'namaSatuanBarang' => 'calorie per cubic centimetre'],
            ['kodeSatuanBarang' => 92, 'namaSatuanBarang' => 'calorie per cubic centimetre'],
            ['kodeSatuanBarang' => 93, 'namaSatuanBarang' => 'calorie per gram'],
            ['kodeSatuanBarang' => 93, 'namaSatuanBarang' => 'calorie per gram'],
            ['kodeSatuanBarang' => 94, 'namaSatuanBarang' => 'curl unit'],
            ['kodeSatuanBarang' => 94, 'namaSatuanBarang' => 'curl unit'],
            ['kodeSatuanBarang' => 96, 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => 96, 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => 97, 'namaSatuanBarang' => 'ten kg drum'],
            ['kodeSatuanBarang' => 98, 'namaSatuanBarang' => 'fifteen kg drum'],
            ['kodeSatuanBarang' => 98, 'namaSatuanBarang' => 'fifteen kg drum'],
            ['kodeSatuanBarang' => '1C', 'namaSatuanBarang' => 'locomotive count'],
            ['kodeSatuanBarang' => '1C', 'namaSatuanBarang' => 'locomotive count'],
            ['kodeSatuanBarang' => '1F', 'namaSatuanBarang' => 'train mile'],
            ['kodeSatuanBarang' => '1F', 'namaSatuanBarang' => 'train mile'],
            ['kodeSatuanBarang' => '1I', 'namaSatuanBarang' => 'fixed rate'],
            ['kodeSatuanBarang' => '1L', 'namaSatuanBarang' => 'total car count'],
            ['kodeSatuanBarang' => '1M', 'namaSatuanBarang' => 'total train count'],
            ['kodeSatuanBarang' => '1X', 'namaSatuanBarang' => 'car count'],
            ['kodeSatuanBarang' => '1Y', 'namaSatuanBarang' => 'car mile'],
            ['kodeSatuanBarang' => '2A', 'namaSatuanBarang' => 'twenty thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '2A', 'namaSatuanBarang' => 'twenty thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '2B', 'namaSatuanBarang' => 'barrel, dry (US)'],
            ['kodeSatuanBarang' => '2B', 'namaSatuanBarang' => 'barrel, dry (US)'],
            ['kodeSatuanBarang' => '2C', 'namaSatuanBarang' => 'barrel, liquid (US)'],
            ['kodeSatuanBarang' => '2C', 'namaSatuanBarang' => 'barrel, liquid (US)'],
            ['kodeSatuanBarang' => '2G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '2G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '2H', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '2H', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '2I', 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => '2I', 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => '2J', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '2J', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '2K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '2K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '2L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '2L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '2M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '2M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '2N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '2N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '2Q', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '2Q', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '2R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '2R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '2U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '2U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '2X', 'namaSatuanBarang' => 'ton mile'],
            ['kodeSatuanBarang' => '2Y', 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => '2Y', 'namaSatuanBarang' => 'kilopascal square metre per gram'],
            ['kodeSatuanBarang' => '2Z', 'namaSatuanBarang' => 'megajoule per cubic metre'],
            ['kodeSatuanBarang' => '2Z', 'namaSatuanBarang' => 'megajoule per cubic metre'],
            ['kodeSatuanBarang' => '4G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '4G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '4H', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '4H', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '4K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '4K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '4L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '4L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '4M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '4M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '4N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '4N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '4P', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '4P', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '4R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '4R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '4U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '4U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '5D', 'namaSatuanBarang' => 'barrel, liquid (US)'],
            ['kodeSatuanBarang' => '5D', 'namaSatuanBarang' => 'barrel, liquid (US)'],
            ['kodeSatuanBarang' => '5E', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '5E', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '5F', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '5F', 'namaSatuanBarang' => 'kilolitre per hectare'],
            ['kodeSatuanBarang' => '5K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '5K', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '5L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '5L', 'namaSatuanBarang' => 'degree day (Fahrenheit)'],
            ['kodeSatuanBarang' => '5M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '5M', 'namaSatuanBarang' => 'degree day (Celsius)'],
            ['kodeSatuanBarang' => '5N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '5N', 'namaSatuanBarang' => 'kilojoule per gram'],
            ['kodeSatuanBarang' => '5P', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '5P', 'namaSatuanBarang' => 'pound per air dry metric ton'],
            ['kodeSatuanBarang' => '5R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '5R', 'namaSatuanBarang' => 'kilogram per air dry metric ton'],
            ['kodeSatuanBarang' => '5U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '5U', 'namaSatuanBarang' => 'ten thousand gallon (US) tankcar'],
            ['kodeSatuanBarang' => '7G', 'namaSatuanBarang' => 'microcurie'],
            ['kodeSatuanBarang' => '7G', 'namaSatuanBarang' => 'microcurie']
        ];
        $satuanBarang = array_unique($satuanBarang, SORT_REGULAR);

        DB::table('satuan_barang')->insert($satuanBarang);
        }
    }
