<?php

namespace Database\Seeders\DataMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ValutaSeeder extends Seeder
    {
    /**
     * Run the database seeds.
     */
    public function run() : void
        {
        $valutas = [
            ['kodeValuta' => 'ADP', 'namaValuta' => 'Andorran Peseta'],
            ['kodeValuta' => 'AED', 'namaValuta' => 'UAE Dirham'],
            ['kodeValuta' => 'AFA', 'namaValuta' => 'Afghani'],
            ['kodeValuta' => 'AFN', 'namaValuta' => 'Afghani'],
            ['kodeValuta' => 'ALL', 'namaValuta' => 'Lek'],
            ['kodeValuta' => 'AMD', 'namaValuta' => 'Armenian Dram'],
            ['kodeValuta' => 'ANG', 'namaValuta' => 'Netherlands Antillian Guilder'],
            ['kodeValuta' => 'AOA', 'namaValuta' => 'Kwanza'],
            ['kodeValuta' => 'AON', 'namaValuta' => 'New Kwanza'],
            ['kodeValuta' => 'ARS', 'namaValuta' => 'Argentina Peso'],
            ['kodeValuta' => 'ATS', 'namaValuta' => 'Schilling'],
            ['kodeValuta' => 'AUD', 'namaValuta' => 'Australian Dollar'],
            ['kodeValuta' => 'AWG', 'namaValuta' => 'Aruban Guilder'],
            ['kodeValuta' => 'AZM', 'namaValuta' => 'Azerbaijanian Manat'],
            ['kodeValuta' => 'AZN', 'namaValuta' => 'Azerbaijanian Manat'],
            ['kodeValuta' => 'BAM', 'namaValuta' => 'Convertible Marks'],
            ['kodeValuta' => 'BBD', 'namaValuta' => 'Barbados Dollar'],
            ['kodeValuta' => 'BDT', 'namaValuta' => 'Taka'],
            ['kodeValuta' => 'BEF', 'namaValuta' => 'Belgian Franc'],
            ['kodeValuta' => 'BGL', 'namaValuta' => 'Lev'],
            ['kodeValuta' => 'BGN', 'namaValuta' => 'Bulgarian Lev'],
            ['kodeValuta' => 'BHD', 'namaValuta' => 'Bahraini Dinar'],
            ['kodeValuta' => 'BIF', 'namaValuta' => 'Burundi Franc'],
            ['kodeValuta' => 'BMD', 'namaValuta' => 'Bermudian Dollar'],
            ['kodeValuta' => 'BND', 'namaValuta' => 'Brunei Dollar'],
            ['kodeValuta' => 'BOB', 'namaValuta' => 'Boliaiano'],
            ['kodeValuta' => 'BOV', 'namaValuta' => 'Mvdol'],
            ['kodeValuta' => 'BRL', 'namaValuta' => 'Brazilian Real'],
            ['kodeValuta' => 'BSD', 'namaValuta' => 'Bahamian Dollar'],
            ['kodeValuta' => 'BTN', 'namaValuta' => 'Ngultrum'],
            ['kodeValuta' => 'BWP', 'namaValuta' => 'Pula'],
            ['kodeValuta' => 'BYB', 'namaValuta' => 'Belarussian Ruble'],
            ['kodeValuta' => 'BYR', 'namaValuta' => 'Belarussian Ruble'],
            ['kodeValuta' => 'BZD', 'namaValuta' => 'Belize Dollar'],
            ['kodeValuta' => 'CAD', 'namaValuta' => 'Canadian Dollar'],
            ['kodeValuta' => 'CDF', 'namaValuta' => 'Congolese Franc'],
            ['kodeValuta' => 'CHE', 'namaValuta' => 'WIR Euro'],
            ['kodeValuta' => 'CHF', 'namaValuta' => 'Swiss Franc'],
            ['kodeValuta' => 'CHW', 'namaValuta' => 'WIR Franc'],
            ['kodeValuta' => 'CLF', 'namaValuta' => 'Unidades de fomento'],
            ['kodeValuta' => 'CLP', 'namaValuta' => 'Chilean Peso'],
            ['kodeValuta' => 'CNY', 'namaValuta' => 'Yuan Renminbi'],
            ['kodeValuta' => 'COP', 'namaValuta' => 'Colombian Peso'],
            ['kodeValuta' => 'COU', 'namaValuta' => 'Unidad de Valor Real'],
            ['kodeValuta' => 'CRC', 'namaValuta' => 'Costa Rican Colon'],
            ['kodeValuta' => 'CUC', 'namaValuta' => 'Peso Convertible'],
            ['kodeValuta' => 'CUP', 'namaValuta' => 'Cuban Peso'],
            ['kodeValuta' => 'CVE', 'namaValuta' => 'Cape Verde Escudo'],
            ['kodeValuta' => 'CYP', 'namaValuta' => 'Cyprus Pound'],
            ['kodeValuta' => 'CZK', 'namaValuta' => 'Czech Koruna'],
            ['kodeValuta' => 'DEM', 'namaValuta' => 'Deustche Mark'],
            ['kodeValuta' => 'DJF', 'namaValuta' => 'Djibouti Franc'],
            ['kodeValuta' => 'DKK', 'namaValuta' => 'Danish Krone'],
            ['kodeValuta' => 'DOP', 'namaValuta' => 'Domincan Peso'],
            ['kodeValuta' => 'DZD', 'namaValuta' => 'Algerian Dinar'],
            ['kodeValuta' => 'ECS', 'namaValuta' => 'Sucre'],
            ['kodeValuta' => 'EEK', 'namaValuta' => 'Kroon'],
            ['kodeValuta' => 'EGP', 'namaValuta' => 'Egyptian Pound'],
            ['kodeValuta' => 'ERN', 'namaValuta' => 'Nakfa'],
            ['kodeValuta' => 'ESP', 'namaValuta' => 'Spainish peseta'],
            ['kodeValuta' => 'ETB', 'namaValuta' => 'Ethiopian Birr'],
            ['kodeValuta' => 'FIM', 'namaValuta' => 'Markka'],
            ['kodeValuta' => 'FJD', 'namaValuta' => 'Fiji Dollar'],
            ['kodeValuta' => 'FKP', 'namaValuta' => 'Falkland Islands Pound'],
            ['kodeValuta' => 'FRF', 'namaValuta' => 'Franch Franc'],
            ['kodeValuta' => 'GBP', 'namaValuta' => 'Pound Sterling'],
            ['kodeValuta' => 'GEK', 'namaValuta' => 'Georgian Coupon'],
            ['kodeValuta' => 'GEL', 'namaValuta' => 'Lari'],
            ['kodeValuta' => 'GHC', 'namaValuta' => 'Cedi'],
            ['kodeValuta' => 'GHS', 'namaValuta' => 'Cedi'],
            ['kodeValuta' => 'GIP', 'namaValuta' => 'Gibraltar Pound'],
            ['kodeValuta' => 'GMD', 'namaValuta' => 'Dalasi'],
            ['kodeValuta' => 'GNF', 'namaValuta' => 'Guinea Franc'],
            ['kodeValuta' => 'GRD', 'namaValuta' => 'Drachma'],
            ['kodeValuta' => 'GTQ', 'namaValuta' => 'Quetzal'],
            ['kodeValuta' => 'GWP', 'namaValuta' => 'Guinea-Bissau Peso'],
            ['kodeValuta' => 'GYD', 'namaValuta' => 'Guyana Dollar'],
            ['kodeValuta' => 'HKD', 'namaValuta' => 'Hong Kong Dollar'],
            ['kodeValuta' => 'HNL', 'namaValuta' => 'Lempira'],
            ['kodeValuta' => 'HRD', 'namaValuta' => 'Croatian Dinar'],
            ['kodeValuta' => 'HRK', 'namaValuta' => 'Kuna'],
            ['kodeValuta' => 'HTG', 'namaValuta' => 'Gourde'],
            ['kodeValuta' => 'HUF', 'namaValuta' => 'Forint'],
            ['kodeValuta' => 'IDR', 'namaValuta' => 'Rupiah'],
            ['kodeValuta' => 'IEP', 'namaValuta' => 'Irish Pound'],
            ['kodeValuta' => 'ILS', 'namaValuta' => 'Shekel'],
            ['kodeValuta' => 'INR', 'namaValuta' => 'Indian Rupee'],
            ['kodeValuta' => 'IQD', 'namaValuta' => 'Iraqi Dinar'],
            ['kodeValuta' => 'IRR', 'namaValuta' => 'Iranian Rial'],
            ['kodeValuta' => 'ISK', 'namaValuta' => 'Iceland Krona'],
            ['kodeValuta' => 'ITL', 'namaValuta' => 'Italian Lira'],
            ['kodeValuta' => 'JMD', 'namaValuta' => 'Jamaican Dollar'],
            ['kodeValuta' => 'JOD', 'namaValuta' => 'Jordanian Dinar'],
            ['kodeValuta' => 'JPY', 'namaValuta' => 'Yen'],
            ['kodeValuta' => 'KES', 'namaValuta' => 'Kenyan Shilling'],
            ['kodeValuta' => 'KGS', 'namaValuta' => 'Som'],
            ['kodeValuta' => 'KHR', 'namaValuta' => 'Riel'],
            ['kodeValuta' => 'KMF', 'namaValuta' => 'Comoro Franc'],
            ['kodeValuta' => 'KPW', 'namaValuta' => 'North Korean Won'],
            ['kodeValuta' => 'KRW', 'namaValuta' => 'Won'],
            ['kodeValuta' => 'KWD', 'namaValuta' => 'Kuwauti Dinar'],
            ['kodeValuta' => 'KYD', 'namaValuta' => 'Cayman Islands Dollar'],
            ['kodeValuta' => 'KZT', 'namaValuta' => 'Tenge'],
            ['kodeValuta' => 'LAK', 'namaValuta' => 'Kip'],
            ['kodeValuta' => 'LBP', 'namaValuta' => 'Lebanese Pound'],
            ['kodeValuta' => 'LKR', 'namaValuta' => 'Sri Langka Rupee'],
            ['kodeValuta' => 'LRD', 'namaValuta' => 'Liberian Dollar'],
            ['kodeValuta' => 'LSL', 'namaValuta' => 'Loli'],
            ['kodeValuta' => 'LTL', 'namaValuta' => 'Lithuanian Litas'],
            ['kodeValuta' => 'LUF', 'namaValuta' => 'Luxembourg Franc'],
            ['kodeValuta' => 'LVL', 'namaValuta' => 'Latvian Lats'],
            ['kodeValuta' => 'LVR', 'namaValuta' => 'Latvian Ruble'],
            ['kodeValuta' => 'LYD', 'namaValuta' => 'Libyan Dinar'],
            ['kodeValuta' => 'MAD', 'namaValuta' => 'Moroccoan Dirham'],
            ['kodeValuta' => 'MDL', 'namaValuta' => 'Moldovan Leu'],
            ['kodeValuta' => 'MGA', 'namaValuta' => 'Malagasy Ariary'],
            ['kodeValuta' => 'MGF', 'namaValuta' => 'Malagasy Franc'],
            ['kodeValuta' => 'MKD', 'namaValuta' => 'Denar'],
            ['kodeValuta' => 'MMK', 'namaValuta' => 'Kyat'],
            ['kodeValuta' => 'MNT', 'namaValuta' => 'Tugrik'],
            ['kodeValuta' => 'MOP', 'namaValuta' => 'Pataca'],
            ['kodeValuta' => 'MRO', 'namaValuta' => 'Ouguiya'],
            ['kodeValuta' => 'MTL', 'namaValuta' => 'Mallese Lira'],
            ['kodeValuta' => 'MUR', 'namaValuta' => 'Mauritius Pupee'],
            ['kodeValuta' => 'MVR', 'namaValuta' => 'Rufiyaa'],
            ['kodeValuta' => 'MWK', 'namaValuta' => 'Kwacha'],
            ['kodeValuta' => 'MXN', 'namaValuta' => 'Mexican Nuevo Peso'],
            ['kodeValuta' => 'MXV', 'namaValuta' => 'Mexican Unidad de Inversion (UDI)'],
            ['kodeValuta' => 'MYR', 'namaValuta' => 'Malaysian Ringgit'],
            ['kodeValuta' => 'MZM', 'namaValuta' => 'Metical'],
            ['kodeValuta' => 'MZN', 'namaValuta' => 'Metical'],
            ['kodeValuta' => 'NAD', 'namaValuta' => 'Namibia Dollar'],
            ['kodeValuta' => 'NGN', 'namaValuta' => 'Naira'],
            ['kodeValuta' => 'NIO', 'namaValuta' => 'Cordoba Oro'],
            ['kodeValuta' => 'NLG', 'namaValuta' => 'Netherlands Guilder'],
            ['kodeValuta' => 'NOK', 'namaValuta' => 'Norwegian Krone'],
            ['kodeValuta' => 'NPR', 'namaValuta' => 'Nepalese Rupee'],
            ['kodeValuta' => 'NZD', 'namaValuta' => 'New Zealand Dollar'],
            ['kodeValuta' => 'OMR', 'namaValuta' => 'Rial Omani'],
            ['kodeValuta' => 'PAB', 'namaValuta' => 'Balboa/US Dollar'],
            ['kodeValuta' => 'PEN', 'namaValuta' => 'Nuevo Sol'],
            ['kodeValuta' => 'PGK', 'namaValuta' => 'Kina'],
            ['kodeValuta' => 'PHP', 'namaValuta' => 'Philippines Peso'],
            ['kodeValuta' => 'PKR', 'namaValuta' => 'Pakistan Rupee'],
            ['kodeValuta' => 'PLN', 'namaValuta' => 'Zloty'],
            ['kodeValuta' => 'PLZ', 'namaValuta' => 'Zloty'],
            ['kodeValuta' => 'PTE', 'namaValuta' => 'Portuguese Escudo'],
            ['kodeValuta' => 'PYG', 'namaValuta' => 'Guarani'],
            ['kodeValuta' => 'QAR', 'namaValuta' => 'Qatari Rial'],
            ['kodeValuta' => 'ROL', 'namaValuta' => 'Leu'],
            ['kodeValuta' => 'RON', 'namaValuta' => 'New Leu'],
            ['kodeValuta' => 'RSD', 'namaValuta' => 'Serbian Dinar'],
            ['kodeValuta' => 'RUB', 'namaValuta' => 'Russian Ruble'],
            ['kodeValuta' => 'RUR', 'namaValuta' => 'Russian Ruble'],
            ['kodeValuta' => 'RWF', 'namaValuta' => 'Rwanda Franc'],
            ['kodeValuta' => 'SAR', 'namaValuta' => 'Saudi Riyal'],
            ['kodeValuta' => 'SBD', 'namaValuta' => 'Solomon Islands Dollar'],
            ['kodeValuta' => 'SCR', 'namaValuta' => 'Seychelles Rupee'],
            ['kodeValuta' => 'SDD', 'namaValuta' => 'Sudanase Dinar'],
            ['kodeValuta' => 'SDG', 'namaValuta' => 'Sudanese Pound'],
            ['kodeValuta' => 'SDP', 'namaValuta' => 'Sudanese Pound'],
            ['kodeValuta' => 'SEK', 'namaValuta' => 'Swedish Krone'],
            ['kodeValuta' => 'SGD', 'namaValuta' => 'Singapore Dollar'],
            ['kodeValuta' => 'SHP', 'namaValuta' => 'St. Helena Pound'],
            ['kodeValuta' => 'SIT', 'namaValuta' => 'Tolar'],
            ['kodeValuta' => 'SKK', 'namaValuta' => 'Slovak Koruna'],
            ['kodeValuta' => 'SLL', 'namaValuta' => 'Leone'],
            ['kodeValuta' => 'SOS', 'namaValuta' => 'Somalia shilling'],
            ['kodeValuta' => 'SRD', 'namaValuta' => 'Surinam Dollar'],
            ['kodeValuta' => 'SRG', 'namaValuta' => 'Surinam Guilder'],
            ['kodeValuta' => 'STD', 'namaValuta' => 'Dobra'],
            ['kodeValuta' => 'SVC', 'namaValuta' => 'El Salvador Colon'],
            ['kodeValuta' => 'SYP', 'namaValuta' => 'Syrian Pound'],
            ['kodeValuta' => 'SZL', 'namaValuta' => 'Lilangeni'],
            ['kodeValuta' => 'THB', 'namaValuta' => 'Baht'],
            ['kodeValuta' => 'TJS', 'namaValuta' => 'Somoni'],
            ['kodeValuta' => 'TMM', 'namaValuta' => 'Manat'],
            ['kodeValuta' => 'TMT', 'namaValuta' => 'Manat'],
            ['kodeValuta' => 'TND', 'namaValuta' => 'Tunisian Dinar'],
            ['kodeValuta' => 'TOP', 'namaValuta' => 'Pa\'anga'],
            ['kodeValuta' => 'TRL', 'namaValuta' => 'Turkish Lira'],
            ['kodeValuta' => 'TRY', 'namaValuta' => 'Turkish Lira'],
            ['kodeValuta' => 'TTD', 'namaValuta' => 'Trinidad and Tobago Dollar'],
            ['kodeValuta' => 'TWD', 'namaValuta' => 'New Taiwan Dollar'],
            ['kodeValuta' => 'TZS', 'namaValuta' => 'Tanzania Shilling'],
            ['kodeValuta' => 'UAH', 'namaValuta' => 'Hryvnia'],
            ['kodeValuta' => 'UAK', 'namaValuta' => 'Karbovanet'],
            ['kodeValuta' => 'UGX', 'namaValuta' => 'Uganda Shilling'],
            ['kodeValuta' => 'USD', 'namaValuta' => 'US Dollar'],
            ['kodeValuta' => 'UYI', 'namaValuta' => 'Uruguay Peso en Unidades Indexadas'],
            ['kodeValuta' => 'UYU', 'namaValuta' => 'Peso Uruguayo'],
            ['kodeValuta' => 'UZS', 'namaValuta' => 'Ubekistan Sum'],
            ['kodeValuta' => 'VEB', 'namaValuta' => 'Bolivar'],
            ['kodeValuta' => 'VEF', 'namaValuta' => 'Bolivar Fuerte'],
            ['kodeValuta' => 'VND', 'namaValuta' => 'Dong'],
            ['kodeValuta' => 'VUV', 'namaValuta' => 'Vatu'],
            ['kodeValuta' => 'WST', 'namaValuta' => 'Tala'],
            ['kodeValuta' => 'YER', 'namaValuta' => 'Yemeni Rial'],
            ['kodeValuta' => 'YUN', 'namaValuta' => 'New Yugosslavian'],
            ['kodeValuta' => 'ZAL', 'namaValuta' => 'Financial Rand'],
            ['kodeValuta' => 'ZAR', 'namaValuta' => 'Rand'],
            ['kodeValuta' => 'ZMK', 'namaValuta' => 'Kwacha'],
            ['kodeValuta' => 'ZWD', 'namaValuta' => 'Zimbabwe Dollar'],
            ['kodeValuta' => 'ZWL', 'namaValuta' => 'Zimbabwe Dollar']
        ];
        $faker   = \Faker\Factory::create();
        foreach ( $valutas as $data ) {
            \App\Models\DataMaster\Valuta::create([
                'kodeValuta' => $data['kodeValuta'],
                'namaValuta' => $data['namaValuta'],
                'kurs'       => $faker->randomFloat(2, 0.1, 100),
            ]);
            }
        }
    }
